/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH                         *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.48                          *
 *        Compiled Jun 13 2018, 10:51:02                              *
 *        (c) 2018 Segger Microcontroller GmbH                        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "PTT_Global.h"
extern uint8_t language_version;
extern void Pg_Call_Job_0_array_init(void);
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0a)
#define ID_TEXT_10 (GUI_ID_USER + 0x0b)
#define ID_TEXT_11 (GUI_ID_USER + 0x0c)
#define ID_TEXT_12 (GUI_ID_USER + 0x0d)
#define ID_TEXT_13 (GUI_ID_USER + 0x0e)
#define ID_TEXT_14 (GUI_ID_USER + 0x0f)
#define ID_TEXT_15 (GUI_ID_USER + 0x10)
#define ID_TEXT_16 (GUI_ID_USER + 0x11)
#define ID_TEXT_17 (GUI_ID_USER + 0x12)
#define ID_TEXT_18 (GUI_ID_USER + 0x13)
#define ID_TEXT_19 (GUI_ID_USER + 0x14)
#define ID_TEXT_20 (GUI_ID_USER + 0x15)
#define ID_TEXT_21 (GUI_ID_USER + 0x16)
#define ID_TEXT_22 (GUI_ID_USER + 0x17)
#define ID_TEXT_23 (GUI_ID_USER + 0x18)
#define ID_TEXT_24 (GUI_ID_USER + 0x19)
#define ID_TEXT_25 (GUI_ID_USER + 0x1a)
#define ID_TEXT_26 (GUI_ID_USER + 0x1b)
#define ID_TEXT_27 (GUI_ID_USER + 0x1c)
#define ID_BUTTON_0 (GUI_ID_USER + 0x1d)
#define ID_BUTTON_1 (GUI_ID_USER + 0x1e)
#define ID_BUTTON_2 (GUI_ID_USER + 0x1f)
#define ID_BUTTON_3 (GUI_ID_USER + 0x20)

// USER START (Optionally insert additional defines)
#define ID_TEXT_First ID_TEXT_0
#define ID_TEXT_Num (ID_TEXT_27 - ID_TEXT_0 + 1)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "S2_Switch_Job_20250305", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job1", ID_TEXT_0, 10, 5, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job2", ID_TEXT_1, 10, 31, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job3", ID_TEXT_2, 10, 57, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job4", ID_TEXT_3, 10, 83, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job5", ID_TEXT_4, 10, 109, 25, 25, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text_Job6", ID_TEXT_5, 10, 135, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job7", ID_TEXT_6, 10, 161, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job8", ID_TEXT_7, 70, 5, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job9", ID_TEXT_8, 70, 31, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job10", ID_TEXT_9, 70, 57, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job11", ID_TEXT_10, 70, 83, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job12", ID_TEXT_11, 70, 109, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job13", ID_TEXT_12, 70, 135, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job14", ID_TEXT_13, 70, 161, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job15", ID_TEXT_14, 130, 5, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job16", ID_TEXT_15, 130, 31, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job17", ID_TEXT_16, 130, 57, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job18", ID_TEXT_17, 130, 83, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job19", ID_TEXT_18, 130, 109, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job20", ID_TEXT_19, 130, 135, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job21", ID_TEXT_20, 130, 161, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job22", ID_TEXT_21, 190, 5, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job23", ID_TEXT_22, 190, 31, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job24", ID_TEXT_23, 190, 57, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job25", ID_TEXT_24, 190, 83, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job26", ID_TEXT_25, 190, 109, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job27", ID_TEXT_26, 190, 135, 25, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text_Job28", ID_TEXT_27, 190, 161, 25, 25, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button_01", ID_BUTTON_0, 0, 196, 76, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_02", ID_BUTTON_1, 77, 196, 76, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_03", ID_BUTTON_2, 154, 196, 76, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_04", ID_BUTTON_3, 143, 163, 80, 20, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  extern int X0, Y0; // Y0=???D?CY???A???????P???o?????m???????(?qLCD???_??Y=0)?A???s?Ã¤J???m??????(?q???D?C??_??Y=0)
  unsigned char for_i8b;
  unsigned int for_i16b;
  extern GUI_CONST_STORAGE GUI_FONT GUI_FontTitleChinese16;
  // main

  extern const char *Page_Big5;      //???
  extern const char *Barcode_Big5;   //???
  extern const char *Confirm_Big5;   //???
  extern const char *Page_Up_Big5;   //???
  extern const char *Page_Down_Big5; //???
  extern const char *Enter_Big5;     //???
  extern const char *Back_Big5;     //???
  extern const char *Select_Big5;   //???
  extern const char *Sequence_Big5; //???
  extern const char *Step_Big5;     //???
  ;                                 //????
  extern const char *Nm_Big5;       //????
  extern const char *Kgf_cm_Big5;   //????
  extern const char *In_lbs_Big5;   //????
  extern const char *cN_m_Big5;     //????
  extern const char *RPM_Big5;      //????
  extern const char *Switch_Job_Big5;
  extern const char *Job_ID_Big5;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'S2_1_Switch_Job_20250305'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, 0xffffff);
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Text_Job1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "1");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "2");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "3");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "4");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "5");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "6");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "7");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "8");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "9");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_10'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "10");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job11'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "11");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_12'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "12");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_13'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "13");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_14'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "14");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_15'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "15");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_16'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "16");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_17'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "17");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_18'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "18");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_19'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "19");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_20'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "20");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_21'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "21");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_22'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "22");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_23'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "23");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_24'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "24");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_25'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "25");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_26'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "26");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_27'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "27");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_28'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_27);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "28");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    // USER START (Optionally insert additional code for further widget initialization)
    Pg_Call_Job_0_array_init();
    for_i16b = ID_TEXT_First;
    for (for_i8b = 1; for_i8b <= ID_TEXT_Num; for_i8b++)
      hItems.TEXT[for_i8b] = WM_GetDialogItem(pMsg->hWin, for_i16b++);

    hItems.hWin = pMsg->hWin; // title
    hItems.BUTTON[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    hItems.BUTTON[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    hItems.BUTTON[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 	WM_HideWindow(hItem);				//?????Focus
    WM_SetFocus(hItem);             //??Focus
    WM_MoveChildTo(hItem, 240, 38); //???????????,?emWin GUIBuilder?????????

    //	hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);	//
    //	hItems.EDIT[2] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//
    ////hItems.EDIT[3] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.BUTTON[0]=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    // hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//
    // PROGBAR_SetFont(hItem, GUI_FONT_16_1);
    //
    //  Initialization of 'S2_Switch_Job_20250305'
    //

    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B);
    FRAMEWIN_SetText(hItem, Switch_Job_Big5);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF1010));
    //  FRAMEWIN_SetTextColor(hItem,GUI_WHITE);
    FRAMEWIN_SetTitleHeight(hItem, 16);
/*
    //
    // Initialization of 'Text_Job1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "1");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "2");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "3");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "4");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "5");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, &GUI_FontChinese22);
    TEXT_SetText(hItem, Job_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "6");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    */
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //       BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //   BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //   BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    //	  _aDialogCreate[1].x0=0;
    //		_aDialogCreate[1].y0=12;

    //	_aDialogCreate[2].x0=0;
    //	_aDialogCreate[2].y0=42;

    //_aDialogCreate[3].x0=0;
    //	_aDialogCreate[3].y0=72;

    //	_aDialogCreate[4].x0=0;
    //	_aDialogCreate[4].y0=102;

    //	_aDialogCreate[5].x0=0;
    //	_aDialogCreate[5].y0=132;

    //	_aDialogCreate[6].x0=0;
    //	_aDialogCreate[6].y0=162;

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button_01'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_02'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_03'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_04'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        FRAMEWIN_Display(ID_TEXT_Num);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateS2_1_Switch_Job_20250305
 */
WM_HWIN CreateS2_Switch_Job_BIG5(void);
WM_HWIN CreateS2_Switch_Job_BIG5(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 80);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
