
/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH                         *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.48                          *
 *        Compiled Jun 13 2018, 10:51:02                              *
 *        (c) 2018 Segger Microcontroller GmbH                        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "PTT_Global.h"
// #include "GUI.h"

// #include "DialogFunction.h"
// #include "stdio.h"			//for sprintf() Library
// #include "NuMicro.h"		//for PB14
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_EDIT_0 (GUI_ID_USER + 0x05)
#define ID_EDIT_1 (GUI_ID_USER + 0x06)
#define ID_EDIT_2 (GUI_ID_USER + 0x07)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x08)
#define ID_PROGBAR_1 (GUI_ID_USER + 0x09)
#define ID_TEXT_0 (GUI_ID_USER + 0x0A)
#define ID_TEXT_1 (GUI_ID_USER + 0x0B)
#define ID_TEXT_2 (GUI_ID_USER + 0x0C)
#define ID_TEXT_3 (GUI_ID_USER + 0x0D)
#define ID_TEXT_4 (GUI_ID_USER + 0x0E)
#define ID_TEXT_5 (GUI_ID_USER + 0x0F)
#define ID_TEXT_6 (GUI_ID_USER + 0x10)
#define ID_TEXT_7 (GUI_ID_USER + 0x11)
#define ID_TEXT_8 (GUI_ID_USER + 0x12)
#define ID_EDIT_3 (GUI_ID_USER + 0x13)
#define ID_TEXT_10 (GUI_ID_USER + 0x14)
#define ID_TEXT_9 (GUI_ID_USER + 0x15)
#define ID_TEXT_11 (GUI_ID_USER + 0x16)
#define ID_TEXT_12 (GUI_ID_USER + 0x17)
#define ID_TEXT_13 (GUI_ID_USER + 0x18)
#define ID_TEXT_14 (GUI_ID_USER + 0x19)
#define ID_TEXT_15 (GUI_ID_USER + 0x1A)
#define ID_TEXT_16 (GUI_ID_USER + 0x1B)
#define ID_TEXT_17 (GUI_ID_USER + 0x1C)
#define ID_TEXT_18 (GUI_ID_USER + 0x1D)
#define ID_TEXT_19 (GUI_ID_USER + 0x1E)

// USER START (Optionally insert additional defines)
extern uint8_t PROGBAR_Color_1T;

extern void Delay_us(uint32_t us);
extern void Pg_home_array_init(void);

// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// MTool_40x16_3.bmp I    ϥΤp e aRGB=211,211,211 C#define GUI_LIGHTGRAY     GUI_MAKE_COLOR(0x00D3D3D3)
// image     ܧ Ϥ      ܧ  ɦW A _ hGUIBuilder.exe u | O   ̥    J   i A  z C2022/02/07
// ϥ PNG   ɡABU     ɭԷ| X {IMAGE_SetPNG L w q A ϥ #include "IMAGE.h"			//for IMAGE_SetPNG() ] L
//   ŦA  M

// static int s_value;
// static char s_Buf[20];
// WM_KEY_INFO My_KEY;
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "Main_EN_", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button_01", ID_BUTTON_0, 0, 196, 72, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_02", ID_BUTTON_1, 77, 196, 72, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_03", ID_BUTTON_2, 154, 196, 72, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_04", ID_BUTTON_3, 149, 170, 80, 20, 0, 0x0, 0},
    {EDIT_CreateIndirect, "Edit_00_Line0", ID_EDIT_0, -5, 0, 240, 30, 0, 0x64, 0},  /*high+7 上 */
    {EDIT_CreateIndirect, "Edit_01_Line1", ID_EDIT_1, -6, 27, 240, 49, 0, 0x64, 0}, /*y+9 中h+5 */
    {EDIT_CreateIndirect, "Edit_02_Line2", ID_EDIT_2, -5, 170, 240, 24, 0, 0x64, 0},
    {PROGBAR_CreateIndirect, "Progbar_00_Batt", ID_PROGBAR_0, 194, 11, 30, 9, 0, 0x0, 0}, /*y+5 上 */
    {PROGBAR_CreateIndirect, "Progbar_01_Batt", ID_PROGBAR_1, 180, 8, 40, 15, 0, 0x0, 0}, /*y+5 上 */
    {TEXT_CreateIndirect, "Text_Job", ID_TEXT_0, 5, 34, 60, 20, 0, 0x64, 0},              /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Seq", ID_TEXT_1, 83, 34, 60, 20, 0, 0x64, 0},             /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Step", ID_TEXT_2, 160, 34, 60, 20, 0, 0x64, 0},           /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Counter", ID_TEXT_3, 1, 80, 80, 24, 0, 0x64, 0},          /*y+10 下 */
    {TEXT_CreateIndirect, "Text_Tourqe", ID_TEXT_4, 1, 103, 75, 24, 0, 0x64, 0},          /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Angle", ID_TEXT_5, 2, 126, 60, 24, 0, 0x64, 0},           /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Speed", ID_TEXT_6, 1, 149, 70, 24, 0, 0x64, 0},           /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Angle_Unit", ID_TEXT_7, 35, 123, 40, 16, 0, 0x64, 0},     /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Speed_Unit", ID_TEXT_8, 155, 152, 50, 16, 0, 0x64, 0},    /*y+10 下*/
    {EDIT_CreateIndirect, "Edit_BLE", ID_EDIT_3, 5, 7, 60, 16, 0, 0x0, 0},                /*y+5 上 */
    {TEXT_CreateIndirect, "Text", ID_TEXT_10, 116, 5, 20, 20, 0, 0x64, 0},                /*y+5 上 */
    {TEXT_CreateIndirect, "Text", ID_TEXT_9, 94, 5, 20, 20, 0, 0x64, 0},                 /*y+5 上 */
    {TEXT_CreateIndirect, "Text_Buzzer_C", ID_TEXT_11, 139, 5, 80, 20, 0, 0x64, 0},        /*y+5 上 */
    {TEXT_CreateIndirect, "Text_Job_C", ID_TEXT_12, 4, 56, 60, 20, 0, 0x64, 0},           /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Seq_C", ID_TEXT_13, 63, 56, 95, 20, 0, 0x64, 0},          /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Step_C", ID_TEXT_14, 160, 56, 60, 20, 0, 0x64, 0},        /*y+10 中 */
    {TEXT_CreateIndirect, "Text_Counter_C", ID_TEXT_15, 78, 80, 75, 24, 0, 0x64, 0},      /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Tourqe_Unit_C", ID_TEXT_16, 155, 80, 72, 16, 0, 0x64, 0}, /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Tourqe_C", ID_TEXT_17, 78, 103, 160, 24, 0, 0x64, 0},     /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Angle_C", ID_TEXT_18, 78, 126, 77, 24, 0, 0x64, 0},       /*y+10 下*/
    {TEXT_CreateIndirect, "Text_Speed_C", ID_TEXT_19, 78, 149, 75, 24, 0, 0x64, 0},       /*y+10 下*/
// USER START (Optionally insert additional widgets)
// ϼh   C      s W   ǡG"  ө~ W" C     s վ㶶 ǡA i N W  Defines P_aDialogCreate[]        m վ A
// A  GUIBuilder.exe   J(  OPEN   J A A R   ª FRAMEWIN) A L յL    n    Ĳ o   ק í  s ^ s A p   n  | ۰ʽs  Defines   ǡC

#define ID_Text_Speed_Unit ID_TEXT_8 // Text_Angle_Unit   ʺA
#define ID_TEXT_First ID_TEXT_10
#define ID_TEXT_Num (ID_TEXT_19 - ID_TEXT_10 + 1)

    // FRAMEWIN  عw ]10 A   D C e  32 r  +10=42
    //    { FRAMEWIN_CreateIndirect, "Setting", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x64, 0 },
    //    { HEADER_CreateIndirect, "Header_01", ID_HEADER_0, 0, 0, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_01", ID_TEXT_0, 0, 0, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_01", ID_EDIT_0, 110, 24, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_02", ID_HEADER_1, 0, 76, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_02", ID_TEXT_1, 0, 76, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_02", ID_EDIT_1, 110, 96, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_03", ID_HEADER_2, 0, 152, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_03", ID_TEXT_2, 0, 152, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_03", ID_EDIT_2, 110, 172, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_04", ID_HEADER_3, 0, 229, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_04", ID_TEXT_3, 0, 229, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_04", ID_EDIT_3, 110, 253, 120, 24, 0, 0x0, 0 },
    //  USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// z---------------------------------------------

// |---------------------------------------------
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  extern int X0, Y0; // Y0=¼ÐÃD¦CY°ª¡A­×¥¿²¾°Ê»P¨ú±oª«¥ó¦ì¸m¬°µ´¹ï­È(±qLCDÃäºâ°_¬°Y=0)¡A¦ý½s¿èª«¥ó¦ì¸m¬°¬Û¹ï­È(±q¼ÐÃD¦Cºâ°_¬°Y=0)
  extern const char *_Title1;
  extern const char *_Title12;
  extern const char *Data_Upload_Big5;
  extern const char *Data_Fulld_Big5;
  extern const char *Setting_Big5;
  extern const char *Page_Big5;      // 功能鍵
  extern const char *Barcode_Big5;   // 功能鍵
  extern const char *Confirm_Big5;   // 功能鍵
  extern const char *Page_Up_Big5;   // 功能鍵
  extern const char *Page_Down_Big5; // 功能鍵
  extern const char *Enter_Big5;     // 功能鍵
  extern const char *Back_Big5;      // 功能鍵
  extern const char *Select_Big5;    // 功能鍵
  extern const char *Sequence_Big5;  // 功能鍵
  extern const char *Step_Big5;      // 功能鍵
  extern const char *Mute_Big5;
  extern const char *Kgf_m_Big5;  // 扭力單位
  extern const char *Nm_Big5;     // 扭力單位
  extern const char *Kgf_cm_Big5; // 扭力單位
  extern const char *In_lbs_Big5; // 扭力單位
  extern const char *cN_m_Big5;   // 扭力單位
  extern const char *RPM_Big5;    // 扭力單位
  extern const char *Job_Big5;
  extern const char *Seq_Big5;
  extern const char *Step_Big5;
  extern const char *Counter_Big5;
  extern const char *Torque_Big5;
  extern const char *Angle_Big5;
  extern const char *Speed_Big5;
  extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_19B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Main_20241226'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_04");
    //
    // Initialization of 'Edit_02_Line2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFont(hItem, GUI_FONT_20B_1);
    EDIT_SetText(hItem, " ");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00005000));
    //
    // Initialization of 'Progbar_01_Batt'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
    PROGBAR_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Text_Job'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Seq'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Step'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Counter'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tourqe'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, "o");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Edit_BLE'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "APPLink");
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    //
    // Initialization of 'Text_Buzzer_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, "0");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Seq_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Step_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Counter_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tourqe_Unit_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tourqe_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
    ////////////////////////////////////////////
    Pg_home_array_init();
    hItem = pMsg->hWin;
    FRAMEWIN_SetActive(hItem, 1); // 1=Active，0=Inactive
    //	X0 = FRAMEWIN_GetBorderSize(hItem) + 4;		//邊寬2，3=實測偏移
    //	Y0 = FRAMEWIN_GetTitleHeight(hItem) + 3;	//標題列高34(使用GUI_FONT_32_1)
    // 	FRAMEWIN_SetTitleHeight(hItem, 32);			//標題高度
    // 	FRAMEWIN_SetBorderSize(hItem, 5);			//邊框(預設5)，需開啟自定義
    // 	FRAMEWIN_SetBarColor(hItem, 1, GUI_RED);	//標題列顏色。1=Active，0=Inactive。需開啟自定義
    // 	FRAMEWIN_SetFont(hItem, GUI_FONT_32_1);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLACK);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLUE);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF1010));	//定義使用0BGR，硬體使用AGBR
    // 	FRAMEWIN_SetClientColor(hItem, GUI_GREEN);	//內容區顏色
    // 	GUI_DrawHLine(200, 5 , 235);	//水平線

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 	WM_HideWindow(hItem);				//隱藏就沒有Focus
    WM_SetFocus(hItem);             // 設定Focus
    WM_MoveChildTo(hItem, 240, 38); // 手動移位置到視窗外隱藏，讓emWin GUIBuilder編輯能看到方便移動

    for_i16b = ID_TEXT_First;
    for (for_i8b = 1; for_i8b <= ID_TEXT_Num; for_i8b++)
      hItems.TEXT[for_i8b] = WM_GetDialogItem(pMsg->hWin, for_i16b++);
    // hItems.TEXT[29] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);

    hItems.hWin = pMsg->hWin;
    hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3); // Text_Angle_Unit單位動態移動
    EDIT_SetBkColor(hItems.EDIT[0], EDIT_CI_ENABLED, GUI_WHITE);
    hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2); // Text_Angle_Unit單位動態移動
    hItems.PROGBAR[0] = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);

    hItems.BUTTON[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    hItems.BUTTON[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    hItems.BUTTON[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFocusable(hItem, 0); // ±Ò¥Î/Ãö³¬Tab Focus¡A0=Ãö³¬§YTab¤Á´«·|³Q¸õ¹L
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00FFE6BC));
    PROGBAR_Color_1T = 0xff;

    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B);

    // FRAMEWIN_SetText(hItem, Data_Upload_Big5[0]);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    FRAMEWIN_SetTitleHeight(hItem, 16);
    if (Pg_Home.Title == 0)
      FRAMEWIN_SetText(hItem, " ");
    else if (Pg_Home.Title == 1)
    {
      FRAMEWIN_SetText(hItem, Data_Fulld_Big5);
    }
    else if (Pg_Home.Title == 2)
    {
      FRAMEWIN_SetText(hItem, Setting_Big5);
    }
    else if (Pg_Home.Title == 3)
    {
      FRAMEWIN_SetText(hItem, Data_Upload_Big5);
    }
    else
    {
    }
    // Delay_us(delayCount);
    ///////////////////////////////////

    //
    // Initialization of 'Button_01' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    BUTTON_SetText(hItem, " ");
    //	Delay_us(delayCount);
    //
    // Initialization of 'Button_02' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_04");
    //
    // Initialization of 'Edit_02_Line2' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_19B);
    EDIT_SetText(hItem, " ");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00005000));
    //
    // Initialization of 'Progbar_01_Batt' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
    PROGBAR_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Text_Job' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Job_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Seq'ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Seq_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Step' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Step_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Counter' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Counter_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tourqe' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Torque_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Angle_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B);
    TEXT_SetText(hItem, Speed_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, "o");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_Unit' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_19B);
    TEXT_SetText(hItem, RPM_Big5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Edit_BLE' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "APPLink");
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Buzzer_C' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_19B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Job_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Seq_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Step_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Counter_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tourqe_Unit_C' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_19B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));

    //
    // Initialization of 'Text_Tourqe_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Angle_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button_01'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_02'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_03'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_04'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        FRAMEWIN_Display(ID_TEXT_Num);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit_00_Line0'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit_01_Line1'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit_02_Line2'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit_BLE'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        // EDIT_SetText(hItem, "CLICKED");
        //  USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        //	EDIT_SetText(hItem, "RELEASED");
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        //	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        // 		EDIT_SetText(hItem, "VAL_CHANGED");
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // z---------------------------------------------
        // NCode = pMsg->Data.v;		//NCode i Ѧ WM.h  Notification codes w q
      case WM_NOTIFICATION_GOT_FOCUS:
        // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_0, WM_NOTIFICATION_GOT_FOCUS);
        break;
      case WM_NOTIFICATION_LOST_FOCUS:
        // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_0, WM_NOTIFICATION_LOST_FOCUS);
        break;

      default:
        //   sprintf(s_Buf, "%d", NCode);
        //	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
        //	EDIT_SetText(hItem, s_Buf);
        break;
        // |---------------------------------------------
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
    // USER START (Optionally insert additional message handling)
    // z---------------------------------------------
    // Focus bBUTTON    ɡA |Ĳ oWM_KEY    KEY G W U   k(1  )+ESC  (2  ) AEnterĲ oWM_NOTIFY_PARENT  WM_NOTIFICATION_CLICKED
    /* case WM_KEY:
       Id    = WM_GetId(pMsg->hWinSrc);
       NCode = pMsg->Data.v;
     hItem = WM_GetFocusedWindow();
     My_KEY.Key = (((WM_KEY_INFO*)(pMsg->Data.p))->Key);
     My_KEY.PressedCnt = (((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt);

     if(My_KEY.Key == GUI_KEY_UP)
     {
   // 		if(Main_Page_Item <= 1)
   // 			Main_Page_Item = 4;
   // 		else
   // 			Main_Page_Item -= 1;

       Main_Page_Item += 10;

       Main_Page_Item_Chg_F = 1;
     }
     else if(My_KEY.Key == GUI_KEY_DOWN)
     {
   // 		if(Main_Page_Item == 4)
   // 			Main_Page_Item = 1;
   // 		else
   // 			Main_Page_Item += 1;

       Main_Page_Item += 1;

       Main_Page_Item_Chg_F = 1;
     }
   */
    // 	if(Main_Page_Item_Chg_F == 1)
    // 	{
    // 		Main_Page_Item_Chg_F = 0;
    //
    // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_0, WM_NOTIFICATION_LOST_FOCUS);
    // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_1, WM_NOTIFICATION_LOST_FOCUS);
    // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_2, WM_NOTIFICATION_LOST_FOCUS);
    // 		EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_3, WM_NOTIFICATION_LOST_FOCUS);
    // 		if(Main_Page_Item == 1)
    // 			EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_0, WM_NOTIFICATION_GOT_FOCUS);
    // 		else if(Main_Page_Item == 2)
    // 			EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_1, WM_NOTIFICATION_GOT_FOCUS);
    // 		else if(Main_Page_Item == 3)
    // 			EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_2, WM_NOTIFICATION_GOT_FOCUS);
    // 		else if(Main_Page_Item == 4)
    // 			EDIT_Set_Bk_Text_Color(pMsg->hWin, ID_EDIT_3, WM_NOTIFICATION_GOT_FOCUS);
    // 	}
    break;
    // |---------------------------------------------
    // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateMain_20241226
 */
WM_HWIN CreateMain_BIG5(void);
WM_HWIN CreateMain_BIG5(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 80);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
