/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH                         *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.48                          *
 *        Compiled Jun 13 2018, 10:51:02                              *
 *        (c) 2018 Segger Microcontroller GmbH                        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_2 (GUI_ID_USER + 0x02)
#define ID_TEXT_3 (GUI_ID_USER + 0x03)
#define ID_TEXT_4 (GUI_ID_USER + 0x04)
#define ID_TEXT_5 (GUI_ID_USER + 0x05)
#define ID_TEXT_6 (GUI_ID_USER + 0x06)
#define ID_TEXT_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_15 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0a)
#define ID_TEXT_10 (GUI_ID_USER + 0x0b)
#define ID_TEXT_11 (GUI_ID_USER + 0x0c)
#define ID_TEXT_8 (GUI_ID_USER + 0x0d)
#define ID_TEXT_12 (GUI_ID_USER + 0x0e)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0f)
#define ID_BUTTON_1 (GUI_ID_USER + 0x10)
#define ID_BUTTON_2 (GUI_ID_USER + 0x11)
#define ID_BUTTON_3 (GUI_ID_USER + 0x12)
#define ID_TEXT_13 (GUI_ID_USER + 0x13)
#define ID_TEXT_14 (GUI_ID_USER + 0x14)

// USER START (Optionally insert additional defines)
#include "PTT_Global.h"
extern void Pg_JS_2_Step2_1_array_init(void);
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "S3_1A_Step1_1", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Step_ID", ID_TEXT_0, 0, 0, 100, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Direction", ID_TEXT_2, 0, 50, 100, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Speed", ID_TEXT_3, 0, 75, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Joint_Offset", ID_TEXT_4, 0, 100, 92, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Delay_Time", ID_TEXT_5, 0, 125, 92, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Step_ID_C", ID_TEXT_6, 104, 0, 41, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Tar_Ang", ID_TEXT_1, 0, 25, 104, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Tar_Ang_C", ID_TEXT_7, 104, 25, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Ang_Unit", ID_TEXT_15, 158, 31, 80, 16, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Direction_C", ID_TEXT_9, 104, 50, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Speed_C", ID_TEXT_10, 104, 74, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Joint_Offset_C", ID_TEXT_11, 104, 100, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Tor_Unit_C", ID_TEXT_8, 158, 105, 80, 16, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Delay_time_C", ID_TEXT_12, 104, 125, 80, 25, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button_01", ID_BUTTON_0, 0, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_02", ID_BUTTON_1, 77, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_03", ID_BUTTON_2, 154, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_04", ID_BUTTON_3, 143, 163, 80, 20, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Text_Speed_Unit", ID_TEXT_13, 158, 80, 54, 16, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Delay_Time_Unit", ID_TEXT_14, 158, 128, 44, 16, 0, 0x64, 0},
// USER START (Optionally insert additional widgets)
#define ID_TEXT_First ID_TEXT_6
#define ID_TEXT_Num (ID_TEXT_12 - ID_TEXT_6 + 1)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  extern int X0, Y0; // Y0=���D�CY���A�ץ����ʻP���o�����m�������(�qLCD���_��Y=0)�A���s�誫���m���۹��(�q���D�C��_��Y=0)
  unsigned char for_i8b;
  unsigned int for_i16b;
  extern const char *Page_Big5;      //???
  extern const char *Barcode_Big5;   //???
  extern const char *Confirm_Big5;   //???
  extern const char *Page_Up_Big5;   //???
  extern const char *Page_Down_Big5; //???
  extern const char *Enter_Big5;     //???
  extern const char *Back_Big5;      //???
  extern const char *Select_Big5;    //???
  extern const char *Sequence_Big5;  //???
  extern const char *Step_Big5;      //???
  extern const char *Next_Big5;
  extern const char *Back_Big5;
  extern const char *Step_Big5;
  extern const char *RPM_Big5; //????
  extern const char *Nm_Big5;  //????
  extern const char *Sec_Big5;
  extern const char *Degree_Big5;
  extern const char *Step_ID_Big5;
  extern const char *Target_Tor_Big5;
  extern const char *Direction_Big5;
  extern const char *Joint_Offset_Big5;
  extern const char *Delay_Time_Big5;
  extern const char *Speed_Big5;
  extern const char *CW_Big5;
  extern const char *CCW_Big5;
  extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'S3_1A_Step1_1'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, 0xffffff);
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Text_Step_ID'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tar_Ang'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Direction'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Joint_Offset'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Delay_Time'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Step_ID_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tar_Ang_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tor_Unit_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Direction_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Joint_Offset_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Delay_time_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    //
    // Initialization of 'Text_Speed_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Delay_Time_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Ang_Unit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
    Pg_JS_2_Step2_1_array_init();
    hItem = pMsg->hWin;
    FRAMEWIN_SetActive(hItem, 1); // 1=Active,0=Inactive

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);

    WM_SetFocus(hItem);             //??Focus
    WM_MoveChildTo(hItem, 240, 38); //???????????,?emWin GUIBuilder?????????

    for_i16b = ID_TEXT_First;
    for (for_i8b = 1; for_i8b <= ID_TEXT_Num; for_i8b++)
      hItems.TEXT[for_i8b] = WM_GetDialogItem(pMsg->hWin, for_i16b++);

    hItems.hWin = pMsg->hWin; // title
    hItems.BUTTON[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    hItems.BUTTON[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    hItems.BUTTON[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    //	hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);	//
    //	hItems.EDIT[2] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//
    ////hItems.EDIT[3] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.BUTTON[0]=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    // hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//

    // PROGBAR_SetFont(hItem, GUI_FONT_16_1);

    //
    // Initialization of 'S3_1A_Step1_1' ok
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF1010));
    //	FRAMEWIN_SetTextColor(hItem,GUI_WHITE);
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Text_Step_ID' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Step_ID_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tar_Ang' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Target_Tor_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Direction' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Direction_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Speed_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Joint_Offset' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Joint_Offset_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Delay_Time' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Delay_Time_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Step_ID_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tar_Ang_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tor_Unit_C' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //_aDialogCreate[8].x0=158; //166
    //_aDialogCreate[8].y0=105; //105
    //
    // Initialization of 'Text_Direction_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Speed_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Joint_Offset_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Delay_time_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    // BUTTON_SetSkinClassic(hItem);  // 這句是關鍵
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // 設定文字顏色為米白色
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // 未按下：白色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // 按下：黃色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // 停用：灰色
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //  BUTTON_SetSkinClassic(hItem);  // 這句是關鍵
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // 設定文字顏色為米白色
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // 未按下：白色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // 按下：黃色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // 停用：灰色
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //  BUTTON_SetSkinClassic(hItem);  // 這句是關鍵
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // 設定文字顏色為米白色
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // 未按下：白色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // 按下：黃色
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // 停用：灰色
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    //
    // Initialization of 'Text_Speed_Unit' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B);
    TEXT_SetText(hItem, RPM_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //	_aDialogCreate[19].x0=158; //166
    //_aDialogCreate[19].y0=80; //80
    //
    // Initialization of 'Text_Delay_Time_Unit' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B);
    TEXT_SetText(hItem, Sec_Big5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //	_aDialogCreate[20].x0=158; //166
    //_aDialogCreate[20].y0=128; //128
    //
    // Initialization of 'Text_Ang_Unit' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //	_aDialogCreate[7].x0=158; //166
    //	_aDialogCreate[7].y0=31; //31

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button_01'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_02'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_03'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_04'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        FRAMEWIN_Display(ID_TEXT_Num);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateS3_1A_Step1_1
 */
WM_HWIN CreateS3_1A_Step1_1_BIG5(void);
WM_HWIN CreateS3_1A_Step1_1_BIG5(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 80);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
