/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH                         *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.48                          *
 *        Compiled Jun 13 2018, 10:51:02                              *
 *        (c) 2018 Segger Microcontroller GmbH                        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "PTT_Global.h"
extern void Pg_JS_1_JobSEQ_array_init(void);
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_5 (GUI_ID_USER + 0x05)
#define ID_TEXT_4 (GUI_ID_USER + 0x06)
#define ID_TEXT_7 (GUI_ID_USER + 0x07)
#define ID_TEXT_9 (GUI_ID_USER + 0x08)
#define ID_TEXT_11 (GUI_ID_USER + 0x09)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0a)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0b)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0c)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0d)
#define ID_TEXT_6 (GUI_ID_USER + 0x0e)
#define ID_TEXT_8 (GUI_ID_USER + 0x0f)
#define ID_TEXT_10 (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "S3_1_Sequence", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Seq_Name", ID_TEXT_0, 0, 0, 93, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_TR", ID_TEXT_1, 0, 75, 140, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Select_Tool", ID_TEXT_2, 0, 25, 153, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Seq_Name_C", ID_TEXT_3, 94, 0, 137, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Select_Tool_C", ID_TEXT_5, 0, 50, 229, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_TR_C", ID_TEXT_4, 150, 75, 28, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_7, 150, 100, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_9, 150, 125, 80, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_11, 150, 150, 80, 25, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button_01", ID_BUTTON_0, 0, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_02", ID_BUTTON_1, 77, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_03", ID_BUTTON_2, 154, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_04", ID_BUTTON_3, 143, 173, 80, 20, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Text_N", ID_TEXT_6, 0, 100, 102, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_8, 1, 125, 150, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_10, 0, 150, 150, 25, 0, 0x64, 0},
// USER START (Optionally insert additional widgets)
#define ID_TEXT_First ID_TEXT_3
#define ID_TEXT_Num (ID_TEXT_11 - ID_TEXT_3 + 1)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'S3_1_Sequence'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, 0xffffff);
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Text_Seq_Name'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Seq. Name");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_TR'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Ti. Repeat ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Select_Tool'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Select Tool Name");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Seq_Name_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_TR_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Select_Tool_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    //
    // Initialization of 'Text_N'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Stop on NG");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Sequence OK");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "Stop Seq. on OK");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
    Pg_JS_1_JobSEQ_array_init();
    hItem = pMsg->hWin;
    FRAMEWIN_SetActive(hItem, 1); // 1=Active,0=Inactive
                                  //	X0 = FRAMEWIN_GetBorderSize(hItem) + 4;		//??2,3=????
    //	Y0 = FRAMEWIN_GetTitleHeight(hItem) + 3;	//????34(??GUI_FONT_32_1)
    // 	FRAMEWIN_SetTitleHeight(hItem, 32);			//????
    // 	FRAMEWIN_SetBorderSize(hItem, 5);			//??(??5),??????
    // 	FRAMEWIN_SetBarColor(hItem, 1, GUI_RED);	//??????1=Active,0=Inactive???????
    // 	FRAMEWIN_SetFont(hItem, GUI_FONT_32_1);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLACK);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLUE);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF1010));	//????0BGR,????AGBR
    // 	FRAMEWIN_SetClientColor(hItem, GUI_GREEN);	//?????
    // 	GUI_DrawHLine(200, 5 , 235);	//???

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 	WM_HideWindow(hItem);				//?????Focus
    WM_SetFocus(hItem);             //??Focus
    WM_MoveChildTo(hItem, 240, 38); //???????????,?emWin GUIBuilder?????????

    for_i16b = ID_TEXT_First;
    for (for_i8b = 1; for_i8b <= ID_TEXT_Num; for_i8b++)
      hItems.TEXT[for_i8b] = WM_GetDialogItem(pMsg->hWin, for_i16b++);

    hItems.hWin = pMsg->hWin; // title
    hItems.BUTTON[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    hItems.BUTTON[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    hItems.BUTTON[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    //	hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);	//
    //	hItems.EDIT[2] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//
    ////hItems.EDIT[3] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.BUTTON[0]=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);

    // hItems.EDIT[0] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
    //	hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//

    // PROGBAR_SetFont(hItem, GUI_FONT_16_1);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button_01'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_02'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_03'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_04'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        FRAMEWIN_Display(ID_TEXT_Num);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateS3_1_Sequence
 */
WM_HWIN CreateS3_1_Sequence_EN(void);
WM_HWIN CreateS3_1_Sequence_EN(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 80);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
