/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH                         *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.48                          *
 *        Compiled Jun 13 2018, 10:51:02                              *
 *        (c) 2018 Segger Microcontroller GmbH                        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "PTT_Global.h"
// #include "GUI.h"

// #include "DialogFunction.h"
// #include "stdio.h"			//for sprintf() Library
// #include "NuMicro.h"		//for PB14
extern void Pg_Tool_Mode_0_array_init(void);
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_2 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_TEXT_4 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0E)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// static int s_value;
// static char s_Buf[20];
// WM_KEY_INFO My_KEY;
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "S1_Tool_Mode_20241223", ID_FRAMEWIN_0, 0, 0, 240, 240, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Stand Alone", ID_TEXT_0, 0, 1, 120, 20, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Controlled", ID_TEXT_1, 0, 26, 120, 20, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_DF_Setting_Resets", ID_TEXT_2, 0, 53, 193, 20, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_Tool", ID_TEXT_3, 0, 82, 120, 20, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text_WIFI", ID_TEXT_4, 0, 106, 120, 20, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button_01", ID_BUTTON_0, 0, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_02", ID_BUTTON_1, 77, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_03", ID_BUTTON_2, 154, 196, 76, 20, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button_04", ID_BUTTON_3, 143, 163, 80, 20, 0, 0x0, 0},
// USER START (Optionally insert additional widgets)
//???????????:"????"????????,????Defines?_aDialogCreate[]???????,
//??GUIBuilder.exe??(?OPEN??,?????FRAMEWIN),??????????????????,?????????Defines???
#define ID_TEXT_First ID_TEXT_0
#define ID_TEXT_Num (ID_TEXT_4 - ID_TEXT_0 + 1)
    // FRAMEWIN????10,?????32??+10=42
    //    { FRAMEWIN_CreateIndirect, "Setting", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x64, 0 },
    //    { HEADER_CreateIndirect, "Header_01", ID_HEADER_0, 0, 0, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_01", ID_TEXT_0, 0, 0, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_01", ID_EDIT_0, 110, 24, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_02", ID_HEADER_1, 0, 76, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_02", ID_TEXT_1, 0, 76, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_02", ID_EDIT_1, 110, 96, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_03", ID_HEADER_2, 0, 152, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_03", ID_TEXT_2, 0, 152, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_03", ID_EDIT_2, 110, 172, 120, 24, 0, 0x0, 0 },
    //    { HEADER_CreateIndirect, "Header_04", ID_HEADER_3, 0, 229, 230, 50, 0, 0x0, 0 },
    //    { TEXT_CreateIndirect, "Text_04", ID_TEXT_3, 0, 229, 230, 24, 0, 0x64, 0 },
    //    { EDIT_CreateIndirect, "Edit_04", ID_EDIT_3, 110, 253, 120, 24, 0, 0x0, 0 },
    //  USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
//+---------------------------------------------

//+---------------------------------------------
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  extern int X0, Y0; // Y0=???D?CY???A???????P???o?????m???????(?qLCD???_??Y=0)?A???s?äJ???m??????(?q???D?C??_??Y=0)
  unsigned char for_i8b;
  unsigned int for_i16b;
  extern const char *Page_GB;      //???
  extern const char *Barcode_GB;   //???
  extern const char *Confirm_GB;   //???
  extern const char *Page_Up_GB;   //???
  extern const char *Page_Down_GB; //???
  extern const char *Enter_GB;     //???
  extern const char *Back_GB;      //???
  extern const char *Select_GB;    //???
  extern const char *Sequence_GB;  //???
  extern const char *Step_GB;      //???
  extern const char *Tool_Mode_GB; /// hh
  extern const char *Stand_Alone_GB;
  extern const char *Controlled_GB;
  extern const char *Tool_GB;
  extern const char *WIFI_GB;
  extern const char *Job_ID_GB;
  extern const char *Defaults_Setting_Resets_GB;
 	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B;
	extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'S1_Tool_Mode_20241223'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
    FRAMEWIN_SetText(hItem, " ");
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTextColor(hItem, 0xffffff);
    FRAMEWIN_SetTitleHeight(hItem, 16);
    //
    // Initialization of 'Text_Stand Alone'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Controlled'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_DF_Setting_Resets'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_Tool'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_WIFI'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_04'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Button_00");
    // USER START (Optionally insert additional code for further widget initialization)
    //+---------------------------------------------
    //?USER???????????,??GUIBuilder???????
    Pg_Tool_Mode_0_array_init();
    hItem = pMsg->hWin;
    FRAMEWIN_SetActive(hItem, 1); // 1=Active,0=Inactive
    //	X0 = FRAMEWIN_GetBorderSize(hItem) + 4;		//??2,3=????
    //	Y0 = FRAMEWIN_GetTitleHeight(hItem) + 3;	//????34(??GUI_FONT_32_1)
    // 	FRAMEWIN_SetTitleHeight(hItem, 32);			//????
    // 	FRAMEWIN_SetBorderSize(hItem, 5);			//??(??5),??????
    // 	FRAMEWIN_SetBarColor(hItem, 1, GUI_RED);	//??????1=Active,0=Inactive???????
    // 	FRAMEWIN_SetFont(hItem, GUI_FONT_32_1);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLACK);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_BLUE);
    // 	FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF1010));	//????0BGR,????AGBR
    // 	FRAMEWIN_SetClientColor(hItem, GUI_GREEN);	//?????
    // 	GUI_DrawHLine(200, 5 , 235);	//???

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 	WM_HideWindow(hItem);				//?????Focus
    WM_SetFocus(hItem);             //??Focus
    WM_MoveChildTo(hItem, 240, 38); //???????????,?emWin GUIBuilder?????????

    for_i16b = ID_TEXT_First;
    for (for_i8b = 1; for_i8b <= ID_TEXT_Num; for_i8b++)
      hItems.TEXT[for_i8b] = WM_GetDialogItem(pMsg->hWin, for_i16b++);

    hItems.hWin = pMsg->hWin; // title
    /*	hItems.EDIT = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);	//
      hItems.EDIT[1] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);	//
      hItems.EDIT[2] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);	//
      hItems.EDIT[3] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);	//
      hItems.EDIT[4] = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);	//
      */
    // hItems.BUTTON= WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);	//

    hItems.BUTTON[0] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    hItems.BUTTON[1] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    hItems.BUTTON[2] = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    //+---------------------------------------------

    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B);
    FRAMEWIN_SetText(hItem, Tool_Mode_GB);
    // FRAMEWIN_SetSkinClassic(hItem);  // ?????

    // FRAMEWIN_SetBarColor(hItem, 0, GUI_BLACK);
    // FRAMEWIN_SetBarColor(hItem, 1, GUI_BLACK);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // FRAMEWIN_SetTextColor(hItem, GUI_WHITE);
    FRAMEWIN_SetTitleHeight(hItem, 16);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Stand_Alone_GB);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Text_Controlled' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, Controlled_GB);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_DF_Setting_Resets' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));

    //
    // Initialization of 'Text_Tool' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text_WIFI' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B);
    TEXT_SetText(hItem, " ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Button_01' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    // BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_02' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    // BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");
    //
    // Initialization of 'Button_03' ok
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B);
    // BUTTON_SetSkinClassic(hItem);  // ?????
    // BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
    // BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);

    // ??????????
    // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);

    //	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);   // ???:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED,    GUI_WHITE);  // ??:??
    //	BUTTON_SetTextColor(hItem, BUTTON_CI_DISABLED,   GUI_WHITE);    // ??:??
    BUTTON_SetText(hItem, " ");

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button_01'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_02'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button_03'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button_04'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        FRAMEWIN_Display(ID_TEXT_Num);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateS1_Tool_Mode_20241223
 */
WM_HWIN CreateS1_Tool_Mode_GB(void);
WM_HWIN CreateS1_Tool_Mode_GB(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 80);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
