/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Language_Microsoft JhengHei_22B.c             *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260115-修正語言頁字庫當機問題-a3b0\01-20250105-字庫檔案\最後\Font_Pg_Language_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0045[ 13] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXX_,
  _XXXXXXX,
  _X____XX,
  ______XX,
  _XXXXXXX,
  XXX___XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0067[ 26] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _X____XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0068[ 28] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX__XXX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XXXXXX__,
  XX___X__,
  XXXX____,
  _XXXX___,
  ____XX__,
  X___XX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_4E2D[ 30] = { /* code 4E2D */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XX____X_,____X___,
  XX____X_,____X___,
  XX____X_,____X___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_4F53[ 32] = { /* code 4F53 */
  ___XX___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  __XXXXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  _XX_____,XXX_____,
  XXX____X,XXXX____,
  XXX___XX,_X_X____,
  __X___XX,_X_XX___,
  __X__XX_,_X__XX__,
  __X_XX__,_X___XX_,
  __X_X_XX,XXXXX_X_,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_6587[ 32] = { /* code 6587 */
  _____XX_,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____X___,__XX____,
  ___XX___,__XX____,
  ____XX__,_XX_____,
  ____XX__,_XX_____,
  _____XX_,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,XXX_____,
  __XXXX__,_XXXX___,
  XXXXX___,___XXXX_,
  _X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_7B80[ 30] = { /* code 7B80 */
  ___X____,_XX_____,
  __XXXXX_,_XXXXXX_,
  _XXXXXX_,XXXXXXX_,
  _X__XX_X,X__XX___,
  XXX___XX,XXXXXX__,
  __XX____,_____X__,
  ___X____,_____X__,
  _X__XXXX,XXX__X__,
  _X__XX__,__X__X__,
  _X__XXXX,XXX__X__,
  _X__XX__,__X__X__,
  _X__XX__,__X__X__,
  _X__XXXX,XXX__X__,
  _X______,___XXX__,
  _X______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_7E41[ 32] = { /* code 7E41 */
  __XX____,________,
  XXXXXXXX,__X_____,
  __X_X_X_,_XXXXXX_,
  XXXXXXXX,X___XX__,
  _XX_X_X_,_XX_X___,
  _XXXX_X_,__XXX___,
  _XXXXXXX,__XXX___,
  ______X_,XX___XX_,
  _____XXX,X_XX____,
  _____XXX,_XX_____,
  __XXXXXX,X__XX___,
  ____XXX_,___XXX__,
  _XXXXXXX,XXX__X__,
  ____X__X,__XX____,
  __XX___X,___XXX__,
  _X___XXX,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_9AD4[ 30] = { /* code 9AD4 */
  _XXXXX__,_XXXX___,
  _X___X_X,XXXXXXX_,
  _X_XXX_X,_XXXXXX_,
  _X_X_X_X,XXXXXXX_,
  XXXXXXXX,_XXXXXX_,
  XX___XXX,XXXXXXX_,
  XXXXXXX_,________,
  _X__XX_X,XXXXXXX_,
  _XXXXX__,________,
  _X__XX_X,XXXXXX__,
  _X_XXX_X,X____X__,
  _XXXXX_X,XXXXXX__,
  _XX_XX__,XX__X___,
  XX_XXX__,_X__X___,
  X__XX_XX,XXXXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[25] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,   9,   1,   8,   9, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  14,   0,   3,   6, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   5, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   2,  14,   1,   3,   5, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,   9,   1,   8,  16, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   5,   9,   1,   8,   7, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   8, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  12,   0,   5,   7, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_4E2D } /* code 4E2D */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_4F53 } /* code 4F53 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_6587 } /* code 6587 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_7B80 } /* code 7B80 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_7E41 } /* code 7E41 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_9AD4 } /* code 9AD4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop13 = {
   0x9AD4 /* first character */
  ,0x9AD4 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 24] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop12 = {
   0x7E41 /* first character */
  ,0x7E41 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop11 = {
   0x7B80 /* first character */
  ,0x7B80 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop10 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop9 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop8 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop7 = {
   0x0072 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop6 = {
   0x006C /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop5 = {
   0x0063 /* first character */
  ,0x0069 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop4 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop3 = {
   0x0054 /* first character */
  ,0x0054 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop2 = {
   0x0045 /* first character */
  ,0x0045 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Language_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

