/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_ALLPage_Button_Microsoft JhengHei_16B.c          *
* Font:        微軟正黑體                                            *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260115-修正語言頁字庫當機問題-a3b0\01-20250105-字庫檔案\最後\Font_ALLPage_Button_Microsoft JhengHei_16B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0021[  9] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0022[  3] = { /* code 0022, QUOTATION MARK */
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0023[  8] = { /* code 0023, NUMBER SIGN */
  ___X__X_,
  __X___X_,
  XXXXXXXX,
  __X___X_,
  __X__X__,
  XXXXXXXX,
  _X___X__,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0024[ 10] = { /* code 0024, DOLLAR SIGN */
  _XXX____,
  X_X_X___,
  X_X_____,
  X_X_____,
  _XX_____,
  __XXX___,
  __X_X___,
  X_X_X___,
  _XXX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0025[ 18] = { /* code 0025, PERCENT SIGN */
  _XX_____,X_______,
  X__X___X,________,
  X__X__X_,________,
  X__X_X__,________,
  _XX_XX_X,X_______,
  ____X_X_,_X______,
  ___X__X_,_X______,
  __X___X_,_X______,
  _X_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0026[ 18] = { /* code 0026, AMPERSAND */
  __XXX___,________,
  _X___X__,________,
  _X___X__,X_______,
  __XXX___,X_______,
  _XXXX___,X_______,
  X____X_X,________,
  X_____XX,________,
  X____XXX,________,
  _XXXX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0027[  3] = { /* code 0027, APOSTROPHE */
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0028[ 11] = { /* code 0028, LEFT PARENTHESIS */
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0029[ 11] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002A[  4] = { /* code 002A, ASTERISK */
  __X_____,
  XXXXXX__,
  __XX____,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002B[  6] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002C[  3] = { /* code 002C, COMMA */
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002F[ 11] = { /* code 002F, SOLIDUS */
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0030[  9] = { /* code 0030, DIGIT ZERO */
  _XXX____,
  _X_XX___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XX_X____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0031[  9] = { /* code 0031, DIGIT ONE */
  _XX_____,
  X_X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0032[  9] = { /* code 0032, DIGIT TWO */
  _XXX____,
  X___X___,
  ____X___,
  ____X___,
  ___XX___,
  __XX____,
  _XX_____,
  _X______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0033[  9] = { /* code 0033, DIGIT THREE */
  _XXX____,
  X___X___,
  ____X___,
  ____X___,
  _XXX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0034[  9] = { /* code 0034, DIGIT FOUR */
  ____X___,
  ___XX___,
  __X_X___,
  __X_X___,
  _X__X___,
  XX__X___,
  XXXXXX__,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0035[  9] = { /* code 0035, DIGIT FIVE */
  XXXXX___,
  X_______,
  X_______,
  XXXX____,
  ___XX___,
  ____X___,
  ____X___,
  X__XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0036[  9] = { /* code 0036, DIGIT SIX */
  _XXX____,
  _X______,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XX__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0037[  9] = { /* code 0037, DIGIT SEVEN */
  XXXXX___,
  ___XX___,
  ___X____,
  __XX____,
  __X_____,
  __X_____,
  _XX_____,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0038[  9] = { /* code 0038, DIGIT EIGHT */
  _XXX____,
  X___X___,
  X___X___,
  X__X____,
  _XXX____,
  XX_XX___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0039[  9] = { /* code 0039, DIGIT NINE */
  _XXX____,
  X__XX___,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  ___X____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003A[  7] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003B[  9] = { /* code 003B, SEMICOLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  _X______,
  XX______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003C[  6] = { /* code 003C, LESS-THAN SIGN */
  _____X__,
  ___XX___,
  _XX_____,
  X_______,
  _XXX____,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXX__,
  ________,
  ________,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003E[  6] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _XX_____,
  ___XX___,
  _____X__,
  __XXX___,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003F[  9] = { /* code 003F, QUESTION MARK */
  _XX_____,
  X__X____,
  ___X____,
  __XX____,
  _XX_____,
  _X______,
  ________,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0040[ 20] = { /* code 0040, COMMERCIAL AT */
  ___XXXXX,________,
  _XX____X,X_______,
  _X_XXXX_,XX______,
  X_XX__X_,_X______,
  X_X___X_,_X______,
  X_X___X_,_X______,
  X_X__XX_,XX______,
  _X_XX_XX,X_______,
  _XX____X,________,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0041[ 18] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XX__,________,
  ___XXXX_,________,
  ___X_XX_,________,
  __XX__X_,________,
  __XX__XX,________,
  _XXXXXXX,________,
  _X_____X,________,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0042[  9] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0043[  9] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0044[  9] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  X____X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X____XX_,
  X___XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0045[  9] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0046[  9] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXX___,
  X_______,
  X_______,
  X_______,
  XXXXX___,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0047[  9] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXX__,
  _XX___X_,
  XX______,
  X_______,
  X___XXX_,
  X_____X_,
  X_____X_,
  _X____X_,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0048[  9] = { /* code 0048, LATIN CAPITAL LETTER H */
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  XXXXXXX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0049[  9] = { /* code 0049, LATIN CAPITAL LETTER I */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004A[  9] = { /* code 004A, LATIN CAPITAL LETTER J */
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004B[  9] = { /* code 004B, LATIN CAPITAL LETTER K */
  X____XX_,
  X___XX__,
  X__XX___,
  X_XX____,
  XXX_____,
  X__X____,
  X___X___,
  X____XX_,
  X_____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004C[  9] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004D[ 18] = { /* code 004D, LATIN CAPITAL LETTER M */
  XX______,X_______,
  XXX____X,X_______,
  XXX____X,X_______,
  X_X___XX,X_______,
  X_XX__X_,X_______,
  X__X_XX_,X_______,
  X__X_X__,X_______,
  X__XXX__,X_______,
  X___X___,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004E[  9] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX____X_,
  XXX___X_,
  XXX___X_,
  X_XX__X_,
  X__XX_X_,
  X__XX_X_,
  X___XXX_,
  X____XX_,
  X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004F[  9] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0050[  9] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXX___,
  X___XX__,
  X____X__,
  X____X__,
  X___XX__,
  XXXX____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0051[ 11] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__,
  ____XX__,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0052[  9] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  XXXX____,
  X__X____,
  X__XX___,
  X___X___,
  X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0053[  9] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXX____,
  X___X___,
  X_______,
  XX______,
  _XX_____,
  __XXX___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0054[  9] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0055[  9] = { /* code 0055, LATIN CAPITAL LETTER U */
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0056[  9] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX_____X,
  XX_____X,
  _X____X_,
  _XX___X_,
  _XX__XX_,
  __X__X__,
  __XX_X__,
  __XXXX__,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0057[ 18] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX____X_,___X____,
  XX____X_,___X____,
  _X___XXX,___X____,
  _XX__XXX,__X_____,
  _XX__X_X,__X_____,
  __X__X_X,__X_____,
  __XXX__X,XXX_____,
  __XXX___,XX______,
  ___XX___,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0058[  9] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX____XX,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  ___XX___,
  __XXXX__,
  __X__X__,
  _XX__XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0059[  9] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX___XX_,
  _X___X__,
  _XX_XX__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005A[  9] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,
  ______X_,
  _____X__,
  ____XX__,
  ___XX___,
  __XX____,
  __X_____,
  _X______,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005B[ 11] = { /* code 005B, LEFT SQUARE BRACKET */
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005C[ 11] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005D[ 11] = { /* code 005D, RIGHT SQUARE BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005E[  5] = { /* code 005E, CIRCUMFLEX ACCENT */
  ___X____,
  __X_X___,
  _X___X__,
  _X___X__,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005F[  1] = { /* code 005F, LOW LINE */
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0060[  2] = { /* code 0060, GRAVE ACCENT */
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXX____,
  ____X___,
  ____X___,
  _XXXX___,
  X___X___,
  X__XX___,
  _XX_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0062[ 10] = { /* code 0062, LATIN SMALL LETTER B */
  X_______,
  X_______,
  X_______,
  X_XXX___,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  __XXX___,
  _X__X___,
  X_______,
  X_______,
  X_______,
  XX__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0064[ 10] = { /* code 0064, LATIN SMALL LETTER D */
  _____X__,
  _____X__,
  _____X__,
  _XXX_X__,
  _X__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXX____,
  XX__X___,
  X___X___,
  XXXXX___,
  X_______,
  XX__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0066[ 10] = { /* code 0066, LATIN SMALL LETTER F */
  __XX____,
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0067[ 10] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__,
  _____X__,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0068[ 10] = { /* code 0068, LATIN SMALL LETTER H */
  X_______,
  X_______,
  X_______,
  X_XXX___,
  XX___X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0069[ 10] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006A[ 13] = { /* code 006A, LATIN SMALL LETTER J */
  __XX____,
  __XX____,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006B[ 10] = { /* code 006B, LATIN SMALL LETTER K */
  X_______,
  X_______,
  X_______,
  X___XX__,
  X__X____,
  X_X_____,
  XX______,
  X_X_____,
  X__XX___,
  X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006C[ 10] = { /* code 006C, LATIN SMALL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006D[ 14] = { /* code 006D, LATIN SMALL LETTER M */
  X_XX_XXX,________,
  XX__XX__,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006E[  7] = { /* code 006E, LATIN SMALL LETTER N */
  X_XXX___,
  XX___X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0070[ 10] = { /* code 0070, LATIN SMALL LETTER P */
  X_XXX___,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  XXXXX___,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0071[ 10] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXX_X__,
  XX__XX__,
  X____X__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXX_X__,
  _____X__,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_____,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXX____,
  X_______,
  XX______,
  _XXX____,
  ___X____,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0075[  7] = { /* code 0075, LATIN SMALL LETTER U */
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0076[  7] = { /* code 0076, LATIN SMALL LETTER V */
  XX____X_,
  XX____X_,
  _XX__X__,
  _XX__X__,
  __X_X___,
  __X_X___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0077[ 14] = { /* code 0077, LATIN SMALL LETTER W */
  X____X__,_X______,
  X___XXX_,_X______,
  _X__XXX_,X_______,
  _X_X__X_,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __X____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  XX__XX__,
  _XX_X___,
  _XXXX___,
  __XX____,
  _XXXX___,
  _X_XX___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0079[ 10] = { /* code 0079, LATIN SMALL LETTER Y */
  XX____X_,
  XX____X_,
  _XX__X__,
  _XX__X__,
  __X_X___,
  __XXX___,
  ___X____,
  ___X____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXX__,
  ____X___,
  ___XX___,
  __XX____,
  _XX_____,
  _X______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007B[ 11] = { /* code 007B, LEFT CURLY BRACKET */
  _XX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007C[ 13] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007D[ 11] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007E[  2] = { /* code 007E, TILDE */
  _XXX__X_,
  X__XXX__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E00[  2] = { /* code 4E00, <CJK Ideograph, First> */
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E0A[ 22] = { /* code 4E0A */
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____XXXX,XX______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E0B[ 22] = { /* code 4E0B */
  XXXXXXXX,XX______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____XXX_,________,
  ____X_XX,________,
  ____X___,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5165[ 22] = { /* code 5165 */
  ___XXX__,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ___XX_X_,________,
  ___X__X_,________,
  __XX___X,________,
  __X____X,X_______,
  _X______,XX______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5217[ 22] = { /* code 5217 */
  XXXXXX__,_X______,
  __X____X,_X______,
  _XX____X,_X______,
  _XXXXX_X,_X______,
  _X__X__X,_X______,
  XXX_X__X,_X______,
  X_XXX__X,_X______,
  ___XX__X,_X______,
  __XX___X,_X______,
  _XX_____,_X______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_529F[ 22] = { /* code 529F */
  ______X_,________,
  XXXX__X_,________,
  __X_XXXX,XX______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __XX_X__,_X______,
  _XX__X__,_X______,
  X___X___,_X______,
  ___X___X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_548C[ 22] = { /* code 548C */
  ___XX___,________,
  XXX___XX,XX______,
  __X___X_,_X______,
  XXXXX_X_,_X______,
  __XX__X_,_X______,
  __XX__X_,_X______,
  _XX_X_X_,_X______,
  X_X__XX_,_X______,
  X_X___X_,_X______,
  __X___XX,XX______,
  __X___X_,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_56DE[ 22] = { /* code 56DE */
  XXXXXXXX,XX______,
  X_______,_X______,
  X_______,_X______,
  X__XXXXX,_X______,
  X__X__XX,_X______,
  X__X__XX,_X______,
  X__XXXXX,_X______,
  X_______,_X______,
  X_______,_X______,
  XXXXXXXX,XX______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5DE5[ 20] = { /* code 5DE5 */
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5E8F[ 22] = { /* code 5E8F */
  _____X__,________,
  _XXXXXXX,XX______,
  _X______,________,
  _X_XXXXX,X_______,
  _X_____X,X_______,
  _X__X_XX,________,
  _X___XX_,________,
  _XXXXXXX,XX______,
  XX____X_,_X______,
  X_____X_,X_______,
  X___XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_62E9[ 22] = { /* code 62E9 */
  _X__XXXX,XX______,
  _X__XX__,X_______,
  XXX__XXX,________,
  _X___XXX,X_______,
  _X_XX_X_,XX______,
  _XX_XXXX,XX______,
  XX____X_,________,
  _X____X_,________,
  _X_XXXXX,XX______,
  _X____X_,________,
  XX____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_64C7[ 22] = { /* code 64C7 */
  _X_XXXXX,XX______,
  _X_X_X_X,_X______,
  XXXXXXXX,XX______,
  _X____X_,________,
  _X_XXXXX,XX______,
  _XX__X__,X_______,
  XX___X_X,X_______,
  _X_XXXXX,XX______,
  _X____X_,________,
  _X_XXXXX,XX______,
  XX____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6570[ 22] = { /* code 6570 */
  X_X_X__X,________,
  _XXXX_XX,________,
  XXXXXXXX,XX______,
  __X_X_X_,X_______,
  _XX_XX__,X_______,
  X_X_X_X_,X_______,
  XXXXXXX_,X_______,
  _X_X___X,________,
  _XXX___X,________,
  _XXXX_X_,X_______,
  X____X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6578[ 22] = { /* code 6578 */
  __X____X,________,
  XXXXXX_X,________,
  X_X__X_X,XX______,
  XXXXXXX_,_X______,
  X_X__XX_,XX______,
  XXXXXX_X,X_______,
  X_X__X_X,X_______,
  XXXXXX_X,X_______,
  _X_X___X,X_______,
  __XX___X,XX______,
  XX__XXX_,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6761[ 20] = { /* code 6761 */
  ___XX___,________,
  __XXXXXX,X_______,
  XXXX___X,________,
  ___XXXX_,________,
  ___XXXXX,________,
  XXX__X_X,XX______,
  XXXXXXXX,XX______,
  __XX_XXX,________,
  _XX__X__,XX______,
  X____X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_689D[ 22] = { /* code 689D */
  __X__X__,________,
  _X_X_XXX,XX______,
  _X_XXX__,X_______,
  XX_X__XX,________,
  XX_XXX__,XX______,
  XX_X__XX,________,
  _X_XXXXX,XX______,
  _X_X__XX,________,
  _X_X_XXX,X_______,
  _X__XXXX,XX______,
  _X__X_XX,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6B65[ 22] = { /* code 6B65 */
  _____X__,________,
  __X__XXX,X_______,
  __X__X__,________,
  __X__X__,________,
  XXXXXXXX,XX______,
  _____X__,________,
  __XX_X__,XX______,
  _XX__X__,X_______,
  X______X,________,
  _____XX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6E05[ 22] = { /* code 6E05 */
  X_____X_,________,
  _X_XXXXX,XX______,
  ______X_,________,
  X__XXXXX,XX______,
  _X____X_,________,
  ___XXXXX,XX______,
  ___X____,X_______,
  _X_XXXXX,X_______,
  _X_X____,X_______,
  XX_XXXXX,X_______,
  X_XX___X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_7801[ 22] = { /* code 7801 */
  XXXXXXXX,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X__XX__,X_______,
  XXX_X___,X_______,
  XXX_XXXX,XX______,
  _XX_____,_X______,
  _XX_XXXX,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  _X_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_786E[ 22] = { /* code 786E */
  XXXX__XX,X_______,
  _X___X__,X_______,
  _X__X__X,X_______,
  _X_X_XXX,XX______,
  XXXX_X_X,_X______,
  XX_X_XXX,XX______,
  _X_X_X_X,_X______,
  _X_X_XXX,XX______,
  _X_XXX__,_X______,
  _XXXX___,_X______,
  _X__X___,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_78BA[ 22] = { /* code 78BA */
  ______X_,________,
  XXXXXXXX,XX______,
  _X__X_X_,_X______,
  _X___X_X,________,
  _X__XXXX,XX______,
  XXXXXX_X,________,
  XX_X_XXX,XX______,
  _X_X_X_X,________,
  _X_X_XXX,XX______,
  _XXX_X_X,________,
  _X_X_XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_78BC[ 22] = { /* code 78BC */
  XXXXXXXX,XX______,
  _X__X__X,________,
  _X__XXXX,XX______,
  XX__X__X,________,
  XXXXXXXX,XX______,
  XX_XX__X,________,
  _X_XXXXX,XX______,
  _X_X____,_X______,
  _XXXXX_X,XX______,
  _X_XXX_X,_X______,
  ____X_X_,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_80FD[ 22] = { /* code 80FD */
  __X___X_,________,
  _X_X__XX,XX______,
  XXX_XXX_,________,
  ______X_,________,
  XXXXX_XX,XX______,
  X___X___,________,
  XXXXX_X_,________,
  X__XX_XX,XX______,
  XXX_X_X_,________,
  X___X_X_,_X______,
  X__XX_XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8A8D[ 22] = { /* code 8A8D */
  _X__XXXX,XX______,
  XXX___XX,_X______,
  ____XXX_,_X______,
  XXX__XX_,_X______,
  ____X__X,X_______,
  XXX___X_,________,
  _______X,________,
  XXX_XX__,XX______,
  X_X_XX__,_X______,
  XXXXXX__,XX______,
  X_X___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8BA4[ 22] = { /* code 8BA4 */
  XX____X_,________,
  _XX___X_,________,
  ______X_,________,
  XX____X_,________,
  _X____X_,________,
  _X____XX,________,
  _X___X_X,________,
  _X_X_X_X,________,
  _XX_X___,X_______,
  _X_XX___,XX______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8FD4[ 22] = { /* code 8FD4 */
  XX__XXXX,XX______,
  _XX_X___,________,
  ____XXXX,XX______,
  XXX_XX__,X_______,
  _X__X_X_,X_______,
  XX__X__X,X_______,
  XXXXX_XX,X_______,
  __XX_XX_,XX______,
  _X_XXX__,_X______,
  _XX_____,________,
  X__XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8FDB[ 22] = { /* code 8FDB */
  X____X_X,X_______,
  _X___X_X,X_______,
  __XXXXXX,XX______,
  _____X_X,X_______,
  XX___X_X,X_______,
  _X_XXXXX,XX______,
  _X__X__X,X_______,
  _X__X__X,X_______,
  _XXX___X,X_______,
  X_XX____,________,
  X___XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9009[ 20] = { /* code 9009 */
  X_______,________,
  _X__X_X_,________,
  __X_XXXX,XX______,
  XXXX__X_,________,
  _X_XXXXX,XX______,
  XX___X_X,________,
  XXX_XX_X,_X______,
  _XXXX__X,XX______,
  _XX_____,________,
  X_XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9032[ 22] = { /* code 9032 */
  XX___XX_,________,
  _X__X__X,________,
  ____XXXX,XX______,
  XXXXX__X,________,
  _X_XXXXX,XX______,
  XX__X__X,________,
  XXX_XXXX,XX______,
  __X_X__X,________,
  _X__XXXX,XX______,
  XXX_____,________,
  X__XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9078[ 22] = { /* code 9078 */
  X__XXX_X,XX______,
  _X_X_X_X,_X______,
  ___XXX_X,XX______,
  XX_X___X,________,
  _X_XXX_X,XX______,
  X___XX_X,________,
  XX_XXXXX,XX______,
  _X__XX_X,________,
  _X_XXXXX,XX______,
  XXX_XX__,_X______,
  X__XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9664[ 22] = { /* code 9664 */
  XXX___X_,________,
  X_X__X_X,________,
  X_X_X___,X_______,
  XX_XXXXX,XX______,
  X_X___X_,________,
  X_X_XXXX,XX______,
  X_X___X_,________,
  XXX_XXX_,X_______,
  X__XX_X_,_X______,
  X__X__X_,_X______,
  X____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9801[ 22] = { /* code 9801 */
  XXXXXXXX,XX______,
  ____X___,________,
  _XXXXXXX,X_______,
  _X______,X_______,
  _XXXXXXX,X_______,
  _X______,X_______,
  _XXXXXXX,X_______,
  _X______,X_______,
  _XXXXXXX,X_______,
  __XX__XX,________,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9846[ 22] = { /* code 9846 */
  XXXXXXXX,XX______,
  X_X_X__X,________,
  XXXXXXXX,XX______,
  X_X_XXX_,_X______,
  XXXXXXXX,XX______,
  __X__XX_,_X______,
  XXXXXXXX,XX______,
  __X__XX_,_X______,
  _XXX_XXX,XX______,
  X_X_X_X_,X_______,
  X_X__X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9875[ 22] = { /* code 9875 */
  XXXXXXXX,XX______,
  ____XX__,________,
  _XXXXXXX,X_______,
  _X__XX__,X_______,
  _X__XX__,X_______,
  _X__XX__,X_______,
  _X__X___,X_______,
  _X__X___,X_______,
  ___XX_X_,________,
  __XX_X_X,X_______,
  XX______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9897[ 22] = { /* code 9897 */
  XXXXXXXX,XX______,
  X_X_X__X,________,
  XXXXX_XX,XX______,
  X_X_X_X_,_X______,
  XXXXX_XX,_X______,
  __X___XX,_X______,
  XXXXX_XX,_X______,
  __XX__XX,_X______,
  _XX_X__X,X_______,
  X_X_X_X_,_X______,
  X_X__X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9A5F[ 22] = { /* code 9A5F */
  XXXXXXXX,XX______,
  X_X_X_XX,_X______,
  XXX_XXX_,XX______,
  X_X_X_X_,XX______,
  XXX_XXXX,_X______,
  X_X_____,XX______,
  XXXXXXXX,________,
  ___X_X_X,_X______,
  X_XX_X_X,X_______,
  XX_XXX_X,XX______,
  __XXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9AA4[ 20] = { /* code 9AA4 */
  XXX_XXXX,XX______,
  X_X_XXXX,_X______,
  X_X_X_X_,X_______,
  X_X_XXX_,XX______,
  X_X_XXXX,_X______,
  XXX_____,X_______,
  __X_XXXX,XX______,
  _XX_XXX_,X_______,
  X_X__XX_,XX______,
  _XX_X_X_,_X______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[132] = {
   {   1,   1,   0,  12,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0020 } /* code 0020, SPACE */
  ,{   2,   9,   1,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   3,   1,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0022 } /* code 0022, QUOTATION MARK */
  ,{   8,   8,   0,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0023 } /* code 0023, NUMBER SIGN */
  ,{   5,  10,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0024 } /* code 0024, DOLLAR SIGN */
  ,{  10,   9,   1,   3,  11, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0025 } /* code 0025, PERCENT SIGN */
  ,{  10,   9,   1,   3,  11, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0026 } /* code 0026, AMPERSAND */
  ,{   1,   3,   1,   3,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0027 } /* code 0027, APOSTROPHE */
  ,{   3,  11,   1,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  11,   0,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   6,   4,   0,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002A } /* code 002A, ASTERISK */
  ,{   7,   6,   1,   5,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002B } /* code 002B, PLUS SIGN */
  ,{   2,   3,   0,  11,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002C } /* code 002C, COMMA */
  ,{   3,   1,   1,   8,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  10,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002E } /* code 002E, FULL STOP */
  ,{   5,  11,   0,   3,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_002F } /* code 002F, SOLIDUS */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0031 } /* code 0031, DIGIT ONE */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0032 } /* code 0032, DIGIT TWO */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0033 } /* code 0033, DIGIT THREE */
  ,{   6,   9,   0,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0034 } /* code 0034, DIGIT FOUR */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0035 } /* code 0035, DIGIT FIVE */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0036 } /* code 0036, DIGIT SIX */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   7,   1,   5,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003A } /* code 003A, COLON */
  ,{   2,   9,   0,   5,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003B } /* code 003B, SEMICOLON */
  ,{   6,   6,   2,   5,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003C } /* code 003C, LESS-THAN SIGN */
  ,{   6,   4,   1,   6,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003D } /* code 003D, EQUALS SIGN */
  ,{   6,   6,   1,   5,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   4,   9,   1,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_003F } /* code 003F, QUESTION MARK */
  ,{  10,  10,   1,   3,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,   9,   0,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   5,   9,   1,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   6,   9,   1,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   7,   9,   1,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   5,   9,   1,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,   9,   1,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   7,   9,   1,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   1,   9,   1,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   3,   9,   1,   3,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,   9,   1,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   5,   9,   1,   3,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   9,   9,   1,   3,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   7,   9,   1,   3,  10, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   8,   9,   1,   3,  10, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   6,   9,   1,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   8,  11,   1,   3,  10, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   6,   9,   1,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   5,   9,   1,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   7,   9,   0,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   7,   9,   1,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   8,   9,   0,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  12,   9,   0,   3,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   8,   9,   0,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   7,   9,   0,   3,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,   9,   0,   3,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   2,  11,   1,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   5,  11,   0,   3,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   2,  11,   1,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   7,   5,   1,   3,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   5,   1,   0,  13,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_005F } /* code 005F, LOW LINE */
  ,{   4,   2,   0,   2,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0060 } /* code 0060, GRAVE ACCENT */
  ,{   5,   7,   1,   5,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   6,  10,   1,   2,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   5,   7,   1,   5,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   6,  10,   1,   2,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   5,   7,   1,   5,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   4,  10,   0,   2,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,  10,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   6,  10,   1,   2,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  10,   1,   2,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  13,  -1,   2,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   6,  10,   1,   2,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   1,  10,   1,   2,   3, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   9,   7,   1,   5,  11, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   6,   7,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   7,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   6,  10,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   6,  10,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   3,   7,   1,   5,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   7,   1,   5,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,   9,   0,   3,   5, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   6,   7,   1,   5,   8, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   7,   7,   0,   5,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  10,   7,   0,   5,  10, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   7,   0,   5,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   7,  10,   0,   5,   7, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   6,   7,   0,   5,   6, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  11,   1,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  13,   1,   2,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  11,   0,   3,   4, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   7,   2,   1,   7,   9, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_007E } /* code 007E, TILDE */
  ,{  10,   1,   1,   7,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E00 } /* code 4E00, <CJK Ideograph, First> */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E0A } /* code 4E0A */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_4E0B } /* code 4E0B */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5165 } /* code 5165 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5217 } /* code 5217 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_529F } /* code 529F */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_548C } /* code 548C */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_56DE } /* code 56DE */
  ,{  10,  10,   1,   3,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5DE5 } /* code 5DE5 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_5E8F } /* code 5E8F */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_62E9 } /* code 62E9 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_64C7 } /* code 64C7 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6570 } /* code 6570 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6578 } /* code 6578 */
  ,{  10,  10,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6761 } /* code 6761 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_689D } /* code 689D */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6B65 } /* code 6B65 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_6E05 } /* code 6E05 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_7801 } /* code 7801 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_786E } /* code 786E */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_78BA } /* code 78BA */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_78BC } /* code 78BC */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_80FD } /* code 80FD */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8A8D } /* code 8A8D */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8BA4 } /* code 8BA4 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8FD4 } /* code 8FD4 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_8FDB } /* code 8FDB */
  ,{  10,  10,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9009 } /* code 9009 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9032 } /* code 9032 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9078 } /* code 9078 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9664 } /* code 9664 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9801 } /* code 9801 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9846 } /* code 9846 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9875 } /* code 9875 */
  ,{  11,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9897 } /* code 9897 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9A5F } /* code 9A5F */
  ,{  10,  10,   1,   2,  12, acGUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_9AA4 } /* code 9AA4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop37 = {
   0x9AA4 /* first character */
  ,0x9AA4 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[131] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop36 = {
   0x9A5F /* first character */
  ,0x9A5F /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[130] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop35 = {
   0x9897 /* first character */
  ,0x9897 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[129] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop34 = {
   0x9875 /* first character */
  ,0x9875 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[128] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop33 = {
   0x9846 /* first character */
  ,0x9846 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[127] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop32 = {
   0x9801 /* first character */
  ,0x9801 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[126] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop31 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[125] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop30 = {
   0x9078 /* first character */
  ,0x9078 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[124] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop29 = {
   0x9032 /* first character */
  ,0x9032 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[123] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop28 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[122] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop27 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[121] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop26 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[120] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop25 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[119] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop24 = {
   0x8A8D /* first character */
  ,0x8A8D /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[118] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop23 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[117] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop22 = {
   0x78BC /* first character */
  ,0x78BC /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[116] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop21 = {
   0x78BA /* first character */
  ,0x78BA /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[115] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop20 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[114] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop19 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[113] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop18 = {
   0x6E05 /* first character */
  ,0x6E05 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[112] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop17 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[111] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop16 = {
   0x689D /* first character */
  ,0x689D /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[110] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop15 = {
   0x6761 /* first character */
  ,0x6761 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[109] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop14 = {
   0x6578 /* first character */
  ,0x6578 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[108] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop13 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[107] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop12 = {
   0x64C7 /* first character */
  ,0x64C7 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[106] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop11 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[105] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop10 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[104] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop9 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[103] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop8 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[102] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop7 = {
   0x548C /* first character */
  ,0x548C /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[101] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop6 = {
   0x529F /* first character */
  ,0x529F /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[100] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop5 = {
   0x5217 /* first character */
  ,0x5217 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop4 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop3 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop2 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_ALLPage_Button_MicrosoftJhengHei_16B_Prop1}
  ,12 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

