/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Home_Microsoft JhengHei_192B.c                *
* Font:        微軟正黑體                                            *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--字庫導入910a\20250707-字庫檔案\最後\Font_Pg_Home_Microsoft JhengHei_192B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_002F[ 13] = { /* code 002F, SOLIDUS */
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0030[ 11] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0031[ 11] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XX_XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0032[ 11] = { /* code 0032, DIGIT TWO */
  _XXXXX__,
  _X___XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  _X______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0033[ 11] = { /* code 0033, DIGIT THREE */
  XXXXX___,
  X___XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  _XXX____,
  ___XXX__,
  ____XX__,
  ____XX__,
  X__XXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0034[ 11] = { /* code 0034, DIGIT FOUR */
  ____XXX_,
  ____XXX_,
  ___XXXX_,
  __XX_XX_,
  __X__XX_,
  _XX__XX_,
  XX___XX_,
  XXXXXXXX,
  _____XX_,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0035[ 11] = { /* code 0035, DIGIT FIVE */
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  ___XXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  X__XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0036[ 11] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  _XX_____,
  _XX_____,
  XX______,
  XX_XXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0037[ 11] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,
  ______XX,
  _____XX_,
  _____XX_,
  _____X__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0038[ 11] = { /* code 0038, DIGIT EIGHT */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XXXXX__,
  XXX_XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0039[ 11] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXXXXX,
  ______XX,
  ______X_,
  _X___XX_,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0041[ 22] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___XX__X,X_______,
  __XXX__X,X_______,
  __XX____,XX______,
  _XXXXXXX,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0042[ 22] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXXX_,________,
  XX____XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0043[ 11] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXXX,
  __XX___X,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XXX___X,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0044[ 22] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0045[ 11] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0046[ 11] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0047[ 22] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXXX,X_______,
  __XX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX___XXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0048[ 22] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0049[ 11] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  XXX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004B[ 22] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX__X___,________,
  XX___X__,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004C[ 11] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004D[ 22] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_X_XX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004E[ 22] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,XX______,
  XXXX____,XX______,
  XXXX____,XX______,
  XX_XX___,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX___XX_,XX______,
  XX___XX_,XX______,
  XX____XX,XX______,
  XX_____X,XX______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004F[ 22] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXXX,________,
  __XX___X,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  __XX___X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0050[ 11] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XX___XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0051[ 28] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,________,
  __XX___X,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX___X,X_______,
  ___XXXXX,________,
  _____XX_,________,
  ______XX,________,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0052[ 22] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XX__XX__,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0053[ 11] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,
  _XX___X_,
  XX______,
  XX______,
  XXX_____,
  _XXXX___,
  ___XXX__,
  _____XX_,
  _____XX_,
  X____XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0054[ 11] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0055[ 22] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0056[ 22] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0057[ 22] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_____X,X_____XX,
  XX____XX,XX____XX,
  XX____XX,XX____XX,
  _XX___XX,XX___XX_,
  _XX__XX_,_XX__XX_,
  _XX__XX_,_XX__XX_,
  __X__XX_,_XX__X__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  ___XXX__,__XXX___,
  ___XX___,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0058[ 22] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,XX______,
  _XX____X,X_______,
  __X___XX,________,
  __XX_XX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ___XXXX_,________,
  __XX__X_,________,
  __XX___X,________,
  _XX____X,X_______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0059[ 22] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX_____X,X_______,
  _XX____X,X_______,
  _XX___XX,________,
  __XX__XX,________,
  __XXXXX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_005A[ 22] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,X_______,
  ______XX,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ___XXX__,________,
  ___XX___,________,
  __XX____,________,
  _XXX____,________,
  _XX_____,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0061[  8] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXX__,
  _X___XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0063[  8] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XX__X__,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX__X__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  __XXXXXX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0065[  8] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XX___XX,
  XX____XX,
  XXXXXXXX,
  XX______,
  XX______,
  _XX___X_,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  __XXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  _X___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  __XX____,
  __XX____,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  XX______,
  XX______,
  XX______,
  XX___XX_,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XXXX____,
  XX_XX___,
  XX___XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXX_X,XXX_____,
  XXX__XXX,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006E[  8] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0072[  8] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0073[  8] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XX___X__,
  XX______,
  _XXXX___,
  ___XXX__,
  ____XX__,
  X___XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0074[ 10] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0075[  8] = { /* code 0075, LATIN SMALL LETTER U */
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0076[  8] = { /* code 0076, LATIN SMALL LETTER V */
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  __XXXX__,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  XX___XX_,__XX____,
  XX__XXX_,__XX____,
  XX__XXXX,__XX____,
  _XX_XXXX,__X_____,
  _XXXX__X,_XX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XX____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0078[  8] = { /* code 0078, LATIN SMALL LETTER X */
  XX____XX,
  _XX__XX_,
  __X_XX__,
  ___XX___,
  ___XX___,
  __XX_X__,
  _XX__XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_007A[  8] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XXX____,
  _XX_____,
  XXXXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_CharInfo[65] = {
   {   1,   1,   0,  15,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0020 } /* code 0020, SPACE */
  ,{   2,   2,   1,  13,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_002E } /* code 002E, FULL STOP */
  ,{   7,  13,   0,   4,   7, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_002F } /* code 002F, SOLIDUS */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0030 } /* code 0030, DIGIT ZERO */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0032 } /* code 0032, DIGIT TWO */
  ,{   6,  11,   2,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  11,   0,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,  11,   2,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  11,   0,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0039 } /* code 0039, DIGIT NINE */
  ,{  11,  11,   0,   4,  11, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  11,   1,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   8,  11,   1,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   9,  11,   1,   4,  11, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  11,   1,   4,   5, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  12,   0,   4,   6, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  11,   1,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  11,   1,   4,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  11,  11,   1,   4,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  11,  14,   1,   4,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  11,   1,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  11,   1,   4,  11, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  10,  11,   0,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  16,  11,   0,   4,  16, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  11,   0,   4,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  11,   0,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  11,   0,   4,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   7,   8,   1,   7,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  12,   1,   3,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   8,   1,   7,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  12,   1,   3,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   8,   1,   7,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,  12,   1,   3,   5, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   7,  12,   1,   3,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  12,   1,   3,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  16,  -1,   3,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   8,  12,   1,   3,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  12,   1,   3,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  12,   8,   1,   7,  14, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   7,   8,   1,   7,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   8,   1,   7,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   8,   1,   7,   6, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   8,   1,   7,   7, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  10,   1,   5,   6, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   7,   8,   1,   7,   9, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,   8,   0,   7,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  12,   8,   0,   7,  12, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   8,   8,   0,   7,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,  12,   0,   7,   8, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   8,   0,   7,   7, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_007A } /* code 007A, LATIN SMALL LETTER Z */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop4 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_CharInfo[ 39] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop2 = {
   0x002E /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Home_MicrosoftJhengHei_192B_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

