/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Net_Info_Microsoft JhengHei_19B.c             *
* Font:        微軟正黑體                                            *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_Net_Info_Microsoft JhengHei_19B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0021[ 11] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0022[  4] = { /* code 0022, QUOTATION MARK */
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0023[ 20] = { /* code 0023, NUMBER SIGN */
  ____X__X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,X_______,
  ___X___X,________,
  __X___X_,________,
  XXXXXXXX,X_______,
  __X___X_,________,
  _X___X__,________,
  _X___X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0024[ 15] = { /* code 0024, DOLLAR SIGN */
  ___X____,
  ___X____,
  _XXXXX__,
  XX_X_X__,
  XX_X____,
  XX_X____,
  _XXX____,
  __XXXX__,
  ___XXXX_,
  ___X_XX_,
  ___X_XX_,
  X__X_XX_,
  XXXXXX__,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0025[ 22] = { /* code 0025, PERCENT SIGN */
  _XXXX___,__X_____,
  XX__XX__,_X______,
  XX__XX__,X_______,
  XX__XX__,X_______,
  XX__XX_X,________,
  _XXXX_X_,XXXX____,
  _____X_X,X__XX___,
  ____X__X,X__XX___,
  ____X__X,X__XX___,
  ___X___X,X__XX___,
  __X_____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0026[ 22] = { /* code 0026, AMPERSAND */
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,_XX_____,
  ___XXX__,_XX_____,
  _XX__XX_,_XX_____,
  XX____XX,_XX_____,
  XX_____X,XX______,
  XX______,X_______,
  XXX___XX,XX______,
  __XXXXX_,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0027[  4] = { /* code 0027, APOSTROPHE */
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ___X____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _XX_____,
  __X_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002A[  5] = { /* code 002A, ASTERISK */
  ___X____,
  XX_X_XX_,
  __XXX___,
  __X_X___,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002B[  7] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002C[  4] = { /* code 002C, COMMA */
  XX______,
  XX______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002F[ 13] = { /* code 002F, SOLIDUS */
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0030[ 11] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0031[ 11] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XX_XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0032[ 11] = { /* code 0032, DIGIT TWO */
  _XXXXX__,
  _X___XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  _X______,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0033[ 11] = { /* code 0033, DIGIT THREE */
  XXXXX___,
  X___XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  _XXX____,
  ___XXX__,
  ____XX__,
  ____XX__,
  X__XXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0034[ 11] = { /* code 0034, DIGIT FOUR */
  ____XXX_,
  ____XXX_,
  ___XXXX_,
  __XX_XX_,
  __X__XX_,
  _XX__XX_,
  XX___XX_,
  XXXXXXXX,
  _____XX_,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0035[ 11] = { /* code 0035, DIGIT FIVE */
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  ___XXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  X__XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0036[ 11] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  _XX_____,
  _XX_____,
  XX______,
  XX_XXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0037[ 11] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,
  ______XX,
  _____XX_,
  _____XX_,
  _____X__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0038[ 11] = { /* code 0038, DIGIT EIGHT */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  _XXXXX__,
  XXX_XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0039[ 11] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXXXXX,
  ______XX,
  ______X_,
  _X___XX_,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003A[  8] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003B[ 10] = { /* code 003B, SEMICOLON */
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003C[  7] = { /* code 003C, LESS-THAN SIGN */
  _____XX_,
  ___XXX__,
  _XXX____,
  XX______,
  _XXX____,
  ___XXX__,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003E[  7] = { /* code 003E, GREATER-THAN SIGN */
  XX______,
  _XXX____,
  ___XXX__,
  _____XX_,
  ___XXX__,
  _XXX____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003F[ 11] = { /* code 003F, QUESTION MARK */
  XXXXX___,
  X___XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  _XX_____,
  ________,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0040[ 24] = { /* code 0040, COMMERCIAL AT */
  ____XXXX,X_______,
  __XX____,_X______,
  _X______,__X_____,
  _X__XXXX,___X____,
  X__XX__X,___X____,
  X__X___X,___X____,
  X__X___X,___X____,
  X__X__XX,__X_____,
  X___XX_X,XX______,
  _X______,________,
  __X_____,________,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0041[ 22] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___XX__X,X_______,
  __XXX__X,X_______,
  __XX____,XX______,
  _XXXXXXX,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0042[ 22] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXXX_,________,
  XX____XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0043[ 11] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXXX,
  __XX___X,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XXX___X,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0044[ 22] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0045[ 11] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0046[ 11] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0047[ 22] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXXX,X_______,
  __XX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX___XXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XXX___X,X_______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0048[ 22] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0049[ 11] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  XXX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004B[ 22] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX__X___,________,
  XX___X__,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004C[ 11] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004D[ 22] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_X_XX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004E[ 22] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,XX______,
  XXXX____,XX______,
  XXXX____,XX______,
  XX_XX___,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX___XX_,XX______,
  XX___XX_,XX______,
  XX____XX,XX______,
  XX_____X,XX______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004F[ 22] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXXX,________,
  __XX___X,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  __XX___X,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0050[ 11] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XX___XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0051[ 28] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,________,
  __XX___X,XX______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX___X,X_______,
  ___XXXXX,________,
  _____XX_,________,
  ______XX,________,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0052[ 22] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XX__XX__,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0053[ 11] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,
  _XX___X_,
  XX______,
  XX______,
  XXX_____,
  _XXXX___,
  ___XXX__,
  _____XX_,
  _____XX_,
  X____XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0054[ 11] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0055[ 22] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0056[ 22] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  __XX__XX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0057[ 22] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_____X,X_____XX,
  XX____XX,XX____XX,
  XX____XX,XX____XX,
  _XX___XX,XX___XX_,
  _XX__XX_,_XX__XX_,
  _XX__XX_,_XX__XX_,
  __X__XX_,_XX__X__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  ___XXX__,__XXX___,
  ___XX___,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0058[ 22] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,XX______,
  _XX____X,X_______,
  __X___XX,________,
  __XX_XX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ___XXXX_,________,
  __XX__X_,________,
  __XX___X,________,
  _XX____X,X_______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0059[ 22] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX_____X,X_______,
  _XX____X,X_______,
  _XX___XX,________,
  __XX__XX,________,
  __XXXXX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005A[ 22] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,X_______,
  ______XX,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ___XXX__,________,
  ___XX___,________,
  __XX____,________,
  _XXX____,________,
  _XX_____,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005B[ 13] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005C[ 13] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __XX____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005D[ 13] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005E[  7] = { /* code 005E, CIRCUMFLEX ACCENT */
  ___X____,
  __XXX___,
  __X_X___,
  _XX_XX__,
  _X___X__,
  XX___XX_,
  X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0060[  3] = { /* code 0060, GRAVE ACCENT */
  XX______,
  _XX_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0061[  8] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXX__,
  _X___XX_,
  _____XX_,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0063[  8] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XX__X__,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX__X__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  __XXXXXX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0065[  8] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XX___XX,
  XX____XX,
  XXXXXXXX,
  XX______,
  XX______,
  _XX___X_,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  __XXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  _X___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  __XX____,
  __XX____,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  XX______,
  XX______,
  XX______,
  XX___XX_,
  XX__XX__,
  XX_XX___,
  XXXX____,
  XXXX____,
  XX_XX___,
  XX___XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXX_X,XXX_____,
  XXX__XXX,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006E[  8] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXX__,
  XXX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  __XXX_XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0072[  8] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0073[  8] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XX___X__,
  XX______,
  _XXXX___,
  ___XXX__,
  ____XX__,
  X___XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0074[ 10] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0075[  8] = { /* code 0075, LATIN SMALL LETTER U */
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0076[  8] = { /* code 0076, LATIN SMALL LETTER V */
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  __XXXX__,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  XX___XX_,__XX____,
  XX__XXX_,__XX____,
  XX__XXXX,__XX____,
  _XX_XXXX,__X_____,
  _XXXX__X,_XX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XX____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0078[  8] = { /* code 0078, LATIN SMALL LETTER X */
  XX____XX,
  _XX__XX_,
  __X_XX__,
  ___XX___,
  ___XX___,
  __XX_X__,
  _XX__XX_,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XXXX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007A[  8] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XXX____,
  _XX_____,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007C[ 16] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007E[  2] = { /* code 007E, TILDE */
  _XXX__X_,
  X__XXX__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_4F3A[ 26] = { /* code 4F3A */
  __XX____,________,
  __X_XXXX,XXXXX___,
  __X_____,___XX___,
  _XX_XXXX,XXXXX___,
  _XX_____,___XX___,
  XXX_____,___XX___,
  X_X_XXXX,XX_XX___,
  __X_XX__,_X_XX___,
  __X_XX__,_X_XX___,
  __X_XX__,_X_XX___,
  __X_XXXX,XX_XX___,
  __X_____,___XX___,
  __X_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_4F4D[ 26] = { /* code 4F4D */
  ___X___X,________,
  __XX___X,X_______,
  __X_____,X_______,
  _XX_XXXX,XXXXX___,
  _XX__X__,___X____,
  XXX__X__,__XX____,
  X_X__X__,__XX____,
  __X__XX_,__X_____,
  __X__XX_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___X_,_XX_____,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5173[ 26] = { /* code 5173 */
  ____X__X,X_______,
  ___XX___,_X______,
  __XX____,_XX_____,
  __XXXXXX,XXXX____,
  _X____X_,___X____,
  X_____X_,____X___,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  _____XX_,________,
  _____X_X,X_______,
  ____XX__,XXX_____,
  __XX____,__XX____,
  XX______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5177[ 26] = { /* code 5177 */
  _XXXXXXX,XXXX____,
  _XX_____,__XX____,
  _XXXXXXX,XXXX____,
  _XX_____,__XX____,
  _XXXXXXX,XXXX____,
  _XX_____,__XX____,
  _XXXXXXX,XXXX____,
  _XX_____,__XX____,
  XXXXXXXX,XXXXX___,
  ________,________,
  ___XX___,XX______,
  _XXX____,__XX____,
  XX______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52A1[ 26] = { /* code 52A1 */
  ____XX__,________,
  ___XXXXX,XXXX____,
  _XXX____,_XX_____,
  XX_XX___,XX______,
  _____XXX,________,
  ___XXXXX,XXX_____,
  XXX___X_,__XXX___,
  ______X_,________,
  _XXXXXXX,XXXX____,
  _____X__,___X____,
  ____XX__,___X____,
  ___XX___,__XX____,
  XXX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52A8[ 26] = { /* code 52A8 */
  _XXXXX__,X_______,
  ________,X_______,
  ________,X_______,
  _______X,XXXXX___,
  XXXXXX__,X___X___,
  __XX____,X__XX___,
  __X_____,X__XX___,
  __X_X___,X__XX___,
  _XX_XX_X,X__XX___,
  _X___X_X,___XX___,
  XXXXXX_X,___X____,
  XXX__XXX,___X____,
  ______X_,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52D5[ 26] = { /* code 52D5 */
  _____XX_,_X______,
  _XXXX___,_X______,
  ___X____,_X______,
  XXXXXXX_,XXXXX___,
  _X_X__X_,_X__X___,
  _XXXXXX_,_X__X___,
  _X_X__X_,_X__X___,
  _XXXXXX_,_X__X___,
  ___X____,_X__X___,
  _XXXXXX_,XX_XX___,
  ___X____,X__XX___,
  ___XXXX_,X__XX___,
  XXX____X,X_XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_53E3[ 24] = { /* code 53E3 */
  XXXXXXXX,XXX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XXXXXXXX,XXX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5668[ 26] = { /* code 5668 */
  _XXXXX_X,XXXX____,
  _X__XX_X,X__X____,
  _X__XX_X,X__X____,
  _XXXXX_X,XXXX____,
  _____XX_,_XX_____,
  XXXXXXXX,XXXXX___,
  ___XX___,XX______,
  __XX____,_XXX____,
  XXXXXX_X,XXXXX___,
  _X___X_X,X__X____,
  _X___X_X,X__X____,
  _XXXXX_X,XXXX____,
  _X___X_X,X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5730[ 26] = { /* code 5730 */
  __X_____,XX______,
  __X_____,XX______,
  __X__X__,XX__X___,
  XXXX_X__,XXXXX___,
  __X__X_X,XX_XX___,
  __X__XX_,XX_X____,
  __X_XX__,XX_X____,
  __X__X__,XX_X____,
  __X__X__,XX______,
  __XX_X__,XX______,
  _XXXXX__,____X___,
  XX___X__,____X___,
  ______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5740[ 26] = { /* code 5740 */
  __X_____,_X______,
  __X_____,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  XXXXX_X_,_XXXX___,
  __X___X_,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X_X_X_,_X______,
  _XXX__X_,_X______,
  XX____X_,_X______,
  ____XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_57E0[ 28] = { /* code 57E0 */
  _______X,X_______,
  __X__XXX,XXXX____,
  __X__X__,___X____,
  __X__X__,___X____,
  XXXX_XXX,XXXX____,
  __X__X__,________,
  __X__XXX,XXXXX___,
  __X__X__,___XX___,
  __X__X__,___XX___,
  __XX_XXX,XXXXX___,
  _XX_____,X_______,
  X___XXXX,XXXXX___,
  ________,X_______,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5B50[ 26] = { /* code 5B50 */
  __XXXXXX,XXX_____,
  ________,_XX_____,
  ________,XX______,
  _______X,X_______,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5DE5[ 24] = { /* code 5DE5 */
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5F0F[ 26] = { /* code 5F0F */
  ________,X_XX____,
  ________,X_______,
  XXXXXXXX,XXXXX___,
  ________,X_______,
  ________,X_______,
  _XXXXXX_,X_______,
  ___XX___,X_______,
  ___XX___,X_______,
  ___XX___,XX______,
  ___XX___,_X__X___,
  ___XXXXX,_X__X___,
  XXXX____,_XX_X___,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_6001[ 26] = { /* code 6001 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  _____X_X,________,
  ____XX_X,X_______,
  ___XXX__,X_______,
  __XX_XX_,_X______,
  XX____XX,__XX____,
  __X_X_X_,____X___,
  _XX_X_XX,__XX____,
  _X__X__X,___X____,
  XX__X___,_X_XX___,
  X___XXXX,XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_614B[ 26] = { /* code 614B */
  __XXXX_X,X_______,
  __X__X_X,XXXX____,
  _XXXX_XX,X_______,
  X_____XX,X_______,
  _XXXXX__,XXXXX___,
  _X___X__,X_______,
  _XXXXX__,XXXX____,
  _X__XX__,X_______,
  _XXX_X__,X_______,
  XX__XX__,XXXXX___,
  __X_X_X_,___X____,
  _X__X__X,_X_XX___,
  XX__XXXX,XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_63A9[ 24] = { /* code 63A9 */
  __X____X,X_______,
  __X_XXXX,XXXXX___,
  XXXX__XX,_XX_____,
  __X__XX_,X_XX____,
  __X_XXXX,XXXXX___,
  __XX_X__,X__X____,
  _XX__XXX,XXXX____,
  X_X__X__,X__X____,
  __X__X__,X__X____,
  __X__XXX,XXXX____,
  __X_____,X_______,
  XXX_____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_670D[ 26] = { /* code 670D */
  _XXXX_XX,XXXXX___,
  _X__X_XX,___XX___,
  _X__X_XX,___XX___,
  _XXXX_XX,_XXX____,
  _X__X_XX,________,
  _X__X_XX,XXXXX___,
  _X__X_XX,X__XX___,
  _XXXX_XX,X__X____,
  _X__X_XX,_X_X____,
  _X__X_XX,_XXX____,
  _X__X_XX,_XX_____,
  XX__X_XX,_X_X____,
  X_XXX_XX,X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_6A21[ 26] = { /* code 6A21 */
  __X___XX,__X_____,
  __X_XXXX,XXXXX___,
  __X___XX,__X_____,
  XXXX_XXX,XXXX____,
  __X__XX_,___X____,
  _XXX_XXX,XXXX____,
  _XX_XXX_,___X____,
  X_X__XXX,XXXX____,
  X_X_____,X_______,
  __X_XXXX,XXXXX___,
  __X____X,X_______,
  __X___XX,_XX_____,
  __X_XX__,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7801[ 26] = { /* code 7801 */
  XXXXX_XX,XXXX____,
  __X___X_,___X____,
  __X___X_,___X____,
  _XX___X_,__XX____,
  _X____X_,__XX____,
  _XXXX_X_,__XX____,
  XX_XX_XX,XXXXX___,
  XX_XXX__,___XX___,
  _X_XX___,___XX___,
  _X_XXXXX,XXXXX___,
  _X_XX___,___XX___,
  _XXXX___,___X____,
  _X______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7AEF[ 26] = { /* code 7AEF */
  _XX_____,XX______,
  __X___X_,XX_X____,
  XXXXX_X_,XX_X____,
  _X_X__XX,XXXX____,
  XX_XX___,________,
  _X_X_XXX,XXXXX___,
  _X_X____,X_______,
  _X_X_XXX,XXXXX___,
  _X_X_XXX,XX_XX___,
  _X_X_XXX,XX_XX___,
  _X_XXXXX,XX_XX___,
  _XXX_XXX,XX_XX___,
  XX___XXX,XX_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7DB2[ 26] = { /* code 7DB2 */
  __XX_XXX,XXXXX___,
  __X_XXX_,___XX___,
  _XX_XXXX,__XXX___,
  _X_X_XX_,XXXXX___,
  XXXX_XXX,XXXXX___,
  __X__XX_,XX_XX___,
  _XXXXXX_,_X_XX___,
  XXXXXXXX,XXXXX___,
  XXX_XXXX,X__XX___,
  _____XXX,X__XX___,
  _XX_XXX_,XXXXX___,
  XXXXXXX_,___XX___,
  X_XX_XX_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7F51[ 24] = { /* code 7F51 */
  XXXXXXXX,XXXX____,
  X___X___,X_XX____,
  X___X___,X_XX____,
  X_X_X_X_,X_XX____,
  XXX_XXX_,X_XX____,
  X_XXX__X,X_XX____,
  X__X___X,X_XX____,
  X__XX__X,X_XX____,
  X_XXX_XX,XXXX____,
  X_X_XXX_,_XXX____,
  XXX___X_,__XX____,
  X_______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7F69[ 28] = { /* code 7F69 */
  _XXXXXXX,XXXX____,
  _X__X___,X__X____,
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______XX,XXXX____,
  ______X_,________,
  __XXXXXX,XXXX____,
  __X_____,__XX____,
  __XXXXXX,XXXX____,
  __X_____,__XX____,
  __XXXXXX,XXXX____,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8A0A[ 26] = { /* code 8A0A */
  _XX__XXX,XXX_____,
  __X____X,__X_____,
  XXXXX__X,__X_____,
  _______X,__X_____,
  XXXXX__X,__X_____,
  _____XXX,XXX_____,
  XXXXX__X,__X_____,
  _______X,__X_____,
  XXXXX__X,__X_X___,
  XX_XX__X,__X_X___,
  XX_XX__X,__X_X___,
  XXXXX__X,__XXX___,
  XX_XX__X,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8A2D[ 26] = { /* code 8A2D */
  __X____X,XXX_____,
  __X____X,__X_____,
  XXXXX__X,__X_____,
  ______XX,__X_____,
  XXXXXXX_,__XXX___,
  ________,________,
  XXXXX_XX,XXXX____,
  _______X,___X____,
  XXXXX__X,__XX____,
  XX__X___,XXX_____,
  XX__X___,XX______,
  XXXXX__X,X_X_____,
  XX__XXX_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8DEF[ 26] = { /* code 8DEF */
  XXXXX___,X_______,
  XX__X__X,XXXX____,
  XX__X_XX,___X____,
  XXXXXX_X,X_X_____,
  __XX____,XX______,
  _XXX___X,XXXX____,
  _XXXXXX_,___XX___,
  _XXX____,________,
  _XXX__XX,XXXX____,
  _XXX__X_,___X____,
  _XXXX_X_,___X____,
  _XXXX_XX,XXXX____,
  XX____X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_901A[ 26] = { /* code 901A */
  _X__XXXX,XXXX____,
  _XX___X_,__XX____,
  __X___XX,_XX_____,
  XXXX___X,XX______,
  __XX_XXX,XXXXX___,
  _XX__X__,X__XX___,
  _X___XXX,XXXXX___,
  XXXX_X__,X__XX___,
  __XX_XXX,XXXXX___,
  __X__X__,X__XX___,
  _XX__X__,X_XXX___,
  _X_XX___,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9053[ 26] = { /* code 9053 */
  _X___XX_,__XX____,
  _XX___X_,__X_____,
  __XXXXXX,XXXXX___,
  XXXX___X,X_______,
  __X__XXX,XXXX____,
  _XX__X__,___X____,
  _X___XXX,XXXX____,
  XXXX_X__,___X____,
  __XX_XXX,XXXX____,
  __X__X__,___X____,
  _XX__XXX,XXXX____,
  XX_X____,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_906E[ 26] = { /* code 906E */
  _X______,X_______,
  _XX__XXX,XXXXX___,
  __X__X__,________,
  XXXX_X_X,__XX____,
  __X__XXX,XXXXX___,
  _XX__X_X,__XX____,
  _X___X_X,__XX____,
  XXXXXX_X,XXXX____,
  __XXXX__,________,
  __X_X_X_,XXXX____,
  _XX_X_X_,X_X_X___,
  _X_X_X__,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9598[ 26] = { /* code 9598 */
  XXXXXX_X,XXXXX___,
  XX___X_X,___XX___,
  XXXXXX_X,XXXXX___,
  XX___X_X,___XX___,
  XXXXXX_X,XXXXX___,
  XX______,___XX___,
  XX_XXXXX,XX_XX___,
  XX_X__X_,_X_XX___,
  XX_XXXXX,XX_XX___,
  XX_X__X_,_X_XX___,
  XX_XXXXX,XX_XX___,
  XX____X_,___XX___,
  XX____X_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9759[ 26] = { /* code 9759 */
  __XX____,X_______,
  XXXXXX_X,XXXX____,
  __XX___X,__X_____,
  _XXXXXX_,_XX_____,
  XXXXXX_X,XXXX____,
  ________,_X_X____,
  _XXXX___,_X_X____,
  _X__X_XX,XXXXX___,
  _XXXX___,_X_X____,
  _X__X__X,XXXX____,
  _XXXX___,_X______,
  XX__X___,_X______,
  X__XX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_975C[ 26] = { /* code 975C */
  ___X____,__XXX___,
  XXXXXXXX,XX______,
  ___X__XX,_X__X___,
  _XXXXX_X,_X_XX___,
  ___X___X,_XXX____,
  XXXXXX_X,XXXX____,
  ________,_X_X____,
  _XXXXXXX,XXXXX___,
  _X__XX__,_X_X____,
  _XXXXX_X,XXXX____,
  _X__XX__,_X______,
  XXXXXX__,_X______,
  XX_XX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9810[ 26] = { /* code 9810 */
  XXXXX_XX,XXXXX___,
  ___XX___,_X______,
  _X_X____,XX______,
  _XXX__XX,XXXXX___,
  __XX__XX,___XX___,
  XXXXXXXX,XXXXX___,
  __X_XXXX,___XX___,
  __X_X_XX,XXXXX___,
  __X_X_XX,___XX___,
  __X___XX,XXXXX___,
  __X____X,X_X_____,
  __X___XX,___XX___,
  _XX__XX_,____X___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[130] = {
   {   1,   1,   0,  15,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0020 } /* code 0020, SPACE */
  ,{   2,  11,   1,   4,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   4,   1,   4,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0022 } /* code 0022, QUOTATION MARK */
  ,{   9,  10,   0,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0023 } /* code 0023, NUMBER SIGN */
  ,{   7,  15,   1,   2,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0024 } /* code 0024, DOLLAR SIGN */
  ,{  13,  11,   1,   4,  14, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0025 } /* code 0025, PERCENT SIGN */
  ,{  12,  11,   1,   4,  13, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0026 } /* code 0026, AMPERSAND */
  ,{   1,   4,   1,   4,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0027 } /* code 0027, APOSTROPHE */
  ,{   4,  14,   1,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  14,   0,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   7,   5,   0,   4,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002A } /* code 002A, ASTERISK */
  ,{   7,   7,   2,   7,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002B } /* code 002B, PLUS SIGN */
  ,{   2,   4,   0,  13,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002C } /* code 002C, COMMA */
  ,{   5,   1,   1,  10,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  13,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002E } /* code 002E, FULL STOP */
  ,{   7,  13,   0,   4,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_002F } /* code 002F, SOLIDUS */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0030 } /* code 0030, DIGIT ZERO */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0032 } /* code 0032, DIGIT TWO */
  ,{   6,  11,   2,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  11,   0,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,  11,   2,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  11,   0,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   8,   1,   7,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003A } /* code 003A, COLON */
  ,{   3,  10,   0,   7,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003B } /* code 003B, SEMICOLON */
  ,{   7,   7,   2,   6,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   4,   2,   8,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003D } /* code 003D, EQUALS SIGN */
  ,{   7,   7,   2,   6,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   6,  11,   1,   4,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_003F } /* code 003F, QUESTION MARK */
  ,{  12,  12,   1,   4,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0040 } /* code 0040, COMMERCIAL AT */
  ,{  11,  11,   0,   4,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  11,   1,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   8,  11,   1,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   9,  11,   1,   4,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  11,   1,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  12,   0,   4,   6, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  11,   1,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,  11,   1,   4,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  11,   1,   4,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  10,  11,   1,   4,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  11,  11,   1,   4,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  11,  14,   1,   4,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  11,   1,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   7,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  11,   1,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  11,   1,   4,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  10,  11,   0,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  16,  11,   0,   4,  16, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  11,   0,   4,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  11,   0,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  11,   0,   4,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  13,   2,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   6,  13,   0,   4,   6, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  13,   0,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   7,   7,   2,   4,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   7,   1,   0,  16,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   3,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0060 } /* code 0060, GRAVE ACCENT */
  ,{   7,   8,   1,   7,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  12,   1,   3,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   8,   1,   7,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  12,   1,   3,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   8,   1,   7,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,  12,   1,   3,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   7,  12,   1,   3,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  12,   1,   3,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  16,  -1,   3,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   8,  12,   1,   3,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  12,   1,   3,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  12,   8,   1,   7,  14, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   7,   8,   1,   7,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   8,   1,   7,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,  12,   1,   7,  10, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   8,   1,   7,   6, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   8,   1,   7,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  10,   1,   5,   6, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   7,   8,   1,   7,   9, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,   8,   0,   7,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  12,   8,   0,   7,  12, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   8,   8,   0,   7,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,  12,   0,   7,   8, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   8,   0,   7,   7, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  14,   1,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  16,   1,   3,   4, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  14,   1,   4,   5, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   7,   2,   2,   9,  11, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_007E } /* code 007E, TILDE */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_4F3A } /* code 4F3A */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_4F4D } /* code 4F4D */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5173 } /* code 5173 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5177 } /* code 5177 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52A1 } /* code 52A1 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52A8 } /* code 52A8 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_52D5 } /* code 52D5 */
  ,{  11,  12,   2,   4,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_53E3 } /* code 53E3 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5668 } /* code 5668 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5730 } /* code 5730 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5740 } /* code 5740 */
  ,{  13,  14,   1,   2,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_57E0 } /* code 57E0 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5B50 } /* code 5B50 */
  ,{  13,  12,   1,   4,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5DE5 } /* code 5DE5 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_5F0F } /* code 5F0F */
  ,{  13,  13,   1,   2,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_6001 } /* code 6001 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_614B } /* code 614B */
  ,{  13,  12,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_63A9 } /* code 63A9 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_670D } /* code 670D */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_6A21 } /* code 6A21 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7801 } /* code 7801 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7AEF } /* code 7AEF */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7DB2 } /* code 7DB2 */
  ,{  12,  12,   2,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7F51 } /* code 7F51 */
  ,{  13,  14,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_7F69 } /* code 7F69 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8A0A } /* code 8A0A */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8A2D } /* code 8A2D */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_8DEF } /* code 8DEF */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_901A } /* code 901A */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9053 } /* code 9053 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_906E } /* code 906E */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9598 } /* code 9598 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9759 } /* code 9759 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_975C } /* code 975C */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_9810 } /* code 9810 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop36 = {
   0x9810 /* first character */
  ,0x9810 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[129] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop35 = {
   0x975C /* first character */
  ,0x975C /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[128] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop34 = {
   0x9759 /* first character */
  ,0x9759 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[127] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop33 = {
   0x9598 /* first character */
  ,0x9598 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[126] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop32 = {
   0x906E /* first character */
  ,0x906E /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[125] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop31 = {
   0x9053 /* first character */
  ,0x9053 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[124] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop30 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[123] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop29 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[122] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop28 = {
   0x8A2D /* first character */
  ,0x8A2D /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[121] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop27 = {
   0x8A0A /* first character */
  ,0x8A0A /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[120] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop26 = {
   0x7F69 /* first character */
  ,0x7F69 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[119] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop25 = {
   0x7F51 /* first character */
  ,0x7F51 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[118] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop24 = {
   0x7DB2 /* first character */
  ,0x7DB2 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[117] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop23 = {
   0x7AEF /* first character */
  ,0x7AEF /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[116] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop22 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[115] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop21 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[114] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop20 = {
   0x670D /* first character */
  ,0x670D /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[113] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop19 = {
   0x63A9 /* first character */
  ,0x63A9 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[112] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop18 = {
   0x614B /* first character */
  ,0x614B /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[111] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop17 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[110] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop16 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[109] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop15 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[108] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop14 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[107] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop13 = {
   0x57E0 /* first character */
  ,0x57E0 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[106] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop12 = {
   0x5740 /* first character */
  ,0x5740 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[105] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop11 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[104] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop10 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[103] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop9 = {
   0x53E3 /* first character */
  ,0x53E3 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[102] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop8 = {
   0x52D5 /* first character */
  ,0x52D5 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[101] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop7 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[100] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop6 = {
   0x52A1 /* first character */
  ,0x52A1 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop5 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop4 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[ 97] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop3 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop2 = {
   0x4F3A /* first character */
  ,0x4F3A /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Net_Info_MicrosoftJhengHei_19B_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

