/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Tool_Info_Microsoft JhengHei_22B.c            *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_Tool_Info_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0030[ 13] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0031[ 13] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XXXXX___,
  X__XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0032[ 13] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _XXXXXX_,
  _X____XX,
  ______XX,
  ______XX,
  ______X_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0033[ 13] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XXXXXXX_,
  X____XX_,
  _____XX_,
  ____XXX_,
  _XXXX___,
  _XXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0034[ 26] = { /* code 0034, DIGIT FOUR */
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___X__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _X____XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0035[ 13] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0036[ 13] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  __XXXXX_,
  _XXX____,
  _XX_____,
  XX______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0037[ 26] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0038[ 13] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _XXXXXXX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXX___,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0039[ 13] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XXXXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,________,
  _XXX____,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0045[ 13] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0046[ 13] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,__X_____,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX____XX,XXX_____,
  XX____XX,XXX_____,
  XX______,_XX_____,
  _XX_____,_XX_____,
  _XXX____,_XX_____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XXX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XXX__,________,
  XXXXX___,________,
  XX_XXX__,________,
  XX__XXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004C[ 13] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004D[ 26] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__X___,X__XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,_XX_____,
  XXXX____,_XX_____,
  XXXX____,_XX_____,
  XX_XX___,_XX_____,
  XX_XXX__,_XX_____,
  XX__XX__,_XX_____,
  XX___XX_,_XX_____,
  XX___XX_,_XX_____,
  XX____XX,_XX_____,
  XX_____X,XXX_____,
  XX_____X,XXX_____,
  XX______,XXX_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0050[ 13] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XXXXXXX_,
  XX___XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  XXXXXXX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,________,
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0053[ 13] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  _XX_____,
  _XXXXX__,
  ___XXXX_,
  _____XXX,
  ______XX,
  X_____XX,
  XXXXXXX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ____XX_X,________,
  ____XXXX,________,
  ____XXXX,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0057[ 39] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  __X___XX,__XX___X,________,
  __XX__XX,__XX__XX,________,
  __XX__XX,__XX__XX,________,
  ___X__X_,___X__X_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0058[ 26] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,_XX_____,
  _XX_____,XX______,
  __X____X,X_______,
  __XX__XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  _____X__,________,
  ____XXX_,________,
  ___XX_XX,________,
  __XX___X,X_______,
  __XX____,X_______,
  _XX_____,XX______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX____,XX______,
  __XX___X,X_______,
  ___XX__X,X_______,
  ___XXXXX,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_005A[ 26] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXX_,
  _XXXXXXX,
  _X____XX,
  ______XX,
  _XXXXXXX,
  XXX___XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0062[ 28] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0067[ 26] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _X____XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0068[ 28] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006A[ 17] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006B[ 28] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX_XX___,________,
  XX___XX_,________,
  XX____XX,________,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX__XXX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0071[ 26] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XXXXXX__,
  XX___X__,
  XXXX____,
  _XXXX___,
  ____XX__,
  X___XX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____XX,____XX__,
  XX____XX,____XX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__X__,X__XX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,_XXX____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0078[ 18] = { /* code 0078, LATIN SMALL LETTER X */
  XX_____X,X_______,
  _XX___XX,________,
  __X__XX_,________,
  ___XXX__,________,
  ____X___,________,
  ___XXX__,________,
  __XX__X_,________,
  _XX___XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0079[ 26] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___X_X__,________,
  ___XXX__,________,
  ____XX__,________,
  ___XX___,________,
  __XXX___,________,
  XXXX____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_4F53[ 32] = { /* code 4F53 */
  ___XX___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  __XXXXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  _XX_____,XXX_____,
  XXX____X,XXXX____,
  XXX___XX,_X_X____,
  __X___XX,_X_XX___,
  __X__XX_,_X__XX__,
  __X_XX__,_X___XX_,
  __X_X_XX,XXXXX_X_,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_4FA6[ 32] = { /* code 4FA6 */
  ___X____,XX______,
  __XX____,XX______,
  __XX____,XXXXXXX_,
  __X_____,XXXXXXX_,
  _XX_____,XX______,
  _XX_XXXX,XXXXXX__,
  XXX_XXXX,XXXXXX__,
  XXX_XX__,____XX__,
  __X_XX__,XX__XX__,
  __X_XX__,XX__XX__,
  __X_XX__,XX__XX__,
  __X_XX__,XX__XX__,
  __X_____,XXXX____,
  __X___XX,X__XX___,
  __XXXXXX,____XX__,
  __X_XX__,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5075[ 32] = { /* code 5075 */
  ___XX___,XX______,
  ___X____,XXXXXXX_,
  __XX____,XXXXXXX_,
  __X_____,XX______,
  _XX__XXX,XXXXXX__,
  _XX__XXX,XXXXXX__,
  XXX__X__,_____X__,
  __X__XXX,XXXXXX__,
  __X__X__,_____X__,
  __X__XXX,XXXXXX__,
  __X__X__,_____X__,
  __X__XXX,XXXXXX__,
  __X__XXX,XXXXXX__,
  __X____X,________,
  __X__XXX,___XX___,
  __X_XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5177[ 30] = { /* code 5177 */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____X___,__XX____,
  _XXXX___,___XXX__,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_529B[ 30] = { /* code 529B */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ______XX,_____X__,
  ______XX,_____X__,
  ______X_,_____X__,
  ______X_,____XX__,
  _____XX_,____XX__,
  _____X__,____XX__,
  ____XX__,____XX__,
  ___XX___,____XX__,
  __XX____,XXXXXX__,
  _X______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ________,___XX___,
  ________,___X____,
  _______X,XXXX____,
  _______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_578B[ 30] = { /* code 578B */
  _XXXXXXX,X____X__,
  _XXXXXXX,X_X__X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  XXXXXXXX,X_X__X__,
  XXXXXXXX,X_X__X__,
  __XX__X_,_____X__,
  __XX__X_,__XXXX__,
  _XX___X_,___XXX__,
  _X_____X,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5DE5[ 28] = { /* code 5DE5 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5E8F[ 32] = { /* code 5E8F */
  _______X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,________,
  _XX_XXXX,XXXXXX__,
  _XX_XXXX,XXXXXX__,
  _XX_____,__XXX___,
  _XX___XX,XXX_____,
  _XX____X,XX______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,XX__XX__,
  _XX_____,XX__X___,
  XX____XX,XX______,
  _X____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  _______X,X_______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __X___X_,___X____,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  __X___X_,___X____,
  __X___XX,XXXX____,
  __X___XX,XXXX____,
  __X_____,________,
  _XX_XXXX,XXXXX___,
  _XX_XXXX,XXXXX___,
  _XX__XXX,__XX____,
  XX_XXXXX,XXXXXXX_,
  _X_XXXX_,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_626D[ 30] = { /* code 626D */
  __XX__XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  XXXXXX__,XX__XX__,
  XXXXXX__,X___XX__,
  __XX____,X___XX__,
  __XX____,X___XX__,
  __XXX_XX,XXXXXXX_,
  _XXXX_XX,XXXXXXX_,
  XXXX____,X___X___,
  X_XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  XXXX_XXX,XXXXXXX_,
  _XXX_XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_672C[ 32] = { /* code 672C */
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  ______XX,XX______,
  _____X_X,_X______,
  ____XX_X,_XX_____,
  ____X__X,__X_____,
  ___XX__X,__XX____,
  __XX___X,___XX___,
  _XX____X,____XX__,
  XX_XXXXX,XXXX_XX_,
  ___XXXXX,XXXX____,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6C60[ 32] = { /* code 6C60 */
  _X______,_XX_____,
  _XX_____,_XX_____,
  __XX__X_,_XX_____,
  ___X__X_,_XX_XXX_,
  _X____X_,_XXXXX__,
  _XX___XX,XXX__X__,
  __XX_XXX,_XX__X__,
  ___X__X_,_XX__X__,
  ______X_,_XX_XX__,
  ______X_,_XX_XX__,
  ___X__X_,_XX_____,
  __XX__X_,_XX_____,
  __XX__X_,______X_,
  _XX___X_,_____XX_,
  _X____XX,XXXXXXX_,
  _X____XX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6D4B[ 32] = { /* code 6D4B */
  _X__XXXX,XX___XX_,
  _XX_XXXX,XX_X_XX_,
  __XXX___,XX_X_XX_,
  ____X_X_,XX_X_XX_,
  XX__X_X_,XX_X_XX_,
  _XX_X_X_,XX_X_XX_,
  __X_X_X_,XX_X_XX_,
  ____X_X_,XX_X_XX_,
  ____X_X_,XX_X_XX_,
  __X_X_X_,XX_X_XX_,
  _XX_X_X_,XX_X_XX_,
  _XX___X_,___X_XX_,
  _X___X__,X__X_XX_,
  XX__XX__,X____XX_,
  X__X____,XX_XXXX_,
  ________,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6E29[ 30] = { /* code 6E29 */
  _X______,________,
  __XX_XXX,XXXXX___,
  ___XXXXX,XXXXX___,
  _____XXX,XXXXX___,
  XX___X__,____X___,
  _XX__X__,____X___,
  __X__XXX,XXXXX___,
  ___X_XXX,XXXXX___,
  __X_XXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXXX_X,__X_XX__,
  _XX_XX_X,__X_XX__,
  _XX_XX_X,__X_XX__,
  XX_XXXXX,XXXXXXX_,
  _X_XXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6E2C[ 32] = { /* code 6E2C */
  _X______,_____XX_,
  _XX_XXXX,X____XX_,
  __XXXXXX,X__X_XX_,
  __X_XX__,X__X_XX_,
  ____XXXX,X__X_XX_,
  _X__XXXX,X__X_XX_,
  XXX_XX__,X__X_XX_,
  _XXXXXXX,X__X_XX_,
  __X_XXXX,X__X_XX_,
  ____XX__,X__X_XX_,
  __X_XX__,X__X_XX_,
  __X_XXXX,X__X_XX_,
  _XX_XXXX,X____XX_,
  _XX__XXX,X____XX_,
  XX__XX__,XX_XXXX_,
  _X__X___,XX_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6EAB[ 32] = { /* code 6EAB */
  _X___XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  ___XXX__,_X__XX__,
  _____X__,XXX_XX__,
  XX___X_X,X_XXXX__,
  _XX__X_X,____XX__,
  __XX_XXX,XXXXXX__,
  ___X_XXX,XXXXXX__,
  ________,________,
  _____XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX_X_X,X_X__X__,
  __X__X_X,X_X__X__,
  _XX_XXXX,XXXXXXX_,
  _X__XXXX,XXXXXXX_,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_7248[ 30] = { /* code 7248 */
  _XX_XX_X,XXXXXXX_,
  _XX_XX_X,XXXXXXX_,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XXXXX_X,XXXXXX__,
  _XXXXX_X,XXXXXX__,
  _XX____X,XX__XX__,
  _XX____X,XXX_XX__,
  _XXXXX_X,X_X_X___,
  _XXXXX_X,X_X_X___,
  _X__XX_X,X_XXX___,
  _X__XX_X,___X____,
  XX__XX_X,__XXX___,
  XX__XXXX,_XX_XX__,
  ____XX_X,XX____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_7535[ 30] = { /* code 7535 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X_____X_,___XX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X_____X_,___XX___,
  X_____X_,___XX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  ______X_,_____X__,
  ______X_,____XX__,
  ______XX,XXXXXX__,
  ______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_865F[ 30] = { /* code 865F */
  _XXXXX__,_XX_____,
  _XXXXX__,_XXXXX__,
  _X__XX__,_XX_____,
  _XXXXX_X,XXXXXXX_,
  _XXXXX_X,__X__XX_,
  _______X,_XXXX___,
  XXXXXX_X,__X_____,
  _XX____X,__XXXXX_,
  _XXXX__X,________,
  _XXXX__X,_X_XX___,
  ____X_XX,_X_XX___,
  ____X_XX,_X_XX_X_,
  ____X_XX,_X_XX_X_,
  _XXXX_X_,XX_XXXX_,
  __XX_XXX,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_96FB[ 30] = { /* code 96FB */
  _XXXXXXX,XXXXXX__,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XX_XX__X,___X_XX_,
  XXX__X_X,_XX_XXX_,
  __XXX__X,___X____,
  ________,________,
  _XXXXXXX,XXXXX___,
  _XX____X,____X___,
  _XXXXXXX,XXXXX___,
  _XX____X,____X___,
  _XXXXXXX,XXXXX___,
  _______X,_____XX_,
  _______X,XXXXXXX_,
  _______X,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_97CC[ 32] = { /* code 97CC */
  ___X____,________,
  _XXXXXX_,XXXXXXX_,
  __XX__X_,XXXXXXX_,
  __XX__X_,__XX_XX_,
  XXXXXXXX,__XX_XX_,
  ________,X_XX_XX_,
  _XXXXXX_,XXXX_XX_,
  _X____X_,_XXX_XX_,
  _XXXXXX_,__XX_XX_,
  ____XX__,__X__XX_,
  XXXXXXXX,__X__XX_,
  _X__XX__,_XX__XX_,
  _X__XX__,_XX__XX_,
  XXXXXXXX,XX___X__,
  ____XX__,XX_XXX__,
  ____XX__,X__XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_97E7[ 30] = { /* code 97E7 */
  ___X____,XXXXXXX_,
  XXXXXXX_,XXXXXXX_,
  XXXXXXX_,__X__XX_,
  ___X____,X_X__XX_,
  _XXXXXX_,X_X__XX_,
  _XXXXXXX,X_X__XX_,
  ___X___X,__X__X__,
  XXXXXXX_,__X__X__,
  XXXXXXX_,__X__X__,
  ___X__X_,_XX__X__,
  ___X_XX_,_X___X__,
  ___XXXX_,XX___X__,
  ___X_X__,X____X__,
  ___X___X,__XXXX__,
  ___X__XX,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_9AD4[ 30] = { /* code 9AD4 */
  _XXXXX__,_XXXX___,
  _X___X_X,XXXXXXX_,
  _X_XXX_X,_XXXXXX_,
  _X_X_X_X,XXXXXXX_,
  XXXXXXXX,_XXXXXX_,
  XX___XXX,XXXXXXX_,
  XXXXXXX_,________,
  _X__XX_X,XXXXXXX_,
  _XXXXX__,________,
  _X__XX_X,XXXXXX__,
  _X_XXX_X,X____X__,
  _XXXXX_X,XXXXXX__,
  _XX_XX__,XX__X___,
  XX_XXX__,_X__X___,
  X__XX_XX,XXXXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[87] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  13,   2,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  13,   0,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0039 } /* code 0039, DIGIT NINE */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  13,   1,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  13,   1,   4,  13, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  13,   2,   4,   5, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  13,   1,   4,   7, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  13,   2,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  13,   2,   4,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  13,   2,   4,  14, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  12,  13,   1,   4,  14, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  13,   2,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  12,  16,   1,   4,  14, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  13,   1,   4,  13, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  13,   0,   4,  18, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   9,   1,   8,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  14,   0,   3,   6, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   5, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  17,  -2,   4,   5, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  14,   1,   3,  10, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  14,   1,   3,   5, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,   9,   1,   8,  16, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   9,   1,   8,   7, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   8, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  12,   0,   5,   7, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  11, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,   9,   0,   8,  14, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  13,   0,   8,   9, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   0,   8,   8, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_4F53 } /* code 4F53 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_4FA6 } /* code 4FA6 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5075 } /* code 5075 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5177 } /* code 5177 */
  ,{  14,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_529B } /* code 529B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_53F7 } /* code 53F7 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_578B } /* code 578B */
  ,{  15,  14,   1,   4,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5DE5 } /* code 5DE5 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5E8F } /* code 5E8F */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_5EA6 } /* code 5EA6 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_626D } /* code 626D */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_672C } /* code 672C */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6C60 } /* code 6C60 */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6D4B } /* code 6D4B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6E29 } /* code 6E29 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6E2C } /* code 6E2C */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_6EAB } /* code 6EAB */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_7248 } /* code 7248 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_7535 } /* code 7535 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_865F } /* code 865F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_96FB } /* code 96FB */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_97CC } /* code 97CC */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_97E7 } /* code 97E7 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_9AD4 } /* code 9AD4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop28 = {
   0x9AD4 /* first character */
  ,0x9AD4 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 86] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop27 = {
   0x97E7 /* first character */
  ,0x97E7 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 85] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop26 = {
   0x97CC /* first character */
  ,0x97CC /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 84] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop25 = {
   0x96FB /* first character */
  ,0x96FB /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 83] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop24 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 82] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop23 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 81] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop22 = {
   0x7248 /* first character */
  ,0x7248 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop21 = {
   0x6EAB /* first character */
  ,0x6EAB /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop20 = {
   0x6E2C /* first character */
  ,0x6E2C /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop19 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop18 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop17 = {
   0x6C60 /* first character */
  ,0x6C60 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop16 = {
   0x672C /* first character */
  ,0x672C /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop15 = {
   0x626D /* first character */
  ,0x626D /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop14 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop13 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop12 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop11 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop10 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop9 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop8 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop7 = {
   0x5075 /* first character */
  ,0x5075 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 65] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop6 = {
   0x4FA6 /* first character */
  ,0x4FA6 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 64] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop5 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 63] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop4 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Tool_Info_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

