/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_JS_2_Step2_1_Microsoft JhengHei_16B.c         *
* Font:        微軟正黑體                                            *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_JS_2_Step2_1_Microsoft JhengHei_16B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002F[ 11] = { /* code 002F, SOLIDUS */
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_516C[ 22] = { /* code 516C */
  ___X_XX_,________,
  ___X___X,________,
  __X____X,________,
  _XX_XX__,X_______,
  XX__X___,XX______,
  X___X___,_X______,
  ___X__X_,________,
  ___X___X,________,
  __X____X,X_______,
  _XXXXXXX,X_______,
  _XXX____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5206[ 22] = { /* code 5206 */
  ___X__XX,________,
  __XX___X,________,
  __X____X,X_______,
  _X______,X_______,
  X_XXXXXX,_X______,
  ____X__X,________,
  ___X___X,________,
  ___X___X,________,
  __XX___X,________,
  _XX____X,________,
  XX___XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5398[ 22] = { /* code 5398 */
  _XXXXXXX,XX______,
  _X______,________,
  _X_XXXXX,X_______,
  _X_X_X__,X_______,
  _X_XXXXX,X_______,
  _X_X_X__,X_______,
  _X_XXXXX,X_______,
  X____X__,________,
  X_XXXXXX,XX______,
  X____X__,________,
  X_XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_540B[ 22] = { /* code 540B */
  ________,X_______,
  XXXX____,X_______,
  X__XXXXX,XX______,
  X__X____,X_______,
  X__XX___,X_______,
  X__X_X__,X_______,
  X__X_XX_,X_______,
  X__X__X_,X_______,
  XXXX____,X_______,
  X__X____,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5708[ 22] = { /* code 5708 */
  XXXXXXXX,XX______,
  X_X__X_X,_X______,
  X__XX_X_,_X______,
  X_XXXXXX,_X______,
  X___X___,_X______,
  X_XXXXXX,_X______,
  X_XXXXXX,XX______,
  XXXX_XX_,_X______,
  X__X____,_X______,
  XXXXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5C3A[ 22] = { /* code 5C3A */
  _XXXXXXX,XX______,
  _X______,XX______,
  _X______,XX______,
  _X______,XX______,
  _XXXXXXX,XX______,
  _X_X____,________,
  _X_X____,________,
  _X__X___,________,
  _X___XX_,________,
  X_____XX,X_______,
  X_______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_65A4[ 22] = { /* code 65A4 */
  _______X,X_______,
  _XXXXXX_,________,
  _X______,________,
  _X______,________,
  _XXXXXXX,XX______,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  X_____X_,________,
  X_____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_725B[ 22] = { /* code 725B */
  __X__X__,________,
  _XX__X__,________,
  _XXXXXXX,XX______,
  XX___X__,________,
  X____X__,________,
  _____X__,________,
  XXXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_78C5[ 22] = { /* code 78C5 */
  XXXX__X_,________,
  _X__XXXX,XX______,
  _X___X__,X_______,
  XX__XXXX,XX______,
  XXX_X_X_,_X______,
  XXX_XXXX,XX______,
  _XX__X__,________,
  _XX__XXX,XX______,
  _XX__X__,XX______,
  _X__X___,X_______,
  ___XX__X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_79D2[ 22] = { /* code 79D2 */
  __XX___X,________,
  XXX__X_X,X_______,
  __X__X_X,_X______,
  XXXX_X_X,_X______,
  _XX_X__X,_X______,
  _XXXX__X,________,
  X_XX___X,_X______,
  X_X_____,XX______,
  __X____X,X_______,
  __X___XX,________,
  __X_XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_7C73[ 22] = { /* code 7C73 */
  _X__XX__,X_______,
  _XX_XX_X,X_______,
  __X_XX_X,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  ____XX__,________,
  __X_XX_X,________,
  __XXXXXX,X_______,
  _XX_XX__,X_______,
  XX__XX__,_X______,
  X___XX__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_82F1[ 22] = { /* code 82F1 */
  __X____X,________,
  XXXXXXXX,XX______,
  __X____X,________,
  _____X__,________,
  _XXXXXXX,X_______,
  _X___X__,X_______,
  _X__XX__,X_______,
  XXXXXXXX,XX______,
  ____X_X_,________,
  __XX_X_X,X_______,
  XX______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_9418[ 22] = { /* code 9418 */
  _XX___X_,________,
  _XX_XXXX,XX______,
  X__X_X__,X_______,
  XXX_XXXX,XX______,
  _X__X__X,_X______,
  XXXXX__X,_X______,
  _X__XXXX,XX______,
  XX_X___X,________,
  XX__XXXX,XX______,
  _XXX___X,________,
  XXX_XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_949F[ 22] = { /* code 949F */
  _X_____X,________,
  _XXX___X,________,
  X___XXXX,XX______,
  XXX_X__X,_X______,
  XX__X__X,_X______,
  _X__X__X,_X______,
  XXXXX__X,_X______,
  _X__XXXX,XX______,
  _X_____X,________,
  _X_X___X,________,
  _XX____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_9813[ 22] = { /* code 9813 */
  __X__XXX,XX______,
  XXXXX__X,________,
  __X__XXX,XX______,
  X_XX_X__,_X______,
  X_XX_XXX,XX______,
  X_XX_X__,_X______,
  X_XX_XXX,XX______,
  XXXX_X__,_X______,
  __X__XXX,XX______,
  __XX__X_,X_______,
  __X_XX__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_987F[ 22] = { /* code 987F */
  __X__XXX,XX______,
  XXXXX__X,________,
  __X__XXX,XX______,
  X_X_XX__,_X______,
  X_X_XX_X,_X______,
  X_X_XX_X,_X______,
  XXXXXX_X,_X______,
  __X__X_X,_X______,
  __X_X_XX,X_______,
  __XX__X_,XX______,
  __X__X__,_X______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[20] = {
   {   1,   1,   0,  12,   3, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_0020 } /* code 0020, SPACE */
  ,{   3,   1,   1,   8,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  10,   3, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002E } /* code 002E, FULL STOP */
  ,{   5,  11,   0,   3,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_002F } /* code 002F, SOLIDUS */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_516C } /* code 516C */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5206 } /* code 5206 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5398 } /* code 5398 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_540B } /* code 540B */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5708 } /* code 5708 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_5C3A } /* code 5C3A */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_65A4 } /* code 65A4 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_725B } /* code 725B */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_78C5 } /* code 78C5 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_79D2 } /* code 79D2 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_7C73 } /* code 7C73 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_82F1 } /* code 82F1 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_9418 } /* code 9418 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_949F } /* code 949F */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_9813 } /* code 9813 */
  ,{  10,  11,   1,   2,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_987F } /* code 987F */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop18 = {
   0x987F /* first character */
  ,0x987F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 19] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop17 = {
   0x9813 /* first character */
  ,0x9813 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop16 = {
   0x949F /* first character */
  ,0x949F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop15 = {
   0x9418 /* first character */
  ,0x9418 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop14 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop13 = {
   0x7C73 /* first character */
  ,0x7C73 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop12 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop11 = {
   0x78C5 /* first character */
  ,0x78C5 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop10 = {
   0x725B /* first character */
  ,0x725B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop9 = {
   0x65A4 /* first character */
  ,0x65A4 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop8 = {
   0x5C3A /* first character */
  ,0x5C3A /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop7 = {
   0x5708 /* first character */
  ,0x5708 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop6 = {
   0x540B /* first character */
  ,0x540B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop5 = {
   0x5398 /* first character */
  ,0x5398 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop4 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop2 = {
   0x002D /* first character */
  ,0x002F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_16B_Prop1}
  ,12 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

