/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_JS_2_Step2_2_Microsoft JhengHei_22B.c         *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_JS_2_Step2_2_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_4E0A[ 30] = { /* code 4E0A */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,XXXXXX__,
  ______XX,XXXXXX__,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_4E0B[ 30] = { /* code 4E0B */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,X_______,
  ______XX,XX______,
  ______XX,_XXX____,
  ______XX,___XX___,
  ______XX,____X___,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_503C[ 30] = { /* code 503C */
  ___X____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __X_____,XX______,
  _XX__XXX,XXXXXX__,
  _XX__XXX,XXXXXX__,
  XXX__XX_,____XX__,
  XXX__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_507F[ 32] = { /* code 507F */
  __XX_X__,XX___X__,
  __XXXXX_,XX__XX__,
  __XX_XX_,XX_XX___,
  __X___X_,XX_XX___,
  _XX_XXXX,XXXXXXX_,
  _XX_XXXX,XXXXXXX_,
  XXX_X___,_____XX_,
  XXX_X_XX,XXXX_XX_,
  __X___XX,XXXX____,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  __X____X,X__X____,
  __X___XX,___XX___,
  __X__XX_,___XX___,
  __X_XXXX,XXXXXX__,
  __X_XXXX,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_511F[ 30] = { /* code 511F */
  __XX_XX_,XX__X___,
  __XX__XX,XX_XX___,
  __X_XXXX,XXXXXXX_,
  _XX_XXXX,___XXXX_,
  _XX___XX,XXXXX___,
  _XX_____,________,
  XXX__XXX,XXXXXX__,
  X_X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X___XX,__XXX___,
  __XXXXX_,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5173[ 30] = { /* code 5173 */
  ____XX__,XXX_____,
  ____XX__,XXX_____,
  ___XX___,__XX____,
  __XX____,___XX___,
  __X_XXXX,XXXXX___,
  _XX_XXXX,XXXXXX__,
  _X_____X,______X_,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,XX______,
  _____XX_,_XX_____,
  ___XXX__,___XX___,
  XXXXX___,____XX__,
  XXX_____,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_529B[ 30] = { /* code 529B */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ______XX,_____X__,
  ______XX,_____X__,
  ______X_,_____X__,
  ______X_,____XX__,
  _____XX_,____XX__,
  _____X__,____XX__,
  ____XX__,____XX__,
  ___XX___,____XX__,
  __XX____,XXXXXX__,
  _X______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ________,___XX___,
  ________,___X____,
  _______X,XXXX____,
  _______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5411[ 30] = { /* code 5411 */
  ____XX__,________,
  ___XX___,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X_______,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__XX___,XX__X___,
  X__XX___,XX__X___,
  X__XX___,XX__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X_______,____X___,
  X_______,_XXXX___,
  X_______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  _______X,X_______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __X___X_,___X____,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  __X___X_,___X____,
  __X___XX,XXXX____,
  __X___XX,XXXX____,
  __X_____,________,
  _XX_XXXX,XXXXX___,
  _XX_XXXX,XXXXX___,
  _XX__XXX,__XX____,
  XX_XXXXX,XXXXXXX_,
  _X_XXXX_,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5EF6[ 34] = { /* code 5EF6 */
  ________,_____X__,
  XXXXX___,_XXXXXX_,
  XXXXX_XX,XXXXX___,
  ___XX_XX,XXX_____,
  __XX____,__X_____,
  _XX___XX,__X_____,
  XXXXX_XX,__XXXXX_,
  XXXXX_XX,__XXXXX_,
  ___XX_XX,__X_____,
  XX_XX_XX,__X_____,
  _X_X__XX,__X_____,
  _XXX_XXX,XXXXXXX_,
  _XXX_XXX,XXXXXXX_,
  __XXX___,________,
  _XXXXXXX,XXXXXXX_,
  XX___XXX,XXXXXXX_,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5F00[ 30] = { /* code 5F00 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ___XX___,__X_____,
  ___XX___,__X_____,
  ___X____,__X_____,
  __XX____,__X_____,
  _XX_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_626D[ 30] = { /* code 626D */
  __XX__XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  XXXXXX__,XX__XX__,
  XXXXXX__,X___XX__,
  __XX____,X___XX__,
  __XX____,X___XX__,
  __XXX_XX,XXXXXXX_,
  _XXXX_XX,XXXXXXX_,
  XXXX____,X___X___,
  X_XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  XXXX_XXX,XXXXXXX_,
  _XXX_XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_65B9[ 32] = { /* code 65B9 */
  ______X_,________,
  ______XX,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____XX__,________,
  ____XX__,________,
  ____XXXX,XXXXX___,
  ____XXXX,XXXXX___,
  ____XX__,____X___,
  ____X___,___XX___,
  ___XX___,___XX___,
  __XXX___,___XX___,
  _XXX____,___XX___,
  XXX____X,XXXX____,
  _X______,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_65F6[ 30] = { /* code 65F6 */
  ________,___X____,
  XXXXX___,___X____,
  XXXXX___,___X____,
  X__XXXXX,XXXXXX__,
  X__XXXXX,XXXXXX__,
  X__XX___,___X____,
  XXXXX_XX,___X____,
  XXXXX__X,___X____,
  X__XX__X,X__X____,
  X__XX___,X__X____,
  X__XX___,X__X____,
  XXXXX___,___X____,
  XXXXX___,___X____,
  X__XX___,XXXX____,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6642[ 32] = { /* code 6642 */
  ________,_X______,
  XXXX_XXX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  X_XX____,_X______,
  X_XX____,_X______,
  X_XX_XXX,XXXXX___,
  XXXX_XXX,XXXXX___,
  XXXX____,________,
  X_XX____,___X____,
  X_XX_XXX,XXXXXX__,
  X_XX_XXX,XXXXXX__,
  X_XX__X_,___X____,
  XXXX__XX,___X____,
  XXXX___X,___X____,
  X_XX____,XXXX____,
  ________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6807[ 30] = { /* code 6807 */
  __XX__XX,XXXXXXX_,
  __XX__XX,XXXXXXX_,
  __XX____,________,
  XXXXXX__,________,
  XXXXXXXX,XXXXXXX_,
  __XXX_XX,XXXXXXX_,
  __XXXX_X,X_X_____,
  _XXX_X_X,X_X_X___,
  XXXX___X,__X_XX__,
  XXXX__XX,__X__X__,
  __XX__X_,__X__X__,
  __XX_XX_,__X__XX_,
  __XX_X__,__X__XX_,
  __XX___X,XXX___X_,
  __XX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_69DB[ 30] = { /* code 69DB */
  __XX____,X__X____,
  __XX_XX_,X__X____,
  __XX_XX_,X_XXXXX_,
  XXXXXXX_,X_XXXXX_,
  XXXXXXX_,X_X_____,
  __XX_XX_,XXX_X___,
  __XXXXX_,X__XXX__,
  _XXXXXX_,X_______,
  XXXX_XXX,XXXXXX__,
  X_XX_XXX,XXXXXX__,
  __XX_XX_,X_XX_X__,
  __XX_XX_,X_XX_X__,
  __XX_XX_,X_XX_X__,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6A19[ 30] = { /* code 6A19 */
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX____,XX_X____,
  XXXXX_XX,XXXXXXX_,
  XXXXX_X_,XX_X_XX_,
  __XX__XX,XXXXXXX_,
  _XXXX___,________,
  _XXXX_XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  __XX____,________,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX___X,_XX_X___,
  __XX__XX,XXX_XX__,
  __XX__X_,_XX__X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6ABB[ 30] = { /* code 6ABB */
  __X__XXX,XX_XX___,
  __X__X_X,X__X____,
  __X__XXX,XX_XXXX_,
  XXXX_X__,XXXXXXX_,
  XXXX_X__,XXX_____,
  _XXX_XXX,XX______,
  _XX_XX_X,X__XXXX_,
  _XX__XXX,XX_XXXX_,
  X_X__XXX,XX______,
  X_X__XXX,XXXXXX__,
  __X__XXX,XXXXXX__,
  __X__XX_,X_XX_X__,
  __X__XX_,X_XX_X__,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6B65[ 30] = { /* code 6B65 */
  _______X,X_______,
  ___X___X,X_______,
  ___X___X,XXXXXX__,
  ___X___X,XXXXXX__,
  ___X___X,X_______,
  ___X___X,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,X_______,
  ___XX__X,X___XX__,
  XXXXX__X,X__XXX__,
  _XX_____,__XXX___,
  _______X,XXXX____,
  _XXXXXXX,XX______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_70B9[ 32] = { /* code 70B9 */
  ______XX,________,
  ______XX,________,
  ______XX,XXXXXX__,
  ______XX,XXXXXX__,
  ______XX,________,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __X_____,____XX__,
  __X_____,____XX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  _XX__X__,XX__XX__,
  _XX__X__,_X__XX__,
  XX___XX_,_XX__XX_,
  XX___XX_,_XX___X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_76EE[ 30] = { /* code 76EE */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_7DE8[ 32] = { /* code 7DE8 */
  ___X____,____XXX_,
  __XX__XX,XXXX____,
  __X_XXXX,________,
  _XX_X_XX,XXXXXX__,
  _X__X_XX,_____X__,
  XXXXX_XX,_____X__,
  XXXX__XX,XXXXXX__,
  __XX__XX,________,
  __X_X_XX,XXXXXXX_,
  _X_XXXXX,X_X_XXX_,
  XXX__XXX,X_X_XXX_,
  ______XX,XXXXXXX_,
  _XXXX_X_,X_X_XXX_,
  _X_X_XX_,X_X_XXX_,
  XX_X_XX_,X_X_XXX_,
  X_______,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_7F16[ 32] = { /* code 7F16 */
  ___X____,_X______,
  __XX____,_XX_____,
  __X___XX,XXXXXX__,
  _XX___XX,XXXXXX__,
  _XX_X_X_,_____X__,
  XX_XXXXX,XXXXXX__,
  XXXXX_XX,XXXXXX__,
  XXXX__X_,XXXXXXX_,
  __XX__X_,XXXXXXX_,
  _XX_X_X_,X_X_XXX_,
  XX_XX_X_,X_X_XXX_,
  XXX___X_,XXXXXXX_,
  ___XXXX_,XXXXXXX_,
  _XXXXXX_,X_X_XXX_,
  XXXX_X__,X_X_XXX_,
  XX__XX__,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_865F[ 30] = { /* code 865F */
  _XXXXX__,_XX_____,
  _XXXXX__,_XXXXX__,
  _X__XX__,_XX_____,
  _XXXXX_X,XXXXXXX_,
  _XXXXX_X,__X__XX_,
  _______X,_XXXX___,
  XXXXXX_X,__X_____,
  _XX____X,__XXXXX_,
  _XXXX__X,________,
  _XXXX__X,_X_XX___,
  ____X_XX,_X_XX___,
  ____X_XX,_X_XX_X_,
  ____X_XX,_X_XX_X_,
  _XXXX_X_,XX_XXXX_,
  __XX_XXX,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8865[ 30] = { /* code 8865 */
  ___X____,_X______,
  ___XX___,_X______,
  ____X___,_X______,
  XXXXXXX_,_X______,
  XXXXXXX_,_X______,
  _____X__,_XX_____,
  ____X_X_,_XXX____,
  ___XX_X_,_X_XX___,
  _XXXXX__,_X___X__,
  XX_X_XX_,_X____X_,
  ___X__X_,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_88DC[ 30] = { /* code 88DC */
  _XX_____,_XX_XX__,
  __XX____,_XX__X__,
  __XX_XXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXX___,_XX_____,
  ___XX_XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  _XXXX_X_,_XX__X__,
  XXXXXXXX,XXXXXX__,
  __X_X_X_,_XX__X__,
  __X___XX,XXXXXX__,
  __X___XX,XXXXXX__,
  __X___X_,_XX__X__,
  __X___X_,_XX_XX__,
  __X___X_,_XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_89D2[ 32] = { /* code 89D2 */
  _____XX_,________,
  ____XXX_,________,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  _XXX____,_XX_____,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XX___X,X____X__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XX___X,X____X__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  _XX_____,_____X__,
  _XX_____,__XXXX__,
  _X______,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8F49[ 32] = { /* code 8F49 */
  ___X____,__X_____,
  ___X____,__X_____,
  XXXXXX_X,XXXXXXX_,
  XXXXXX_X,XXXXXXX_,
  ___X____,__X_____,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,XXXXXX__,
  _XXXXX__,__X_XX__,
  ___X__XX,XXXXXXX_,
  XXXXXX__,____X___,
  XXXXXX_X,XXXXXXX_,
  ___X____,X___X___,
  ___X____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8F6C[ 30] = { /* code 8F6C */
  __X_____,__X_____,
  __X_____,_XX_____,
  XXXXXX_X,XXXXXX__,
  XXXXXX_X,XXXXXX__,
  _XXX____,_X______,
  _X_X__XX,XXXXXXX_,
  _X_X__XX,XXXXXXX_,
  XXXXXX__,X_______,
  XXXXXX__,XXXXXX__,
  ___XXX__,XXXXXX__,
  XXXXXX__,X___XX__,
  XXXX____,XXXXX___,
  ___X____,__XX____,
  ___X____,___XX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8FDF[ 30] = { /* code 8FDF */
  _X______,________,
  __XX__XX,XXXXXX__,
  ___X__XX,XXXXXX__,
  ______XX,_____X__,
  XXXX__XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  __XX__XX,X_______,
  _XX___X_,XXX_____,
  XXXX__X_,__XX____,
  XXXX_XX_,___XX___,
  ___X_XX_,____XX__,
  __XXXX__,_____X__,
  _XXX____,________,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_901F[ 30] = { /* code 901F */
  _X______,_XX_____,
  __X__XXX,XXXXXXX_,
  ___X_XXX,XXXXXXX_,
  ________,_XX_____,
  XXXXX_XX,XXXXXX__,
  XXXXX_X_,_XX__X__,
  __XX__X_,_XX__X__,
  _XX___XX,XXXXXX__,
  XXXXX___,XXXX____,
  XXXXX__X,XXXXX___,
  ___X__XX,_XX_XX__,
  __XX_X__,_XX___X_,
  __XX____,________,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_904B[ 30] = { /* code 904B */
  _X___XXX,XXXXXXX_,
  _XXX_XX_,_XX__XX_,
  ___X_XXX,XXXXXXX_,
  XXXX____,_XX_____,
  XXXX_XXX,XXXXXX__,
  __XX_XX_,_XX__X__,
  _XX__XXX,XXXXXX__,
  XXXX_XX_,_XX__X__,
  XXXX_XXX,XXXXXX__,
  ___X____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX____,_XX_____,
  _XXXX___,________,
  XX__XXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9072[ 30] = { /* code 9072 */
  _X___XXX,XXXXXX__,
  _XX__X__,_____X__,
  __X__XXX,XXXXXX__,
  XXXX_X__,________,
  XXXX_X_X,__X__X__,
  __XX_X__,XXX_XX__,
  _XX__X_X,X_X__X__,
  XX___X__,X_X_____,
  XXXX_X_X,XXXXXX__,
  XXXX_XXX,__X_____,
  __XXXXXX,XXXXXXX_,
  __X_X___,__X_____,
  _XXXX___,__X_____,
  _X_XXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9580[ 30] = { /* code 9580 */
  XXXXXX_X,XXXXX___,
  XXXXXX_X,XXXXX___,
  X___XX_X,X___X___,
  XXXXXX_X,XXXXX___,
  XXXXXX_X,XXXXX___,
  X___XX_X,X___X___,
  XXXXXX_X,XXXXX___,
  XXXXXX_X,XXXXX___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,__XXX___,
  X_______,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_958B[ 30] = { /* code 958B */
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X_______,____XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___XX__,X___XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___X___,X___XX__,
  X__XX___,X___XX__,
  X__XX___,X_XXXX__,
  X__X____,X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9593[ 30] = { /* code 9593 */
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X_______,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__XX___,_X__X___,
  X__XXXXX,XX__X___,
  X__XX___,_X__X___,
  X__XX___,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX_XX___,
  X_______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95DC[ 30] = { /* code 95DC */
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X__XX___,X___X___,
  X__X_X_X,_XX_X___,
  X_XXX__X,X___X___,
  X_XXXX_X,XXX_X___,
  X_______,___XX___,
  X_X__X_X,__X_X___,
  X_XXXX_X,XXX_X___,
  X___XX_X,____X___,
  X__XX__X,__XXX___,
  X_XX___X,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95E8[ 30] = { /* code 95E8 */
  X_______,________,
  XX__XXXX,XXXXX___,
  _XX_XXXX,XXXXX___,
  __X_____,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,__XXX___,
  X_______,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95F4[ 32] = { /* code 95F4 */
  X_______,________,
  XX__XXXX,XXXXX___,
  _XX_XXXX,XXXXX___,
  __X_____,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__X____,_X__X___,
  X__X____,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__X____,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X_______,____X___,
  X_______,__XXX___,
  X_______,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_964D[ 30] = { /* code 964D */
  XXXX___X,X_______,
  XXXX___X,XXXXX___,
  X__X__XX,XXXXX___,
  X_XX_XXX,___XX___,
  X_XXXX_X,XXX_____,
  X_X____X,XXXX____,
  X_XX_XX_,___XXX__,
  X__X____,_X______,
  X__X_XXX,XXXXX___,
  X__X_XXX,XXXXX___,
  XXXXX_X_,_X______,
  X_XX__XX,XXXXXX__,
  X____XXX,XXXXXX__,
  X_______,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9650[ 30] = { /* code 9650 */
  XXXXX_XX,XXXXX___,
  XXXXX_XX,XXXXX___,
  X__X__X_,____X___,
  X_XX__XX,XXXXX___,
  X_XX__XX,XXXXX___,
  X_X___X_,____X___,
  X_XX__XX,XXXXX___,
  X__X__XX,XXXXX___,
  X__XX_X_,________,
  X__XX_X_,XX__X___,
  XXXXX_X_,_X_XX___,
  X_XX__X_,_XXX____,
  X_____X_,XXXX____,
  X_____XX,XX_XX___,
  X_____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9A5F[ 30] = { /* code 9A5F */
  _XXXX_XX,XX_XXXX_,
  _X_X__XX,_X_X_XX_,
  _XXXX_XX,XX_XXX__,
  _X_X__XX,_X__XX__,
  _XXXX_XX,XX__XX__,
  _X_X__XX,_X_XXXX_,
  _X_X__XX,XXXX__X_,
  _XXXXX__,_X_XXX__,
  _____X_X,XXX_____,
  _X___X__,X_X__X__,
  XXXX_X_X,X_X__X__,
  X_XX_X_X,X_X_XX__,
  X_XX_X_X,X_X_XX__,
  X_XXXXXX,XXX_X_X_,
  ___XX_X_,__X_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9AA4[ 32] = { /* code 9AA4 */
  XXXXX_XX,XX_XXXX_,
  XXXXX_X_,XX_XXXX_,
  ____X_XX,XX_X_X__,
  _X_XX_X_,XXXXXX__,
  _X_XX_XX,XX__XX__,
  _X_XX_X_,XX__XX__,
  _X_XX_X_,XX_X_XX_,
  _XXXX_XX,XXXX__X_,
  XXXXX___,___XXX__,
  ____X_XX,XXXXX_X_,
  __X_X___,X_XXXXX_,
  XXX_X__X,__X_XX__,
  XX__XXX_,__X_XX__,
  ____X__X,X_X__XX_,
  __XXXXXX,__X___X_,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9EDE[ 30] = { /* code 9EDE */
  _XXXXXX_,__XX____,
  _X_XX_X_,__XX____,
  _XXXXXX_,__XXXXX_,
  _XXXXXX_,__XXXXX_,
  _XXXXXX_,__XX____,
  _XXXXXX_,__XX____,
  ___XX___,XXXXXX__,
  _XXXXXX_,XXXXXX__,
  ___XX___,XX___X__,
  ___XX___,XX___X__,
  XXXXXXXX,XX___X__,
  ________,XX___X__,
  _XXXX_X_,XXXXXX__,
  XX_XXXXX,XXXXXX__,
  X__X_X__,XX___X__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[47] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_4E0A } /* code 4E0A */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_4E0B } /* code 4E0B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_503C } /* code 503C */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_507F } /* code 507F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_511F } /* code 511F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5173 } /* code 5173 */
  ,{  14,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_529B } /* code 529B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_53F7 } /* code 53F7 */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5411 } /* code 5411 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5EA6 } /* code 5EA6 */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5EF6 } /* code 5EF6 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_5F00 } /* code 5F00 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_626D } /* code 626D */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_65B9 } /* code 65B9 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_65F6 } /* code 65F6 */
  ,{  14,  16,   2,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6642 } /* code 6642 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6807 } /* code 6807 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_69DB } /* code 69DB */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6A19 } /* code 6A19 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6ABB } /* code 6ABB */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_6B65 } /* code 6B65 */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_70B9 } /* code 70B9 */
  ,{  11,  15,   3,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_76EE } /* code 76EE */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_7DE8 } /* code 7DE8 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_7F16 } /* code 7F16 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_865F } /* code 865F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8865 } /* code 8865 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_88DC } /* code 88DC */
  ,{  14,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_89D2 } /* code 89D2 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8F49 } /* code 8F49 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8F6C } /* code 8F6C */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_8FDF } /* code 8FDF */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_901F } /* code 901F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_904B } /* code 904B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9072 } /* code 9072 */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9580 } /* code 9580 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_958B } /* code 958B */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9593 } /* code 9593 */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95DC } /* code 95DC */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95E8 } /* code 95E8 */
  ,{  13,  16,   2,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_95F4 } /* code 95F4 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_964D } /* code 964D */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9650 } /* code 9650 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9A5F } /* code 9A5F */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9AA4 } /* code 9AA4 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_9EDE } /* code 9EDE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop46 = {
   0x9EDE /* first character */
  ,0x9EDE /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 46] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop45 = {
   0x9AA4 /* first character */
  ,0x9AA4 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 45] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop44 = {
   0x9A5F /* first character */
  ,0x9A5F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 44] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop43 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 43] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop42 = {
   0x964D /* first character */
  ,0x964D /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 42] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop41 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 41] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop40 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 40] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop39 = {
   0x95DC /* first character */
  ,0x95DC /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 39] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop38 = {
   0x9593 /* first character */
  ,0x9593 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop37 = {
   0x958B /* first character */
  ,0x958B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop36 = {
   0x9580 /* first character */
  ,0x9580 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 36] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop35 = {
   0x9072 /* first character */
  ,0x9072 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 35] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop34 = {
   0x904B /* first character */
  ,0x904B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 34] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop33 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 33] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop32 = {
   0x8FDF /* first character */
  ,0x8FDF /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 32] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop31 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop30 = {
   0x8F49 /* first character */
  ,0x8F49 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop29 = {
   0x89D2 /* first character */
  ,0x89D2 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop28 = {
   0x88DC /* first character */
  ,0x88DC /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop27 = {
   0x8865 /* first character */
  ,0x8865 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop26 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop25 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop24 = {
   0x7DE8 /* first character */
  ,0x7DE8 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop23 = {
   0x76EE /* first character */
  ,0x76EE /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop22 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop21 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop20 = {
   0x6ABB /* first character */
  ,0x6ABB /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop19 = {
   0x6A19 /* first character */
  ,0x6A19 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop18 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop17 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop16 = {
   0x6642 /* first character */
  ,0x6642 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop15 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop14 = {
   0x65B9 /* first character */
  ,0x65B9 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop13 = {
   0x626D /* first character */
  ,0x626D /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop12 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop11 = {
   0x5EF6 /* first character */
  ,0x5EF6 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop10 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop9 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop8 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop7 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop6 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop5 = {
   0x511F /* first character */
  ,0x511F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop4 = {
   0x507F /* first character */
  ,0x507F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop3 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop2 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_JS_2_Step2_2_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

