/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Home_Microsoft JhengHei_20B.c                 *
* Font:        微軟正黑體                                            *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--字庫導入910a\20250707-字庫檔案\最後\Font_Pg_Home_Microsoft JhengHei_20B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_0020[  1] = { /* code 0020, SPACE */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_4F5C[ 26] = { /* code 4F5C */
  ___X__XX,________,
  __XX__X_,________,
  __X__XXX,XXXXX___,
  _XX__X_X,________,
  XXX_XX_X,________,
  X_XXX__X,XXXXX___,
  __X____X,________,
  __X____X,________,
  __X____X,XXXXX___,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __X____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_529B[ 26] = { /* code 529B */
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _XXXXXXX,XXXX____,
  _____XX_,___X____,
  _____X__,___X____,
  _____X__,___X____,
  _____X__,___X____,
  ____XX__,___X____,
  ____X___,___X____,
  ___X____,___X____,
  _XX_____,___X____,
  XX_____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5DE5[ 24] = { /* code 5DE5 */
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5E8F[ 26] = { /* code 5E8F */
  ______X_,________,
  _XXXXXXX,XXXXX___,
  _XX_____,________,
  _XXXXXXX,XXXX____,
  _XX_____,_XX_____,
  _XX__XXX,XX______,
  _XX___XX,X_______,
  _XXXXXXX,XXXXX___,
  _X_____X,X__XX___,
  _X_____X,X__X____,
  _X_____X,X_XX____,
  XX_____X,X_______,
  X____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5EA6[ 26] = { /* code 5EA6 */
  ______X_,________,
  _XXXXXXX,XXXXX___,
  _XX_____,________,
  _XX__X__,_XX_____,
  _XXXXXXX,XXXXX___,
  _XX__X__,_XX_____,
  _XX__XXX,XXX_____,
  _XX_____,________,
  _XX_XXXX,XXX_____,
  _X___X__,_XX_____,
  _X___XX_,XX______,
  XX___XXX,XX______,
  X__XXX__,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_626D[ 24] = { /* code 626D */
  __X__XXX,XXXX____,
  __X____X,___X____,
  XXXXX__X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __XX_XXX,XXXXX___,
  _XX____X,__XX____,
  X_X___XX,__XX____,
  __X___XX,__XX____,
  __X___XX,__XX____,
  __X___XX,__XX____,
  XXX_XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6570[ 26] = { /* code 6570 */
  _X_X_XX_,_X______,
  _XXX_X__,XX______,
  XXXXXXX_,XXXXX___,
  _X_X_X__,X__X____,
  XXXX__XX,X__X____,
  X__X___X,___X____,
  __XX_X__,X_XX____,
  XXXXXXX_,X_X_____,
  _XX_XX__,_XX_____,
  _XX_X___,_XX_____,
  __XXX___,XXX_____,
  _XXX_X_X,X__X____,
  XX____XX,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6578[ 26] = { /* code 6578 */
  ___XX___,_XX_____,
  _XXXXXX_,_X______,
  _X_XX_X_,_XXXX___,
  XXXXXXXX,_X_X____,
  _X_XX_X_,X__X____,
  _XXXXXX_,X__X____,
  _X_XX_X_,X__X____,
  _XXXXXX_,_X_X____,
  ___X_XX_,_XXX____,
  XXXXXXXX,_XX_____,
  _XX_XX__,_XX_____,
  ___XXX__,XX_X____,
  XXX___XX,X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6B65[ 26] = { /* code 6B65 */
  ______X_,________,
  __X___X_,________,
  __X___XX,XXXX____,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,XXXXX___,
  ______X_,________,
  ___XX_X_,___X____,
  __XX__X_,__XX____,
  XX______,_XX_____,
  ______XX,X_______,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_89D2[ 26] = { /* code 89D2 */
  ____XX__,________,
  ___XXX__,________,
  __XXXXXX,XX______,
  _XXX____,XX______,
  XXXXXXXX,XXXXX___,
  __X___XX,___XX___,
  __X___XX,___XX___,
  __XXXXXX,XXXXX___,
  __X___XX,___XX___,
  __X___XX,___XX___,
  _XXXXXXX,XXXXX___,
  _XX_____,___XX___,
  _X______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_8F49[ 26] = { /* code 8F49 */
  __X_____,_X______,
  XXXXX_XX,XXXXX___,
  __X___X_,_X_X____,
  XXXXX_XX,XXXX____,
  XXX_X_X_,_X_X____,
  XXXXX_XX,XXXX____,
  XXX_X___,_X_X____,
  XXXXX___,_X_XX___,
  __X___XX,XXXXX___,
  XXXXX___,__XX____,
  __X___XX,XXXXX___,
  __X____X,__XX____,
  __X____X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_8F6C[ 26] = { /* code 8F6C */
  __X_____,XX______,
  _XX_____,X_______,
  XXXXXXXX,XXXXX___,
  _X______,X_______,
  _XXX___X,X_______,
  _XXX_XXX,XXXXX___,
  XXXX___X,________,
  XXXXX__X,________,
  __XX___X,XXXX____,
  __XXXX__,__XX____,
  XXXX___X,XXX_____,
  __XX____,XX______,
  __XX____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_901F[ 26] = { /* code 901F */
  _X______,X_______,
  _XX_XXXX,XXXXX___,
  __XX____,X_______,
  XXXX_XXX,XXXXX___,
  __XX_X__,X__XX___,
  _XX__X__,X__XX___,
  _X___XXX,XXXXX___,
  XXXX___X,X_______,
  __XX__XX,XXX_____,
  __X__XX_,X_XX____,
  _XX_XX__,X___X___,
  _X_XX___,________,
  XX__XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9846[ 26] = { /* code 9846 */
  _XXXXX_X,XXXXX___,
  _X_X_X__,_XX_____,
  _XXXXX__,_XX_____,
  _X_X_X_X,XXXX____,
  _X_X_X_X,___X____,
  _XXXXX_X,XXXX____,
  ___X___X,___X____,
  XXXXXXXX,XXXX____,
  __XX___X,___X____,
  _X_XXX_X,XXXX____,
  _X_X__X_,X_X_____,
  X__X___X,XX_XX___,
  ___X__XX,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9897[ 26] = { /* code 9897 */
  _XXXXX_X,XXXXX___,
  _X_X_X__,_XX_____,
  _XXXXX__,_X______,
  _X_X_X_X,XXXXX___,
  _X_X_X_X,____X___,
  _XXXXX_X,_XX_X___,
  ___X___X,_XX_X___,
  XXXXXXXX,_XX_X___,
  __XX_X_X,_X__X___,
  __XXXX_X,_X__X___,
  _X_X_XX_,XXXX____,
  _X_X__XX,X__XX___,
  X__X__XX,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9A5F[ 26] = { /* code 9A5F */
  _XXXXXXX,X_XXX___,
  _X_X__X_,X_XXX___,
  _XXXX_XX,XXXX____,
  _X_X__X_,X__X____,
  _XXXX_X_,X_XXX___,
  _X_X_XXX,XX__X___,
  _XXXX___,X_XX____,
  ____X_XX,XX______,
  XXXXX__X,_X_X____,
  XXXXX_XX,_X_X____,
  X_XXX_XX,_X_X____,
  XX__X_XX,_XXXX___,
  __XXXX__,XXX_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9AA4[ 26] = { /* code 9AA4 */
  XXXX_XXX,XXXXX___,
  _X_X_X_X,X__XX___,
  _X_X_XXX,XX_X____,
  XX_X_XXX,X_XX____,
  XX_X_X_X,X_XX____,
  XX_X_X_X,X_XXX___,
  XXXXXXXX,XX__X___,
  ___XX___,__XX____,
  ___XXXXX,XXX_X___,
  _XXX__XX,XXXX____,
  XX_X_XX_,XX_X____,
  ___X__XX,XX_XX___,
  __XX_XX_,XX__X___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[18] = {
   {   1,   1,   0,  15,   4, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_0020 } /* code 0020, SPACE */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_4F5C } /* code 4F5C */
  ,{  12,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_529B } /* code 529B */
  ,{  13,  12,   1,   4,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5DE5 } /* code 5DE5 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5E8F } /* code 5E8F */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_5EA6 } /* code 5EA6 */
  ,{  13,  12,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_626D } /* code 626D */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6570 } /* code 6570 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6578 } /* code 6578 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_6B65 } /* code 6B65 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_89D2 } /* code 89D2 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_8F49 } /* code 8F49 */
  ,{  13,  13,   1,   2,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_8F6C } /* code 8F6C */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_901F } /* code 901F */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9846 } /* code 9846 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9897 } /* code 9897 */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9A5F } /* code 9A5F */
  ,{  13,  13,   1,   3,  15, acGUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_9AA4 } /* code 9AA4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop18 = {
   0x9AA4 /* first character */
  ,0x9AA4 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 17] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop17 = {
   0x9A5F /* first character */
  ,0x9A5F /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop16 = {
   0x9897 /* first character */
  ,0x9897 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop15 = {
   0x9846 /* first character */
  ,0x9846 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop14 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop13 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop12 = {
   0x8F49 /* first character */
  ,0x8F49 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop11 = {
   0x89D2 /* first character */
  ,0x89D2 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop10 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop9 = {
   0x6578 /* first character */
  ,0x6578 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop8 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop7 = {
   0x626D /* first character */
  ,0x626D /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop6 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop5 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop4 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop3 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop2 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Home_MicrosoftJhengHei_20B_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

