/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Tool_Mode_Microsoft JhengHei_22B.c            *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260105-全部頁面字庫分門別類ab8f-檔案和註解整理乾淨的\01-20250105-字庫檔案\最後\Font_Pg_Tool_Mode_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXX_____,
  _XX_____,
  _XX_____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  __XX____,
  __XX____,
  _XX_____,
  XX______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5177[ 30] = { /* code 5177 */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____X___,__XX____,
  _XXXX___,___XXX__,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5355[ 32] = { /* code 5355 */
  ___XX___,___X____,
  ____XX__,__XX____,
  ____XX__,_XX_____,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __X____X,____XX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __X____X,____XX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_55AE[ 30] = { /* code 55AE */
  _XXXXXX_,XXXXXX__,
  _XX__XX_,XX__XX__,
  _XX__XX_,XX__XX__,
  _XXXXXX_,XXXXXX__,
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_591A[ 30] = { /* code 591A */
  ______XX,________,
  _____XXX,XXXXX___,
  ___XXXXX,XXXXX___,
  __XXXX__,__XX____,
  _XX__XX_,_XX_____,
  ______XX,XX______,
  ____XXXX,_XX_____,
  XXXXXX__,XXXXXXX_,
  _XX____X,XXXXXXX_,
  _____XXX,_____X__,
  ___XXXXX,___XX___,
  __XX____,XXXX____,
  ______XX,XXX_____,
  _XXXXXXX,X_______,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5DE5[ 28] = { /* code 5DE5 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_63A7[ 32] = { /* code 63A7 */
  __XX____,XX______,
  __XX____,_XX_____,
  __XX_XXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXX_,XX_X_XX_,
  __XX____,X__X____,
  __XXX__X,X__XXXX_,
  __XXX_XX,___XXXX_,
  _XXX_X__,________,
  XXXX__XX,XXXXXXX_,
  X_XX__XX,XXXXXXX_,
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  XXXX_XXX,XXXXXXX_,
  _XX__XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_65E0[ 30] = { /* code 65E0 */
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____XX_,X_______,
  _____XX_,X_____X_,
  ____XX__,X_____X_,
  ___XX___,X____XX_,
  __XX____,XXXXXXX_,
  XX______,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_673A[ 30] = { /* code 673A */
  ___X___X,XXXXX___,
  ___X___X,XXXXX___,
  ___X___X,X__XX___,
  XXXXXXXX,X__XX___,
  XXXXXXXX,X__XX___,
  __XXX__X,X__XX___,
  __XXXX_X,X__XX___,
  _XXX_XXX,X__XX___,
  XX_X_X_X,X__XX___,
  XX_X___X,X__XX___,
  ___X___X,X__XX_X_,
  ___X___X,___XX_X_,
  ___X___X,___XX_X_,
  ___X__XX,___XXXX_,
  ___X__X_,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_6A5F[ 32] = { /* code 6A5F */
  __X___X_,_X__X___,
  __X__XX_,_X__X___,
  __X__X_X,_X_X_XX_,
  XXXX_XXX,XX_XXX__,
  XXXX__XX,_X__XX__,
  _XXX_X_X,XX_XXXX_,
  _XXX_XX_,XX_X__X_,
  _XXXX___,_XXXX___,
  _XX_XXXX,XXXXXXX_,
  X_X_XXXX,XXXXXXX_,
  X_X___X_,__X_X___,
  X_X__XXX,__X_X___,
  __X__XXX,X_XXX___,
  __X__XX_,X_XX__X_,
  __X_XX__,XX_XXXX_,
  __X_X__X,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7121[ 32] = { /* code 7121 */
  ___XX___,________,
  ___XX___,________,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  _XX_____,________,
  XXXX_XX_,_X__X___,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  __XX_XX_,_X__X___,
  __XX_XX_,_X__X___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  __X__X__,XX__XX__,
  _XX__XX_,_XX__X__,
  XX___XX_,_XX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7DB2[ 30] = { /* code 7DB2 */
  ___X__XX,XXXXXXX_,
  __XX__XX,XXXXXXX_,
  _XX_XXXX,XX_XXXX_,
  _X__XXXX,_X_X_XX_,
  XXXXX_XX,XXXXXXX_,
  XXXX__XX,XXXXXXX_,
  __XX__XX,__X__XX_,
  _XX_X_XX,XXXXXXX_,
  _X_XXXXX,XXXXXXX_,
  XXX__XXX,_X___XX_,
  ______XX,_X___XX_,
  _X_XX_XX,_XXX_XX_,
  _X_X_XXX,_XXX_XX_,
  XX_X_XXX,___XXXX_,
  XX____XX,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7DDA[ 32] = { /* code 7DDA */
  ___XX___,_XX_____,
  ___X____,_XX_____,
  __XX___X,XXXXXX__,
  __X__X_X,_____X__,
  _XX_XX_X,XXXXXX__,
  _XXXX__X,_____X__,
  XXXXX__X,XXXXXX__,
  ___X____,__X_____,
  __X_X_XX,X_X__X__,
  _X_XXX__,X_XXXX__,
  XXX__X__,X_XXX___,
  _______X,X_XXX___,
  _X_X_X_X,__X_XX__,
  _X_X__XX,__X__X__,
  XX_XXXX_,XXX___X_,
  X_______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7EBF[ 30] = { /* code 7EBF */
  ___X____,_X_XX___,
  __XX____,_X__X___,
  __XX_X__,_XXXXX__,
  _XX_XXXX,XXXXXX__,
  _X_XX_XX,XX______,
  XXXXX___,_X______,
  ___X____,_XXXXXX_,
  __XX__XX,XXXXXXX_,
  _XX__XXX,XX______,
  XX_XXX__,_XX__X__,
  _XX_____,_XX_X___,
  _____X__,__XX__X_,
  __XXXX__,_XXX_XX_,
  XXXXX__X,XX_XXXX_,
  XX___XX_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7F51[ 30] = { /* code 7F51 */
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X_______,____X___,
  X____X__,_XX_X___,
  X_X__X_X,_XX_X___,
  X_XXXXXX,XX__X___,
  X__XXX__,XX__X___,
  X___X___,XX__X___,
  X__XXX__,XXX_X___,
  X__XXXX_,XXX_X___,
  X__X_X_X,X_XXX___,
  X_XX___X,____X___,
  X_XX___X,____X___,
  X_X_____,_XXXX___,
  X_______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_88AB[ 32] = { /* code 88AB */
  __X_____,__X_____,
  __XX____,__X_____,
  __XX___X,XXXXXXX_,
  XXXXX__X,XXXXXXX_,
  XXXXX__X,__X__X__,
  ___XX__X,__X_XX__,
  ___XX__X,__X_____,
  __XX_X_X,XXXXXX__,
  _XXXXX_X,XXXXXX__,
  XXXXX__X,XX__XX__,
  __XX_X_X,_X__X___,
  __XX__XX,_XXXX___,
  __XX__XX,__XX____,
  __XX__X_,_XXXX___,
  __XX_XX_,XX__XX__,
  __XXXX_X,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_8DEF[ 32] = { /* code 8DEF */
  ________,________,
  _XXXXX__,_X______,
  _XXXXX__,XXXXXX__,
  _X__XX__,XXXXXX__,
  _X__XX_X,X___XX__,
  _XXXXXX_,XXXXX___,
  _XXXXX__,XXXX____,
  ___X__XX,XX_XXXX_,
  _X_X__XX,_____XX_,
  _X_XXX_X,XXXXXX__,
  _X_XXX_X,XXXXXX__,
  _X_X___X,X____X__,
  _X_X_X_X,X____X__,
  _XXXXX_X,XXXXXX__,
  XXXXXX_X,XXXXXX__,
  XX_____X,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_8FDE[ 30] = { /* code 8FDE */
  _X______,X_______,
  _XX____X,X_______,
  __XX_XXX,XXXXXXX_,
  _____XXX,XXXXXXX_,
  ______XX,_X______,
  XXXX__X_,_X______,
  XXXX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX____,_X______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __XX____,_X______,
  _X_XXX__,_X______,
  _X__XXXX,XXXXXXX_,
  X_____XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_9023[ 32] = { /* code 9023 */
  _X______,_XX_____,
  __XX_XXX,XXXXXXX_,
  ___X_XXX,XXXXXXX_,
  ________,_XX_____,
  XXXX_XXX,XXXXXX__,
  XXXX_XX_,_XX__X__,
  __XX_XXX,XXXXXX__,
  _XX__XX_,_XX__X__,
  XXXX_XXX,XXXXXX__,
  XXXX____,_XX_____,
  ___X_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __X_____,_XX_____,
  _XXXX___,________,
  XX_XXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[21] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{   5,  16,   1,   4,   6, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  16,   0,   4,   6, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5177 } /* code 5177 */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5355 } /* code 5355 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_55AE } /* code 55AE */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_591A } /* code 591A */
  ,{  15,  14,   1,   4,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_5DE5 } /* code 5DE5 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_63A7 } /* code 63A7 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_65E0 } /* code 65E0 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_673A } /* code 673A */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_6A5F } /* code 6A5F */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7121 } /* code 7121 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7DB2 } /* code 7DB2 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7DDA } /* code 7DDA */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7EBF } /* code 7EBF */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_7F51 } /* code 7F51 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_88AB } /* code 88AB */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_8DEF } /* code 8DEF */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_8FDE } /* code 8FDE */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_9023 } /* code 9023 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop20 = {
   0x9023 /* first character */
  ,0x9023 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 20] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop19 = {
   0x8FDE /* first character */
  ,0x8FDE /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop18 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop17 = {
   0x88AB /* first character */
  ,0x88AB /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop16 = {
   0x7F51 /* first character */
  ,0x7F51 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop15 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop14 = {
   0x7DDA /* first character */
  ,0x7DDA /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop13 = {
   0x7DB2 /* first character */
  ,0x7DB2 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop12 = {
   0x7121 /* first character */
  ,0x7121 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop11 = {
   0x6A5F /* first character */
  ,0x6A5F /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop10 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop9 = {
   0x65E0 /* first character */
  ,0x65E0 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop8 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop7 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop6 = {
   0x591A /* first character */
  ,0x591A /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop5 = {
   0x55AE /* first character */
  ,0x55AE /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop4 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop3 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop2 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

