/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_ALLPage_WinTitle_DFKai-SB_16B.c                  *
* Font:        標楷體                                                *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_ALLPage_WinTitle_DFKai-SB_16B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0021[ 12] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0022[  4] = { /* code 0022, QUOTATION MARK */
  XXXX____,
  XXXX____,
  XXXX____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0023[ 13] = { /* code 0023, NUMBER SIGN */
  __XX____,
  __XXXX__,
  __XXXX__,
  XXXXXXX_,
  XXXXXXX_,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  XXXXXXX_,
  XXXXXXX_,
  _XXXX___,
  _XXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0024[ 14] = { /* code 0024, DOLLAR SIGN */
  ________,
  _XXXXX__,
  XXXX_XX_,
  XXXX_XX_,
  XXXX____,
  XXXX____,
  __XXX___,
  ___XXX__,
  __XX_XX_,
  XXXX_XX_,
  XXXX_XX_,
  XXXX_XX_,
  _XXXXX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0025[ 24] = { /* code 0025, PERCENT SIGN */
  _XXX__XX,________,
  XX_XX_XX,________,
  XX_XXXX_,________,
  XX_XXXX_,________,
  XX_XXX__,________,
  _XXXX___,________,
  ___XXXXX,________,
  __XXXX_X,X_______,
  __XXXX_X,X_______,
  _XX_XX_X,X_______,
  XX__XXXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0026[ 24] = { /* code 0026, AMPERSAND */
  __XXXX__,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  __XXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  XXX_XXXX,________,
  XXX_XXX_,________,
  _XX__XXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0027[  4] = { /* code 0027, APOSTROPHE */
  XX______,
  XXX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  _XX_____,
  __XX____,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002A[ 10] = { /* code 002A, ASTERISK */
  ________,
  ___XX___,
  XXXX_XXX,
  XXXX_XX_,
  __XXXX__,
  ___XX___,
  _XXXXX__,
  XXXX_XX_,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002B[ 10] = { /* code 002B, PLUS SIGN */
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXXX_,
  __XX____,
  __XX____,
  __XX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002C[  5] = { /* code 002C, COMMA */
  XX______,
  XXX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002E[  2] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002F[ 12] = { /* code 002F, SOLIDUS */
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0030[ 12] = { /* code 0030, DIGIT ZERO */
  _XXXXX__,
  _XX_XX__,
  XX__XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX__XXX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0031[ 12] = { /* code 0031, DIGIT ONE */
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0032[ 12] = { /* code 0032, DIGIT TWO */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXX__XX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX___XX_,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0033[ 12] = { /* code 0033, DIGIT THREE */
  _XXXXX__,
  XX__XXX_,
  XXX__XX_,
  ____XXX_,
  ____XX__,
  __XXXX__,
  ____XXX_,
  _____XX_,
  XXX__XX_,
  XX___XX_,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ____XX__,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  _XX_XX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  XXXXXXX_,
  ____XX__,
  ____XX__,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0035[ 12] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XX__XXX_,
  _____XX_,
  _____XX_,
  XX___XX_,
  XX__XXX_,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0036[ 12] = { /* code 0036, DIGIT SIX */
  _XXXXX__,
  _XX_XX__,
  XX__XX__,
  XX______,
  XXXXXX__,
  XXX_XXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXX__XX_,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  XXXXXXX_,
  XX___XX_,
  XX__XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  __XXX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  _XXXXX__,
  XX__XXX_,
  XX___XX_,
  XXX_XXX_,
  _XXXXX__,
  __XXX___,
  XXX_XX__,
  XX__XXX_,
  XX___XX_,
  XX___XX_,
  XXX_XXX_,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0039[ 12] = { /* code 0039, DIGIT NINE */
  _XXXXX__,
  XXX_XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXXX_,
  __XX_XX_,
  _____XX_,
  XXX_XXX_,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003A[  8] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003B[ 10] = { /* code 003B, SEMICOLON */
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  XX______,
  XXX_____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003C[ 11] = { /* code 003C, LESS-THAN SIGN */
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  _XX_____,
  __XX____,
  ___XXX__,
  _____XX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003E[ 11] = { /* code 003E, GREATER-THAN SIGN */
  XX______,
  _XX_____,
  __XX____,
  ___XX___,
  ____XXX_,
  _____XX_,
  ____XX__,
  ___XX___,
  _XXX____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003F[ 12] = { /* code 003F, QUESTION MARK */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  ________,
  __XXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0040[ 26] = { /* code 0040, COMMERCIAL AT */
  __XXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXXX,________,
  XX_XXXXX,________,
  XXXX_XXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  _XX___XX,________,
  _XXX_XX_,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0041[ 24] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___XXX__,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXX_,________,
  __XX_XX_,________,
  _XXXXXX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  _XX__XXX,________,
  XXX__XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0042[ 24] = { /* code 0042, LATIN CAPITAL LETTER B */
  _XXXXXX_,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX_XX_,________,
  _XXXXX__,________,
  _XXX_XXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,________,
  _XXX_XXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0043[ 24] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXXXX,________,
  _XX___XX,________,
  _XX_____,________,
  _XX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  _XX_____,________,
  _XX____X,X_______,
  _XX___XX,________,
  __XX__XX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0044[ 24] = { /* code 0044, LATIN CAPITAL LETTER D */
  _XXXXX__,________,
  _XXX_XX_,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX_XX_,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0045[ 24] = { /* code 0045, LATIN CAPITAL LETTER E */
  _XXXXXXX,________,
  _XXX__XX,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXX____,________,
  _XXX___X,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  _XXXXXXX,
  _XXX__XX,
  _XXX____,
  _XXX____,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0047[ 24] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXXXX,________,
  _XX___XX,________,
  _XX_____,________,
  _XX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_XXXX,X_______,
  _XX__XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  __XX_XXX,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0048[ 24] = { /* code 0048, LATIN CAPITAL LETTER H */
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXXXXXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  XX_XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004B[ 24] = { /* code 004B, LATIN CAPITAL LETTER K */
  _XXX_XX_,________,
  _XXX_XX_,________,
  _XXXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXX_XX_,________,
  _XXX_XX_,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004C[ 24] = { /* code 004C, LATIN CAPITAL LETTER L */
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004D[ 24] = { /* code 004D, LATIN CAPITAL LETTER M */
  _XX__XXX,________,
  _XX__XXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  XXX__XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004E[ 12] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX__XX_,
  XXX__XX_,
  XXX__XX_,
  XXXX_XX_,
  XXXX_XX_,
  XX_XXXX_,
  XX_XXXX_,
  XX_XXXX_,
  XX__XXX_,
  XX__XXX_,
  XX___XX_,
  XXX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004F[ 24] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0050[ 24] = { /* code 0050, LATIN CAPITAL LETTER P */
  _XXXXXX_,________,
  _XXX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,________,
  _XXXXXX_,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0051[ 26] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,________,
  _XXXX_XX,________,
  _XXXXXXX,________,
  __XXXXX_,________,
  ___XXXX_,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0052[ 24] = { /* code 0052, LATIN CAPITAL LETTER R */
  _XXXXXX_,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  _XXX_XX_,________,
  _XXX_XX_,________,
  XXXXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0053[ 24] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXXX,________,
  _XX___XX,________,
  _XX_____,________,
  _XX_____,________,
  __XXX___,________,
  ___XXX__,________,
  ____XXXX,________,
  ______XX,________,
  XX____XX,X_______,
  _XX___XX,X_______,
  _XXX__XX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0054[ 24] = { /* code 0054, LATIN CAPITAL LETTER T */
  _XXXXXXX,________,
  XX_XXX_X,X_______,
  XX_XXX_X,X_______,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0055[ 24] = { /* code 0055, LATIN CAPITAL LETTER U */
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXX__XX,________,
  __XX_XX_,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0056[ 24] = { /* code 0056, LATIN CAPITAL LETTER V */
  _XXX__XX,________,
  __XX__XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0057[ 24] = { /* code 0057, LATIN CAPITAL LETTER W */
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XXXXXX_,________,
  __XXXXX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0058[ 24] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXX__XX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXX__,________,
  __XX_XX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0059[ 24] = { /* code 0059, LATIN CAPITAL LETTER Y */
  _XX___XX,________,
  _XXX__XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005A[ 12] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXX_,
  XX___XX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XX__XX_,
  XXX__XX_,
  XX___XX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005B[ 15] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005C[ 12] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005D[ 15] = { /* code 005D, RIGHT SQUARE BRACKET */
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005E[  1] = { /* code 005E, CIRCUMFLEX ACCENT */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0060[  3] = { /* code 0060, GRAVE ACCENT */
  XX______,
  XX______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXXX_,________,
  _XXX_XX_,________,
  _____XXX,________,
  __XXXXXX,________,
  _XX__XXX,________,
  XXX__XXX,________,
  _XX__XXX,X_______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0062[ 24] = { /* code 0062, LATIN SMALL LETTER B */
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXXX,________,
  _XXX__XX,________,
  _XX___XX,X_______,
  _XX___XX,X_______,
  _XX___XX,X_______,
  _XX___XX,________,
  _XXX__XX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0063[  8] = { /* code 0063, LATIN SMALL LETTER C */
  _XXXXXX_,
  XX___XX_,
  XX______,
  XX______,
  XX______,
  XX___XX_,
  XXX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0064[ 24] = { /* code 0064, LATIN SMALL LETTER D */
  ____XXXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _XXXXXXX,________,
  _XX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  __XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0065[  8] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX______,
  XX______,
  XXX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXXX_,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0067[ 20] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,X_______,
  _XX__XX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  __XXXXX_,________,
  _XXXX___,________,
  _XXXXX__,________,
  _XX__XXX,________,
  XX____XX,________,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0068[ 24] = { /* code 0068, LATIN SMALL LETTER H */
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  _XXX____,
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006A[ 14] = { /* code 006A, LATIN SMALL LETTER J */
  __XXX___,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006B[ 24] = { /* code 006B, LATIN SMALL LETTER K */
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XX_,________,
  _XX_XX__,________,
  _XXXX___,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  _XX__XX_,________,
  _XX__XXX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXXXX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  XXX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0070[ 20] = { /* code 0070, LATIN SMALL LETTER P */
  XXXXXXXX,________,
  _XXX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXXXXX_,________,
  _XXX____,________,
  XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0071[ 20] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXXXXXX,________,
  _XX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  __XXXXXX,________,
  _____XXX,________,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0072[  8] = { /* code 0072, LATIN SMALL LETTER R */
  XXXXXXXX,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0073[  8] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXXX_,
  XX______,
  XXX_____,
  __XXXX__,
  ____XXX_,
  XX___XX_,
  XXX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0074[ 11] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  __XX____,
  __XX____,
  _XXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX_XX_,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  XXX__XXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XXX,________,
  __XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  _XX___XX,________,
  _XXX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  _XXXXXXX,________,
  _XX_XXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXX__,________,
  __XX_XX_,________,
  _XX__XXX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0079[ 10] = { /* code 0079, LATIN SMALL LETTER Y */
  _XX__XX_,
  _XXX_XX_,
  __XX_XX_,
  __XXXX__,
  __XXXX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007A[  8] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  XX__XX__,
  ___XXX__,
  __XXX___,
  __XX____,
  _XX__XX_,
  XXX__XX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007B[ 15] = { /* code 007B, LEFT CURLY BRACKET */
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007C[ 14] = { /* code 007C, VERTICAL LINE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007D[ 15] = { /* code 007D, RIGHT CURLY BRACKET */
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007E[  2] = { /* code 007E, TILDE */
  _XX_____,
  XXXXXXX_};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4E0A[ 22] = { /* code 4E0A */
  ______XX,X_______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,XXX_____,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,XXXXXXX_,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4E2D[ 28] = { /* code 4E2D */
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX_X,XXX_____,
  XXXXXXXX,_XX_____,
  _XX_XX__,XXX_____,
  _XX_XX__,XX______,
  _XXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4F20[ 26] = { /* code 4F20 */
  ____XX__,_XX_____,
  ___XXX__,_XX_____,
  ___XX___,XX______,
  __XXX_XX,XXXX____,
  __XX____,XX______,
  _XXXX___,XXXXXXX_,
  XX_XXXXX,X_______,
  __XX___X,X_XX____,
  __XX__XX,XXXXX___,
  __XX____,__XX____,
  __XX___X,XXX_____,
  __XX____,XXX_____,
  ________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4F5C[ 28] = { /* code 4F5C */
  ________,________,
  ____XX__,XX______,
  ____XX_X,XX______,
  ___XX__X,X__XXX__,
  ___XX__X,XXXX____,
  __XXX_XX,XX______,
  _XXXXXX_,XX______,
  XX_XX___,XXXXX___,
  ___XX___,XX______,
  ___XX___,XX_XXX__,
  ___XX___,XXXX____,
  ___XX___,XX______,
  ___XX___,XX______,
  ________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4FE1[ 26] = { /* code 4FE1 */
  _______X,X_______,
  ___XXX__,XX______,
  ___XX___,_XXXXX__,
  __XXXXXX,XX______,
  __XXX___,________,
  _XXXX_XX,XXX_____,
  XX_XX___,________,
  ___XX__X,XXX_____,
  ___XX___,________,
  ___XX_XX,XXXXX___,
  __XXX_XX,__XX____,
  __XX__XX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_50B3[ 30] = { /* code 50B3 */
  ________,XX______,
  ____XX__,XX_XX___,
  ___XXXXX,XXXX____,
  ___XX___,XXXXX___,
  __XX__XX,XXXXX___,
  __XXX_XX,XXXXX___,
  _XXXX_XX,XXXX____,
  XX_XX___,XXXXX___,
  ___XX_XX,XXXX____,
  ___XX_XX,XXXXXXX_,
  ___XXXXX,_XX_____,
  __XX___X,X_XX____,
  __XX____,__XX____,
  ________,XXXX____,
  ________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5177[ 26] = { /* code 5177 */
  _______X,XXX_____,
  ____XXXX,_XX_____,
  ____XX_X,XXX_____,
  ____XXXX,_XX_____,
  ____XX_X,XXX_____,
  ____XXXX,_XX_____,
  ____XXXX,XXX_____,
  ____XX__,_XX_____,
  __XXXXXX,XXXXXXX_,
  _XX_____,________,
  ____XXX_,_XX_____,
  ___XXX__,_XXX____,
  __XX____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5207[ 22] = { /* code 5207 */
  ___XX___,________,
  ___XX___,____XX__,
  ___XX__X,XXXXXXX_,
  ___XXXX_,_XX_XX__,
  _XXXX___,_XX_XX__,
  ___XX___,XX__XX__,
  ___XX___,XX__XX__,
  ___XXXXX,X___XX__,
  __XXX__X,X__XX___,
  ______XX,_XXXX___,
  ____XXX_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_529F[ 26] = { /* code 529F */
  ________,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  ____XXX_,_XX_____,
  __XXX___,XXXXXX__,
  ___XX_XX,XX__XX__,
  ___XX___,XX__XX__,
  ___XXXX_,XX__XX__,
  __XXXX_X,X__XX___,
  _XX____X,X__XX___,
  ______XX,___XX___,
  _____XX_,_XXXX___,
  ____XX__,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_53F7[ 26] = { /* code 53F7 */
  ____XXXX,XXX_____,
  ____XX__,_XX_____,
  ____XX__,XX______,
  ____XXXX,X_______,
  ________,___XXX__,
  _XXXXXXX,XXXX____,
  _____XX_,________,
  ____XXXX,XXX_____,
  ____XXX_,_XX_____,
  ________,_XX_____,
  ________,_XX_____,
  _____XX_,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_540D[ 26] = { /* code 540D */
  _______X,X_______,
  ______XX,XXXX____,
  _____XXX,XXXX____,
  ____XX__,XXX_____,
  ___XXXXX,XX______,
  ______XX,X_______,
  ______XX,________,
  _____XX_,_XXXX___,
  ____XXXX,XXXXX___,
  ___XXXX_,__XX____,
  _XXX_XX_,__XX____,
  ______XX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5B9A[ 26] = { /* code 5B9A */
  _____XX_,________,
  ______XX,_XXX____,
  __XXXXXX,XXXXX___,
  _XX_____,XXX_____,
  _XX__XXX,XX______,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXXX,XX______,
  __XXXXX_,________,
  __XXXXX_,________,
  _XX___XX,________,
  XX_____X,XXXX____,
  ________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5DE5[ 16] = { /* code 5DE5 */
  _______X,XXXX____,
  ___XXXXX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5DF2[ 22] = { /* code 5DF2 */
  ___XXXXX,X_______,
  __XX__XX,X_______,
  ______XX,________,
  _XX___XX,________,
  _XXXXXX_,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,_XXXX___,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5E8F[ 28] = { /* code 5E8F */
  ______XX,X_______,
  _______X,X_XX____,
  ____XXXX,XXX_____,
  ___XXX__,________,
  ___XX_XX,XXXX____,
  ___XX___,XXX_____,
  ___XX__X,XX______,
  ___XX___,XXXXXX__,
  __XXXXXX,XXXXXXX_,
  __XX____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  XX______,XX______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5EA6[ 28] = { /* code 5EA6 */
  ______XX,________,
  _______X,X_______,
  _____XXX,XXXXX___,
  ___XXX__,_XX_____,
  ___XX_XX,_XX_____,
  ___XX_XX,XXXXX___,
  ___XXXXX,XX______,
  ___XX_XX,XX______,
  __XX____,________,
  __XX_XXX,XXXX____,
  __XX__XX,XXX_____,
  _XX____X,XX______,
  XX____XX,_XXX____,
  ___XXXX_,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5F0F[ 28] = { /* code 5F0F */
  _____XXX,________,
  ______XX,XX______,
  ______XX,_XXX____,
  ______XX,________,
  ______XX,XXX_____,
  _XXXXXXX,________,
  _______X,X_______,
  ___XXX_X,X_______,
  _XXXX__X,X_______,
  ___XX___,XX______,
  ___XXXX_,XX______,
  __XXXX__,_XXXX___,
  XXX_____,_XXXX___,
  ________,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_606F[ 28] = { /* code 606F */
  _____XXX,________,
  _____XX_,________,
  ____XXXX,XX______,
  ___XXXX_,XX______,
  ___XXXXX,XX______,
  ___XXX__,XX______,
  ___XXXXX,XX______,
  ___XX___,XX______,
  ___XXXXX,XX______,
  _____XX_,_XXX____,
  _XXXX_XX,___XX___,
  _XXXX___,_XX_____,
  XXX_XX__,_XXX____,
  _____XXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6362[ 26] = { /* code 6362 */
  ___XXX__,XX______,
  ____XX__,XXXXX___,
  ___XX__X,X_XX____,
  ____XXXX,_XX_____,
  _XXXX_XX,XXXXXX__,
  ___XXXXX,_XXXX___,
  ____XXXX,_XXXX___,
  __XXX_XX,XX_XX___,
  XXXXXXXX,XXXXXXX_,
  ___XX___,XX______,
  ___XX__X,X__XX___,
  ___XX_XX,___XXX__,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_63DB[ 28] = { /* code 63DB */
  ________,________,
  ___XX___,XX______,
  ___XX__X,XXXX____,
  ___XX__X,XXXX____,
  ___XXXXX,_XX_____,
  _XXXX_XX,XXXXXX__,
  ___XXXXX,XX_XX___,
  ___XX_XX,XXXXX___,
  _XXXX_XX,X__XX___,
  XXXXX_XX,XXXXXXX_,
  ___XXXX_,XX______,
  ___XX__X,XXXXX___,
  __XXX_XX,X__XXX__,
  ____XXX_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6599[ 26] = { /* code 6599 */
  ____XX__,__XXX___,
  ____XX__,___XX___,
  _XX_XXXX,XXXXX___,
  __XXXXX_,___XX___,
  ____XX__,XX_XX___,
  XXXXXXX_,XXXX____,
  ___XX___,___XXXX_,
  __XXXXXX,XXXX____,
  _XXXX_XX,__XX____,
  XX_XX___,__XX____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6A21[ 26] = { /* code 6A21 */
  ____XX__,___XX___,
  ____XX_X,X__XXXX_,
  ____XXXX,X_XX____,
  ____XX__,XXXX____,
  _XXXXX_X,XXXXXX__,
  ___XX__X,X_XXXX__,
  ___XXXXX,XXXXX___,
  __XXX__X,XXXXX___,
  _XXXX___,_XX_XXX_,
  XX_XX_XX,XXXXX___,
  ___XX___,XX_XXX__,
  ___XX__X,X___XXX_,
  ___XX___,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6B65[ 28] = { /* code 6B65 */
  _______X,X_______,
  ___XXX_X,XXXX____,
  ____XX_X,XX______,
  ____XX_X,X_______,
  ____XXXX,XXXXXXX_,
  _XXXXXXX,X_______,
  ____XX_X,X_XX____,
  ___XXX_X,XXXX____,
  ___XX__X,XXX_____,
  ________,XX______,
  ______XX,X_______,
  _____XX_,________,
  ___XXX__,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6EE1[ 26] = { /* code 6EE1 */
  _____XX_,_XXX____,
  __XX__XX,_XXXX___,
  ___XXXXX,XXX_____,
  ______XX,XX______,
  XXX____X,XXXXX___,
  _XX__XXX,_XX_____,
  ______XX,_XXXX___,
  __XXXXXX,XXXXX___,
  _XX_XXXX,_XXXX___,
  _XX_XXXX,XXXXX___,
  XXX_XX__,___XX___,
  XX__XX__,_XXXX___,
  ____XX__,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6EFF[ 26] = { /* code 6EFF */
  ______XX,_XXX____,
  __XXX_XX,_XXXX___,
  ___XX_XX,XXXX____,
  ____XXXX,_XX_____,
  _XX____X,XXX_____,
  __XX____,XX______,
  __XXXXXX,XXXXXX__,
  __XXXXX_,XXX_XX__,
  __XXXXXX,XXXXXX__,
  _XX_XXXX,XXXXXX__,
  _XX_XX__,XX__XX__,
  _XX_____,__XXXX__,
  ________,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7A31[ 26] = { /* code 7A31 */
  ________,_XXX____,
  ___XXXX_,XX______,
  __XXX_XX,XX__XX__,
  ___XX_XX,XXXXX___,
  ___XXXXX,XXX_____,
  XXXXX___,_XXXXX__,
  ___XXXXX,XXX_XX__,
  __XXXXXX,XXXXX___,
  _XXXX_XX,_XX_XXX_,
  XX_XXXXX,XXXXXX__,
  ___XX_XX,____XX__,
  ___XX_XX,___XXX__,
  ___XX___,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7DB2[ 24] = { /* code 7DB2 */
  ___XX___,__XXXX__,
  __XX__XX,XXX_XX__,
  __XXXXXX,X_XXXX__,
  _XXXX_XX,XXXXXX__,
  _XXXX_XX,XX_XXX__,
  __XXXXX_,_XXXXX__,
  _XXXXXXX,XX_XXX__,
  _XX_XXXX,X___XX__,
  _XXXXXX_,XXXXXX__,
  _XX__XX_,____XX__,
  ________,___XXX__,
  ________,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7DE8[ 26] = { /* code 7DE8 */
  ________,_XX_____,
  ___XX___,XX______,
  ___XX_XX,XXXXX___,
  __XXXX_X,XX_XX___,
  _XX_XXXX,_XXX____,
  _XXXX_XX,XX______,
  __XXXXXX,__XXXXX_,
  _XXXXXXX,XXXX_XX_,
  ____XXXX,XXXXXXX_,
  XXXX_XXX,XXXXXXX_,
  _XX_XXXX,XXXXXX__,
  ________,___XXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7F16[ 26] = { /* code 7F16 */
  ________,________,
  ___XX___,XXX_____,
  __XXXX__,_XXXX___,
  _XX_XXXX,XX_XX___,
  _XXXX_XX,__XXX___,
  _XXXX_XX,XXX_____,
  __XX__XX,__XXXX__,
  _XXXX_XX,XXXX_XX_,
  _XXX_XXX,XXXXXXX_,
  ___XXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  _XX_____,___XXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7F51[ 24] = { /* code 7F51 */
  ________,__XX____,
  _XXXXXXX,XXXXX___,
  _XX_____,__XX____,
  _XX_XXX_,XXXX____,
  _XXXXXX_,XXXX____,
  _XXXXXXX,XXXX____,
  _XX_XX_X,XXXX____,
  _XXXXXXX,XXXX____,
  _XXX_XXX,_XXX____,
  _XX__XX_,__XX____,
  XXX_____,XXXX____,
  ________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_80FD[ 26] = { /* code 80FD */
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,XXXX____,
  _XX_XXXX,________,
  XXXXXXXX,________,
  ___XXX_X,XXXX____,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXXXX,XXXX____,
  _XXXXXXX,X_______,
  XX__XXXX,___XX___,
  XX_XXX_X,X__XXX__,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_865F[ 26] = { /* code 865F */
  ________,XX______,
  _XXXXX__,XXXX____,
  _XX_XX__,XX_XX___,
  __XXXXXX,XXXXXX__,
  ____XXXX,XXXXX___,
  XXXXX_XX,XXX_____,
  __XX__XX,XXXXX___,
  _XXXXXX_,_XX_____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX__XX_,
  __XXXX_X,XXX__XX_,
  _____XXX,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A00[ 24] = { /* code 8A00 */
  ______XX,X_______,
  _______X,XXXXXX__,
  XXXXXXXX,XX______,
  ________,________,
  ____XXXX,XX______,
  ________,________,
  ____XXXX,XX______,
  ________,________,
  ____XXXX,XXXX____,
  ____XX__,_XX_____,
  ____XX__,XXX_____,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A0A[ 22] = { /* code 8A0A */
  ___XX___,__XX____,
  ___XX__X,XXXXX___,
  XXXXXXXX,X__XX___,
  _______X,X_XX____,
  __XXX__X,X_XX____,
  ____XXXX,XXXX____,
  ___XX__X,X_XX____,
  ___XXXXX,X_XX_XX_,
  __XXXX_X,X__XXXX_,
  __XXXX_X,X__XXXX_,
  __XXX__X,X___XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A2D[ 22] = { /* code 8A2D */
  ___XXX__,XXXX____,
  ____XX_X,XXX_____,
  XXXXXXXX,XXX_____,
  _______X,X_XXXX__,
  __XXX_XX,________,
  ___XXX__,XXXXX___,
  _______X,X_XX____,
  _XXXXX__,XXX_____,
  __XXXX__,_XX_____,
  __XXXX__,XXXXX___,
  __XX_XXX,X__XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A9E[ 22] = { /* code 8A9E */
  ___XX__X,XXXXX___,
  ___XX___,XXX_____,
  XXXXXX__,XXXXX___,
  ______XX,XXXXX___,
  __XXX___,XX_XX___,
  ___XXX_X,XXXXXXX_,
  _____XXX,________,
  _XXXXXXX,XXXXX___,
  _XXXXX_X,X__XX___,
  __XXXX_X,X__XX___,
  _______X,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8BBE[ 22] = { /* code 8BBE */
  ___XX_XX,XXX_____,
  ______XX,_XX_____,
  ______XX,_XX_____,
  __XXX_XX,_XXXXX__,
  _XXXXXX_,________,
  ___XX__X,XXXX____,
  ___XX__X,XXX_____,
  __XX____,XXX_____,
  __XXXX__,XXX_____,
  __XX___X,XXXX____,
  __XX_XXX,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8BED[ 24] = { /* code 8BED */
  ________,__XXX___,
  __XXX_XX,XXX_____,
  ___XX___,XX______,
  ________,XXXXX___,
  __XXX_XX,X_XXX___,
  XXXXX__X,X_XX____,
  __XX__XX,XXXXXXX_,
  __XX____,________,
  __XX__XX,XXXXX___,
  __XXX_XX,X__XX___,
  __XX___X,X_XX____,
  __XX___X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8CC7[ 28] = { /* code 8CC7 */
  ______XX,________,
  ______XX,XXXX____,
  _XXX_XXX,_XX_____,
  _______X,X_______,
  __XXXXXX,XXX_____,
  _XX_XXX_,__XXX___,
  ___XXXXX,XXX_____,
  ___XX___,XX______,
  ___XXXXX,XX______,
  ___XXXXX,XX______,
  ___XX___,XX______,
  ___XXXXX,XX______,
  ____XX__,XX______,
  ___XX___,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8D44[ 28] = { /* code 8D44 */
  ________,________,
  _____XXX,XXXX____,
  _XXXXXXX,XXXX____,
  ____XX_X,X_______,
  ___XX_XX,XX______,
  XXXX_XX_,_XXX____,
  ________,XX______,
  ___XXXXX,XX______,
  ___XX_XX,XX______,
  ___XX_XX,XX______,
  ___XXXX_,XX______,
  ___XXXXX,XX______,
  ____XX__,XXX_____,
  __XXX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8DEF[ 26] = { /* code 8DEF */
  ________,XX______,
  ___XXX_X,XX______,
  _XXXXX_X,XXXXX___,
  _XX_XXXX,__XX____,
  _XXXX_XX,XXX_____,
  ___XX___,XXX_____,
  _XXXXX__,XXXX____,
  _XXXX__X,X_XXXX__,
  _XXXX_XX,__XXXXX_,
  _XXXXXXX,XXXXX___,
  XXX____X,X_XX____,
  _______X,XXXX____,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9759[ 26] = { /* code 9759 */
  ___XX___,_XX_____,
  ___XXXX_,XXXXX___,
  __XXX___,XXXX____,
  _XXXXXXX,XXX_____,
  ___XXXXX,XXXXXX__,
  _XXX____,_XXXXXX_,
  __XXXXXX,XXXXXX__,
  __XX_XX_,_XXXXX__,
  __XXXXX_,XXX_____,
  __XXXXX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XXX,XXX_____,
  ___XXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_975C[ 28] = { /* code 975C */
  ________,________,
  ___XX___,_XXX____,
  ___XXXXX,XX_XX___,
  __XXXXXX,_XXXX___,
  ___XXXXX,XXXX____,
  __XXX___,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXX___,
  __XX_XX_,_XXXX___,
  __XXXXXX,XXXX____,
  __XXXXX_,_XX_____,
  __XXXXX_,_XX_____,
  _XX__XX_,_XX_____,
  ____XXX_,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_97F3[ 28] = { /* code 97F3 */
  ________,________,
  ______XX,X_______,
  ______XX,XXX_____,
  ____XXX_,XXX_____,
  _____XX_,XX______,
  _____XX_,XX______,
  __XXXXXX,XXXXXX__,
  _XX_____,________,
  ____XXXX,XXX_____,
  ____XX__,_XX_____,
  ____XXXX,XXX_____,
  ____XX__,_XX_____,
  ____XXXX,XXX_____,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9801[ 28] = { /* code 9801 */
  ________,________,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  ____XX_X,XX______,
  ___XXXXX,XX______,
  ___XX__X,XX______,
  ___XXXXX,XX______,
  ___XX___,XX______,
  ___XXXXX,XX______,
  ___XX___,XX______,
  ___XXXXX,XX______,
  ____XX_X,XX______,
  ___XX___,XXX_____,
  __XX____,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9A5F[ 26] = { /* code 9A5F */
  _______X,XXX_____,
  _XXXXXXX,XX_XXX__,
  _XXXXX_X,XXXXXX__,
  _XXXX_XX,XX_XX___,
  _XXXXXXX,XXXXXX__,
  _XXXX__X,XXXX____,
  _XXXXXXX,_XXX____,
  ___XXXXX,XXX_XX__,
  XXXXXX_X,XXXXX___,
  XX__XXXX,XXXXXXX_,
  ____XXX_,XXX__XX_,
  ___XXX__,_XX_____,
  ________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9AA4[ 26] = { /* code 9AA4 */
  _______X,XXX_____,
  _XXXXXXX,XX_XXX__,
  _XX_XX_X,XXXXXX__,
  _XX_XXXX,XX_XX___,
  _XX_XXXX,XXXXXX__,
  _XX_XXXX,XXXX_XX_,
  _XXXXXX_,_XXX____,
  _XX__XX_,XXX_XX__,
  ___XXX_X,XXXXXX__,
  XXXXXXXX,XXXX____,
  ____XX_X,XXXXX___,
  ___XXXXX,_XX_XXX_,
  _____XX_,_XX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[142] = {
   {   1,   1,   0,  13,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0020 } /* code 0020, SPACE */
  ,{   3,  12,   3,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   5,   4,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0022 } /* code 0022, QUOTATION MARK */
  ,{   7,  13,   1,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0023 } /* code 0023, NUMBER SIGN */
  ,{   7,  14,   1,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0024 } /* code 0024, DOLLAR SIGN */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0025 } /* code 0025, PERCENT SIGN */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0026 } /* code 0026, AMPERSAND */
  ,{   3,   4,   1,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0027 } /* code 0027, APOSTROPHE */
  ,{   6,  14,   2,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   6,  14,   1,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,  10,   1,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002A } /* code 002A, ASTERISK */
  ,{   7,  10,   1,   3,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002B } /* code 002B, PLUS SIGN */
  ,{   3,   5,   1,  11,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002C } /* code 002C, COMMA */
  ,{   7,   1,   1,   8,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   2,   1,  12,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002E } /* code 002E, FULL STOP */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_002F } /* code 002F, SOLIDUS */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  12,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0033 } /* code 0033, DIGIT THREE */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0039 } /* code 0039, DIGIT NINE */
  ,{   3,   8,   3,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003A } /* code 003A, COLON */
  ,{   3,  10,   3,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003B } /* code 003B, SEMICOLON */
  ,{   7,  11,   1,   3,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   4,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003D } /* code 003D, EQUALS SIGN */
  ,{   7,  11,   1,   3,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_003F } /* code 003F, QUESTION MARK */
  ,{   9,  13,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   5,  12,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   9,  13,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   5,  15,   2,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   5,  15,   2,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   1,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   9,   1,   0,  14,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0060 } /* code 0060, GRAVE ACCENT */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   8,   8,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   7,   8,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  12,   1,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  10,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   5,  12,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  14,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   9,  12,   0,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   5,  12,   2,   2,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  10,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  10,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   8,   8,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,   8,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   7,  11,   1,   3,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,   8,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,  10,   0,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   8,   1,   6,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,  15,   2,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   2,  14,   4,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007C } /* code 007C, VERTICAL LINE */
  ,{   5,  15,   2,   1,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   7,   2,   1,   7,   9, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_007E } /* code 007E, TILDE */
  ,{  15,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4E0A } /* code 4E0A */
  ,{  11,  14,   3,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4E2D } /* code 4E2D */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4F20 } /* code 4F20 */
  ,{  14,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4F5C } /* code 4F5C */
  ,{  14,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_4FE1 } /* code 4FE1 */
  ,{  15,  15,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_50B3 } /* code 50B3 */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5177 } /* code 5177 */
  ,{  15,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5207 } /* code 5207 */
  ,{  14,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_529F } /* code 529F */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_53F7 } /* code 53F7 */
  ,{  13,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_540D } /* code 540D */
  ,{  14,  13,   2,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5B9A } /* code 5B9A */
  ,{  15,   8,   1,   4,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5DE5 } /* code 5DE5 */
  ,{  13,  11,   3,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5DF2 } /* code 5DF2 */
  ,{  15,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5E8F } /* code 5E8F */
  ,{  15,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5EA6 } /* code 5EA6 */
  ,{  14,  14,   2,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_5F0F } /* code 5F0F */
  ,{  13,  14,   2,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_606F } /* code 606F */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6362 } /* code 6362 */
  ,{  15,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_63DB } /* code 63DB */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6599 } /* code 6599 */
  ,{  16,  13,   0,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6A21 } /* code 6A21 */
  ,{  15,  14,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6B65 } /* code 6B65 */
  ,{  13,  13,   2,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6EE1 } /* code 6EE1 */
  ,{  14,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_6EFF } /* code 6EFF */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7A31 } /* code 7A31 */
  ,{  15,  12,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7DB2 } /* code 7DB2 */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7DE8 } /* code 7DE8 */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7F16 } /* code 7F16 */
  ,{  13,  12,   2,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_7F51 } /* code 7F51 */
  ,{  14,  13,   2,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_80FD } /* code 80FD */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_865F } /* code 865F */
  ,{  14,  12,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A00 } /* code 8A00 */
  ,{  16,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A0A } /* code 8A0A */
  ,{  16,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A2D } /* code 8A2D */
  ,{  15,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8A9E } /* code 8A9E */
  ,{  15,  11,   1,   3,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8BBE } /* code 8BBE */
  ,{  15,  12,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8BED } /* code 8BED */
  ,{  13,  14,   2,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8CC7 } /* code 8CC7 */
  ,{  13,  14,   2,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8D44 } /* code 8D44 */
  ,{  16,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_8DEF } /* code 8DEF */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9759 } /* code 9759 */
  ,{  15,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_975C } /* code 975C */
  ,{  15,  14,   1,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_97F3 } /* code 97F3 */
  ,{  13,  14,   2,   1,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9801 } /* code 9801 */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9A5F } /* code 9A5F */
  ,{  15,  13,   1,   2,  17, acGUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_9AA4 } /* code 9AA4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop48 = {
   0x9AA4 /* first character */
  ,0x9AA4 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[141] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop47 = {
   0x9A5F /* first character */
  ,0x9A5F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[140] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop46 = {
   0x9801 /* first character */
  ,0x9801 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[139] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop45 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[138] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop44 = {
   0x975C /* first character */
  ,0x975C /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[137] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop43 = {
   0x9759 /* first character */
  ,0x9759 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[136] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop42 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[135] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop41 = {
   0x8D44 /* first character */
  ,0x8D44 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[134] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop40 = {
   0x8CC7 /* first character */
  ,0x8CC7 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[133] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop39 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[132] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop38 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[131] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop37 = {
   0x8A9E /* first character */
  ,0x8A9E /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[130] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop36 = {
   0x8A2D /* first character */
  ,0x8A2D /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[129] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop35 = {
   0x8A0A /* first character */
  ,0x8A0A /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[128] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop34 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[127] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop33 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[126] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop32 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[125] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop31 = {
   0x7F51 /* first character */
  ,0x7F51 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[124] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop30 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[123] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop29 = {
   0x7DE8 /* first character */
  ,0x7DE8 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[122] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop28 = {
   0x7DB2 /* first character */
  ,0x7DB2 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[121] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop27 = {
   0x7A31 /* first character */
  ,0x7A31 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[120] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop26 = {
   0x6EFF /* first character */
  ,0x6EFF /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[119] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop25 = {
   0x6EE1 /* first character */
  ,0x6EE1 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[118] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop24 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[117] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop23 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[116] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop22 = {
   0x6599 /* first character */
  ,0x6599 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[115] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop21 = {
   0x63DB /* first character */
  ,0x63DB /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[114] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop20 = {
   0x6362 /* first character */
  ,0x6362 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[113] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop19 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[112] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop18 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[111] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop17 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[110] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop16 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[109] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop15 = {
   0x5DF2 /* first character */
  ,0x5DF2 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[108] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop14 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[107] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop13 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[106] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop12 = {
   0x540D /* first character */
  ,0x540D /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[105] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop11 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[104] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop10 = {
   0x529F /* first character */
  ,0x529F /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[103] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop9 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[102] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop8 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[101] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop7 = {
   0x50B3 /* first character */
  ,0x50B3 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[100] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop6 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop5 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop4 = {
   0x4F20 /* first character */
  ,0x4F20 /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[ 97] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop3 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop2 = {
   0x4E0A /* first character */
  ,0x4E0A /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_ALLPage_WinTitle_DFKaiSB_16B_Prop1}
  ,13 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

