/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_JS_2_Step2_1_Microsoft JhengHei_22B.c         *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_JS_2_Step2_1_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002F[ 15] = { /* code 002F, SOLIDUS */
  ______XX,
  ______XX,
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0030[ 13] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0031[ 13] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XXXXX___,
  X__XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0032[ 13] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _XXXXXX_,
  _X____XX,
  ______XX,
  ______XX,
  ______X_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0033[ 13] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XXXXXXX_,
  X____XX_,
  _____XX_,
  ____XXX_,
  _XXXX___,
  _XXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0034[ 26] = { /* code 0034, DIGIT FOUR */
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___X__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _X____XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0035[ 13] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0036[ 13] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  __XXXXX_,
  _XXX____,
  _XX_____,
  XX______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0037[ 26] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0038[ 13] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _XXXXXXX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXX___,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0039[ 13] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XXXXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,________,
  _XXX____,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0045[ 13] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0046[ 13] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,__X_____,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX____XX,XXX_____,
  XX____XX,XXX_____,
  XX______,_XX_____,
  _XX_____,_XX_____,
  _XXX____,_XX_____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XXX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XXX__,________,
  XXXXX___,________,
  XX_XXX__,________,
  XX__XXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004C[ 13] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004D[ 26] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__X___,X__XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,_XX_____,
  XXXX____,_XX_____,
  XXXX____,_XX_____,
  XX_XX___,_XX_____,
  XX_XXX__,_XX_____,
  XX__XX__,_XX_____,
  XX___XX_,_XX_____,
  XX___XX_,_XX_____,
  XX____XX,_XX_____,
  XX_____X,XXX_____,
  XX_____X,XXX_____,
  XX______,XXX_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0050[ 13] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XXXXXXX_,
  XX___XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  XXXXXXX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,________,
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0053[ 13] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  _XX_____,
  _XXXXX__,
  ___XXXX_,
  _____XXX,
  ______XX,
  X_____XX,
  XXXXXXX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ____XX_X,________,
  ____XXXX,________,
  ____XXXX,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0057[ 39] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  __X___XX,__XX___X,________,
  __XX__XX,__XX__XX,________,
  __XX__XX,__XX__XX,________,
  ___X__X_,___X__X_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0058[ 26] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,_XX_____,
  _XX_____,XX______,
  __X____X,X_______,
  __XX__XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  _____X__,________,
  ____XXX_,________,
  ___XX_XX,________,
  __XX___X,X_______,
  __XX____,X_______,
  _XX_____,XX______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX____,XX______,
  __XX___X,X_______,
  ___XX__X,X_______,
  ___XXXXX,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_005A[ 26] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXX_,
  _XXXXXXX,
  _X____XX,
  ______XX,
  _XXXXXXX,
  XXX___XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0062[ 28] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0067[ 26] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _X____XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0068[ 28] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006A[ 17] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006B[ 28] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX_XX___,________,
  XX___XX_,________,
  XX____XX,________,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX__XXX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0071[ 26] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XXXXXX__,
  XX___X__,
  XXXX____,
  _XXXX___,
  ____XX__,
  X___XX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____XX,____XX__,
  XX____XX,____XX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__X__,X__XX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,_XXX____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0078[ 18] = { /* code 0078, LATIN SMALL LETTER X */
  XX_____X,X_______,
  _XX___XX,________,
  __X__XX_,________,
  ___XXX__,________,
  ____X___,________,
  ___XXX__,________,
  __XX__X_,________,
  _XX___XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0079[ 26] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___X_X__,________,
  ___XXX__,________,
  ____XX__,________,
  ___XX___,________,
  __XXX___,________,
  XXXX____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_503C[ 30] = { /* code 503C */
  ___X____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __X_____,XX______,
  _XX__XXX,XXXXXX__,
  _XX__XXX,XXXXXX__,
  XXX__XX_,____XX__,
  XXX__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X__XXX,XXXXXX__,
  __X__XX_,____XX__,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_507F[ 32] = { /* code 507F */
  __XX_X__,XX___X__,
  __XXXXX_,XX__XX__,
  __XX_XX_,XX_XX___,
  __X___X_,XX_XX___,
  _XX_XXXX,XXXXXXX_,
  _XX_XXXX,XXXXXXX_,
  XXX_X___,_____XX_,
  XXX_X_XX,XXXX_XX_,
  __X___XX,XXXX____,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  __X____X,X__X____,
  __X___XX,___XX___,
  __X__XX_,___XX___,
  __X_XXXX,XXXXXX__,
  __X_XXXX,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_511F[ 30] = { /* code 511F */
  __XX_XX_,XX__X___,
  __XX__XX,XX_XX___,
  __X_XXXX,XXXXXXX_,
  _XX_XXXX,___XXXX_,
  _XX___XX,XXXXX___,
  _XX_____,________,
  XXX__XXX,XXXXXX__,
  X_X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X__X__,____XX__,
  __X__XXX,XXXXXX__,
  __X___XX,__XXX___,
  __XXXXX_,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_516C[ 30] = { /* code 516C */
  _____X__,XXX_____,
  ____XX__,XXX_____,
  ____XX__,__XX____,
  ___XX___,__XX____,
  __XX____,___XX___,
  _XXX___X,____XX__,
  XXX___XX,____XXX_,
  _X____X_,______X_,
  _____XX_,__X_____,
  _____X__,__XX____,
  ____XX__,__XX____,
  ____X___,___XX___,
  ___XX___,XXXXX___,
  __XXXXXX,XX__XX__,
  __XXX___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5206[ 30] = { /* code 5206 */
  _____X__,XXX_____,
  ____XX__,XXX_____,
  ____X___,__XX____,
  ___XX___,__XX____,
  ___X____,___XX___,
  __XX____,____X___,
  _XXXXXXX,XXXX_X__,
  XX_XXXXX,XXXX__X_,
  ______X_,___X____,
  _____XX_,___X____,
  _____X__,___X____,
  ____XX__,___X____,
  ___XX___,__XX____,
  __XX___X,XXXX____,
  _XX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_529B[ 30] = { /* code 529B */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ______XX,_____X__,
  ______XX,_____X__,
  ______X_,_____X__,
  ______X_,____XX__,
  _____XX_,____XX__,
  _____X__,____XX__,
  ____XX__,____XX__,
  ___XX___,____XX__,
  __XX____,XXXXXX__,
  _X______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ________,___XX___,
  ________,___X____,
  _______X,XXXX____,
  _______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5411[ 30] = { /* code 5411 */
  ____XX__,________,
  ___XX___,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X_______,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__XX___,XX__X___,
  X__XX___,XX__X___,
  X__XX___,XX__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X_______,____X___,
  X_______,_XXXX___,
  X_______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5708[ 28] = { /* code 5708 */
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  X__XX_X_,_X__X___,
  X_XXXXXX,XXX_X___,
  X____X__,____X___,
  X_XXXXXX,XXX_X___,
  X__XX___,XX__X___,
  X_XXXXXX,XXX_X___,
  XXXXX___,X_XXX___,
  X__XX___,X___X___,
  X__XX_XX,X___X___,
  X__XX___,__X_X___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5C3A[ 30] = { /* code 5C3A */
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XX____,____XX__,
  __XX____,____XX__,
  __XX____,____XX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXXX__,________,
  __XX_X__,________,
  __X__XX_,________,
  __X___XX,________,
  _XX____X,XX______,
  _XX_____,XXXXX___,
  XX______,__XXXXX_,
  _X______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5EF6[ 34] = { /* code 5EF6 */
  ________,_____X__,
  XXXXX___,_XXXXXX_,
  XXXXX_XX,XXXXX___,
  ___XX_XX,XXX_____,
  __XX____,__X_____,
  _XX___XX,__X_____,
  XXXXX_XX,__XXXXX_,
  XXXXX_XX,__XXXXX_,
  ___XX_XX,__X_____,
  XX_XX_XX,__X_____,
  _X_X__XX,__X_____,
  _XXX_XXX,XXXXXXX_,
  _XXX_XXX,XXXXXXX_,
  __XXX___,________,
  _XXXXXXX,XXXXXXX_,
  XX___XXX,XXXXXXX_,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_626D[ 30] = { /* code 626D */
  __XX__XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  XXXXXX__,XX__XX__,
  XXXXXX__,X___XX__,
  __XX____,X___XX__,
  __XX____,X___XX__,
  __XXX_XX,XXXXXXX_,
  _XXXX_XX,XXXXXXX_,
  XXXX____,X___X___,
  X_XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  __XX___X,X___X___,
  XXXX_XXX,XXXXXXX_,
  _XXX_XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_65B9[ 32] = { /* code 65B9 */
  ______X_,________,
  ______XX,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____XX__,________,
  ____XX__,________,
  ____XXXX,XXXXX___,
  ____XXXX,XXXXX___,
  ____XX__,____X___,
  ____X___,___XX___,
  ___XX___,___XX___,
  __XXX___,___XX___,
  _XXX____,___XX___,
  XXX____X,XXXX____,
  _X______,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_65F6[ 30] = { /* code 65F6 */
  ________,___X____,
  XXXXX___,___X____,
  XXXXX___,___X____,
  X__XXXXX,XXXXXX__,
  X__XXXXX,XXXXXX__,
  X__XX___,___X____,
  XXXXX_XX,___X____,
  XXXXX__X,___X____,
  X__XX__X,X__X____,
  X__XX___,X__X____,
  X__XX___,X__X____,
  XXXXX___,___X____,
  XXXXX___,___X____,
  X__XX___,XXXX____,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6642[ 32] = { /* code 6642 */
  ________,_X______,
  XXXX_XXX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  X_XX____,_X______,
  X_XX____,_X______,
  X_XX_XXX,XXXXX___,
  XXXX_XXX,XXXXX___,
  XXXX____,________,
  X_XX____,___X____,
  X_XX_XXX,XXXXXX__,
  X_XX_XXX,XXXXXX__,
  X_XX__X_,___X____,
  XXXX__XX,___X____,
  XXXX___X,___X____,
  X_XX____,XXXX____,
  ________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6807[ 30] = { /* code 6807 */
  __XX__XX,XXXXXXX_,
  __XX__XX,XXXXXXX_,
  __XX____,________,
  XXXXXX__,________,
  XXXXXXXX,XXXXXXX_,
  __XXX_XX,XXXXXXX_,
  __XXXX_X,X_X_____,
  _XXX_X_X,X_X_X___,
  XXXX___X,__X_XX__,
  XXXX__XX,__X__X__,
  __XX__X_,__X__X__,
  __XX_XX_,__X__XX_,
  __XX_X__,__X__XX_,
  __XX___X,XXX___X_,
  __XX____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6A19[ 30] = { /* code 6A19 */
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX____,XX_X____,
  XXXXX_XX,XXXXXXX_,
  XXXXX_X_,XX_X_XX_,
  __XX__XX,XXXXXXX_,
  _XXXX___,________,
  _XXXX_XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  __XX____,________,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX___X,_XX_X___,
  __XX__XX,XXX_XX__,
  __XX__X_,_XX__X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6B65[ 30] = { /* code 6B65 */
  _______X,X_______,
  ___X___X,X_______,
  ___X___X,XXXXXX__,
  ___X___X,XXXXXX__,
  ___X___X,X_______,
  ___X___X,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,X_______,
  ___XX__X,X___XX__,
  XXXXX__X,X__XXX__,
  _XX_____,__XXX___,
  _______X,XXXX____,
  _XXXXXXX,XX______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_725B[ 32] = { /* code 725B */
  _______X,X_______,
  ___XX__X,X_______,
  ___X___X,X_______,
  __XX___X,X_______,
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  XXX____X,X_______,
  _X_____X,X_______,
  _______X,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_76EE[ 30] = { /* code 76EE */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_79D2[ 30] = { /* code 79D2 */
  ____XX__,__X_____,
  XXXXXX__,__X_____,
  _XXX____,X_X_X___,
  ___X____,X_X_XX__,
  XXXXXX_X,X_X__X__,
  XXXXXX_X,X_X__XX_,
  __XXX__X,__X___X_,
  __XXX_XX,__X_____,
  _XXXXXX_,__X__X__,
  _X_X_X__,__X_XX__,
  XX_X____,___XXX__,
  ___X____,__XXX___,
  ___X____,XXXX____,
  ___X__XX,XX______,
  ___X__XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7C73[ 32] = { /* code 7C73 */
  _______X,________,
  __X____X,____XX__,
  __XX___X,___XX___,
  ___XX__X,___XX___,
  ___XX__X,__XX____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  ____X__X,__X_____,
  ___XX__X,__XX____,
  __XX___X,___XX___,
  __XX___X,____XX__,
  _XX____X,_____XX_,
  _X_____X,______X_,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7DE8[ 32] = { /* code 7DE8 */
  ___X____,____XXX_,
  __XX__XX,XXXX____,
  __X_XXXX,________,
  _XX_X_XX,XXXXXX__,
  _X__X_XX,_____X__,
  XXXXX_XX,_____X__,
  XXXX__XX,XXXXXX__,
  __XX__XX,________,
  __X_X_XX,XXXXXXX_,
  _X_XXXXX,X_X_XXX_,
  XXX__XXX,X_X_XXX_,
  ______XX,XXXXXXX_,
  _XXXX_X_,X_X_XXX_,
  _X_X_XX_,X_X_XXX_,
  XX_X_XX_,X_X_XXX_,
  X_______,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7F16[ 32] = { /* code 7F16 */
  ___X____,_X______,
  __XX____,_XX_____,
  __X___XX,XXXXXX__,
  _XX___XX,XXXXXX__,
  _XX_X_X_,_____X__,
  XX_XXXXX,XXXXXX__,
  XXXXX_XX,XXXXXX__,
  XXXX__X_,XXXXXXX_,
  __XX__X_,XXXXXXX_,
  _XX_X_X_,X_X_XXX_,
  XX_XX_X_,X_X_XXX_,
  XXX___X_,XXXXXXX_,
  ___XXXX_,XXXXXXX_,
  _XXXXXX_,X_X_XXX_,
  XXXX_X__,X_X_XXX_,
  XX__XX__,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_865F[ 30] = { /* code 865F */
  _XXXXX__,_XX_____,
  _XXXXX__,_XXXXX__,
  _X__XX__,_XX_____,
  _XXXXX_X,XXXXXXX_,
  _XXXXX_X,__X__XX_,
  _______X,_XXXX___,
  XXXXXX_X,__X_____,
  _XX____X,__XXXXX_,
  _XXXX__X,________,
  _XXXX__X,_X_XX___,
  ____X_XX,_X_XX___,
  ____X_XX,_X_XX_X_,
  ____X_XX,_X_XX_X_,
  _XXXX_X_,XX_XXXX_,
  __XX_XXX,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8865[ 30] = { /* code 8865 */
  ___X____,_X______,
  ___XX___,_X______,
  ____X___,_X______,
  XXXXXXX_,_X______,
  XXXXXXX_,_X______,
  _____X__,_XX_____,
  ____X_X_,_XXX____,
  ___XX_X_,_X_XX___,
  _XXXXX__,_X___X__,
  XX_X_XX_,_X____X_,
  ___X__X_,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_88DC[ 30] = { /* code 88DC */
  _XX_____,_XX_XX__,
  __XX____,_XX__X__,
  __XX_XXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXX___,_XX_____,
  ___XX_XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  _XXXX_X_,_XX__X__,
  XXXXXXXX,XXXXXX__,
  __X_X_X_,_XX__X__,
  __X___XX,XXXXXX__,
  __X___XX,XXXXXX__,
  __X___X_,_XX__X__,
  __X___X_,_XX_XX__,
  __X___X_,_XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8F49[ 32] = { /* code 8F49 */
  ___X____,__X_____,
  ___X____,__X_____,
  XXXXXX_X,XXXXXXX_,
  XXXXXX_X,XXXXXXX_,
  ___X____,__X_____,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _XXXXX_X,XXXXXX__,
  _X_X_X_X,__X__X__,
  _X_X_X_X,XXXXXX__,
  _XXXXX__,__X_XX__,
  ___X__XX,XXXXXXX_,
  XXXXXX__,____X___,
  XXXXXX_X,XXXXXXX_,
  ___X____,X___X___,
  ___X____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8F6C[ 30] = { /* code 8F6C */
  __X_____,__X_____,
  __X_____,_XX_____,
  XXXXXX_X,XXXXXX__,
  XXXXXX_X,XXXXXX__,
  _XXX____,_X______,
  _X_X__XX,XXXXXXX_,
  _X_X__XX,XXXXXXX_,
  XXXXXX__,X_______,
  XXXXXX__,XXXXXX__,
  ___XXX__,XXXXXX__,
  XXXXXX__,X___XX__,
  XXXX____,XXXXX___,
  ___X____,__XX____,
  ___X____,___XX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8FD0[ 30] = { /* code 8FD0 */
  _X______,________,
  __XX__XX,XXXXXX__,
  ___X__XX,XXXXXX__,
  ________,________,
  XXXX_XXX,XXXXXXX_,
  XXXX_XXX,XXXXXXX_,
  __XX____,XX______,
  _XX_____,X__XX___,
  XXXX___X,X__XX___,
  XXXX___X,____XX__,
  ___X__XX,__XXXX__,
  __XX__XX,XXX__XX_,
  _XXX_XXX,________,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8FDF[ 30] = { /* code 8FDF */
  _X______,________,
  __XX__XX,XXXXXX__,
  ___X__XX,XXXXXX__,
  ______XX,_____X__,
  XXXX__XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  __XX__XX,X_______,
  _XX___X_,XXX_____,
  XXXX__X_,__XX____,
  XXXX_XX_,___XX___,
  ___X_XX_,____XX__,
  __XXXX__,_____X__,
  _XXX____,________,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9006[ 32] = { /* code 9006 */
  _X____XX,____X___,
  __XX___X,X__XX___,
  ___X____,________,
  _____XXX,XXXXXXX_,
  XXXX_XXX,XXXXXXX_,
  XXXX____,_XX_____,
  __XX__X_,_XX__X__,
  _XX___X_,_XX__X__,
  XXXX__X_,_XX__X__,
  XXXX__XX,XXXXXX__,
  ___X__XX,XXXXXX__,
  __XX____,_X______,
  __XX___X,XX______,
  _XXXX__X,________,
  _X__XXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_901F[ 30] = { /* code 901F */
  _X______,_XX_____,
  __X__XXX,XXXXXXX_,
  ___X_XXX,XXXXXXX_,
  ________,_XX_____,
  XXXXX_XX,XXXXXX__,
  XXXXX_X_,_XX__X__,
  __XX__X_,_XX__X__,
  _XX___XX,XXXXXX__,
  XXXXX___,XXXX____,
  XXXXX__X,XXXXX___,
  ___X__XX,_XX_XX__,
  __XX_X__,_XX___X_,
  __XX____,________,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_904B[ 30] = { /* code 904B */
  _X___XXX,XXXXXXX_,
  _XXX_XX_,_XX__XX_,
  ___X_XXX,XXXXXXX_,
  XXXX____,_XX_____,
  XXXX_XXX,XXXXXX__,
  __XX_XX_,_XX__X__,
  _XX__XXX,XXXXXX__,
  XXXX_XX_,_XX__X__,
  XXXX_XXX,XXXXXX__,
  ___X____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX____,_XX_____,
  _XXXX___,________,
  XX__XXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9072[ 30] = { /* code 9072 */
  _X___XXX,XXXXXX__,
  _XX__X__,_____X__,
  __X__XXX,XXXXXX__,
  XXXX_X__,________,
  XXXX_X_X,__X__X__,
  __XX_X__,XXX_XX__,
  _XX__X_X,X_X__X__,
  XX___X__,X_X_____,
  XXXX_X_X,XXXXXX__,
  XXXX_XXX,__X_____,
  __XXXXXX,XXXXXXX_,
  __X_X___,__X_____,
  _XXXX___,__X_____,
  _X_XXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_91DD[ 32] = { /* code 91DD */
  ___XX___,___X____,
  ___XX___,___X____,
  __XX_X__,___X____,
  _XX__XX_,___X____,
  XXXXXXX_,___X____,
  __XXXX__,XXXXXXX_,
  ___XX___,XXXXXXX_,
  XXXXXXX_,___X____,
  XXXXXXX_,___X____,
  ___XX___,___X____,
  _X_XX_X_,___X____,
  _X_XXXX_,___X____,
  _X_XXX__,___X____,
  __XXXXX_,___X____,
  XXXXXXX_,___X____,
  XXXX____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9418[ 30] = { /* code 9418 */
  ___X____,_XX_____,
  __XXX_XX,XXXXXXX_,
  _XX_XX_X,X___X___,
  _X______,X__XX___,
  XXXXX_XX,XXXXXXX_,
  XXXXX___,________,
  __XX__XX,XXXXXX__,
  XXXXXXXX,__X__X__,
  XXXXXXXX,XXXXXX__,
  __XX__XX,__X__X__,
  XXXXXXXX,XXXXXX__,
  __XXX___,__X_____,
  __XXX_XX,XXXXXX__,
  XXXXX___,__X_____,
  XX____XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9488[ 30] = { /* code 9488 */
  __XX____,__XX____,
  __XX____,__XX____,
  __XXXXX_,__XX____,
  _XXXXXX_,__XX____,
  _XX_____,__XX____,
  XXXXXX__,__XX____,
  _XXXXX_X,XXXXXXX_,
  ___X___X,XXXXXXX_,
  XXXXXXX_,__XX____,
  XXXXXXX_,__XX____,
  ___X____,__XX____,
  ___X__X_,__XX____,
  ___X_XX_,__XX____,
  ___XXX__,__XX____,
  ___X____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_949F[ 30] = { /* code 949F */
  __X_____,__X_____,
  _XX_____,__X_____,
  _XXXXX__,__X_____,
  _XXXXXXX,XXXXXXX_,
  _X____XX,XXXXXXX_,
  XXXXX_XX,__X__XX_,
  _XXXX_XX,__X__XX_,
  __XX__XX,__X__XX_,
  XXXXXXXX,__X__XX_,
  XXXXXXXX,XXXXXXX_,
  __XX__XX,XXXXXXX_,
  __XX____,__X_____,
  __XX_X__,__X_____,
  __XXXX__,__X_____,
  __XXX___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9593[ 30] = { /* code 9593 */
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X_______,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__XX___,_X__X___,
  X__XXXXX,XX__X___,
  X__XX___,_X__X___,
  X__XX___,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX_XX___,
  X_______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_95F4[ 32] = { /* code 95F4 */
  X_______,________,
  XX__XXXX,XXXXX___,
  _XX_XXXX,XXXXX___,
  __X_____,____X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__X____,_X__X___,
  X__X____,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X__X____,_X__X___,
  X__XXXXX,XX__X___,
  X__XXXXX,XX__X___,
  X_______,____X___,
  X_______,__XXX___,
  X_______,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9806[ 30] = { /* code 9806 */
  _X___XXX,XXXXXXX_,
  _X_X_XXX,XXXXXXX_,
  _X_X_XX_,__XX____,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,X____X__,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,X____X__,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,X____X__,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,XXXXXX__,
  XX_X_XX_,_XX_X___,
  XX_X_XX_,XX_XXX__,
  X____XXX,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9813[ 30] = { /* code 9813 */
  ___X___X,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXX_,__XX____,
  ___X____,XXXXXX__,
  ___X____,XXXXXX__,
  _X_X_XX_,X____X__,
  _X_X_XX_,XXXXXX__,
  _X_X_XX_,X____X__,
  _X_X_XX_,XXXXXX__,
  _XXXXXX_,X____X__,
  _XXXXXX_,XXXXXX__,
  ___X____,XXXXXX__,
  ___X_XX_,_XX_X___,
  ___XXXX_,XX_X_X__,
  ___XX__X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_987A[ 30] = { /* code 987A */
  _X___XXX,XXXXXXX_,
  _X_XXXXX,XXXXXXX_,
  _X_XXXX_,__XX____,
  _X_XXXX_,XXXXXX__,
  _X_XXXX_,XXXXXX__,
  _X_XXXX_,X____X__,
  _X_XXXX_,X_XX_X__,
  _X_XXXX_,X_XX_X__,
  _X_XXXX_,X_XX_X__,
  _X_XXXX_,X_XX_X__,
  _X_XXXX_,X_XX_X__,
  _X_XXXX_,__X_X___,
  _X_XXXX_,__X_XX__,
  XX_XXXX_,XX___XX_,
  X____XXX,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_987F[ 30] = { /* code 987F */
  ___X___X,XXXXXXX_,
  ___X___X,XXXXXXX_,
  XXXXXXX_,__XX____,
  XXXXXXX_,XXXXXX__,
  _X_X__X_,XXXXXX__,
  _X_X__X_,X____X__,
  _X_X__X_,X_XX_X__,
  _X_X__X_,X_XX_X__,
  _XXXXXX_,X_XX_X__,
  _XXXXXX_,X_XX_X__,
  ___X____,X_XX_X__,
  ___X__X_,__X_____,
  ___X_XX_,_XX_X___,
  ___XXX__,XX_XXX__,
  ___XX__X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9A5F[ 30] = { /* code 9A5F */
  _XXXX_XX,XX_XXXX_,
  _X_X__XX,_X_X_XX_,
  _XXXX_XX,XX_XXX__,
  _X_X__XX,_X__XX__,
  _XXXX_XX,XX__XX__,
  _X_X__XX,_X_XXXX_,
  _X_X__XX,XXXX__X_,
  _XXXXX__,_X_XXX__,
  _____X_X,XXX_____,
  _X___X__,X_X__X__,
  XXXX_X_X,X_X__X__,
  X_XX_X_X,X_X_XX__,
  X_XX_X_X,X_X_XX__,
  X_XXXXXX,XXX_X_X_,
  ___XX_X_,__X_X_X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9AA4[ 32] = { /* code 9AA4 */
  XXXXX_XX,XX_XXXX_,
  XXXXX_X_,XX_XXXX_,
  ____X_XX,XX_X_X__,
  _X_XX_X_,XXXXXX__,
  _X_XX_XX,XX__XX__,
  _X_XX_X_,XX__XX__,
  _X_XX_X_,XX_X_XX_,
  _XXXX_XX,XXXX__X_,
  XXXXX___,___XXX__,
  ____X_XX,XXXXX_X_,
  __X_X___,X_XXXXX_,
  XXX_X__X,__X_XX__,
  XX__XXX_,__X_XX__,
  ____X__X,X_X__XX_,
  __XXXXXX,__X___X_,
  __XXX___,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[113] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{   5,   2,   1,  11,   7, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  15,   4, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002E } /* code 002E, FULL STOP */
  ,{   8,  15,   0,   4,   8, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_002F } /* code 002F, SOLIDUS */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  13,   2,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0039 } /* code 0039, DIGIT NINE */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  13,   1,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  13,   1,   4,  13, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  13,   2,   4,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  13,   1,   4,   7, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  13,   2,   4,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  13,   2,   4,  14, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  12,  13,   1,   4,  14, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  12,  16,   1,   4,  14, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  13,   1,   4,  13, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  13,   0,   4,  18, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   9,   1,   8,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  14,   0,   3,   6, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  17,  -2,   4,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  14,   1,   3,  10, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  14,   1,   3,   5, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,   9,   1,   8,  16, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   9,   1,   8,   7, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   8, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  12,   0,   5,   7, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,   9,   0,   8,  14, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  13,   0,   8,   9, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   0,   8,   8, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_503C } /* code 503C */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_507F } /* code 507F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_511F } /* code 511F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_516C } /* code 516C */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5206 } /* code 5206 */
  ,{  14,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_529B } /* code 529B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_53F7 } /* code 53F7 */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5411 } /* code 5411 */
  ,{  13,  14,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5708 } /* code 5708 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5C3A } /* code 5C3A */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_5EF6 } /* code 5EF6 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_626D } /* code 626D */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_65B9 } /* code 65B9 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_65F6 } /* code 65F6 */
  ,{  14,  16,   2,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6642 } /* code 6642 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6807 } /* code 6807 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6A19 } /* code 6A19 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_6B65 } /* code 6B65 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_725B } /* code 725B */
  ,{  11,  15,   3,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_76EE } /* code 76EE */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_79D2 } /* code 79D2 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7C73 } /* code 7C73 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7DE8 } /* code 7DE8 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_7F16 } /* code 7F16 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_865F } /* code 865F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8865 } /* code 8865 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_88DC } /* code 88DC */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8F49 } /* code 8F49 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8F6C } /* code 8F6C */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8FD0 } /* code 8FD0 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_8FDF } /* code 8FDF */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9006 } /* code 9006 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_901F } /* code 901F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_904B } /* code 904B */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9072 } /* code 9072 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_91DD } /* code 91DD */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9418 } /* code 9418 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9488 } /* code 9488 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_949F } /* code 949F */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9593 } /* code 9593 */
  ,{  13,  16,   2,   2,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_95F4 } /* code 95F4 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9806 } /* code 9806 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9813 } /* code 9813 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_987A } /* code 987A */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_987F } /* code 987F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9A5F } /* code 9A5F */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_9AA4 } /* code 9AA4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop51 = {
   0x9AA4 /* first character */
  ,0x9AA4 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[112] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop50 = {
   0x9A5F /* first character */
  ,0x9A5F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[111] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop49 = {
   0x987F /* first character */
  ,0x987F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[110] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop48 = {
   0x987A /* first character */
  ,0x987A /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[109] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop47 = {
   0x9813 /* first character */
  ,0x9813 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[108] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop46 = {
   0x9806 /* first character */
  ,0x9806 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[107] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop45 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[106] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop44 = {
   0x9593 /* first character */
  ,0x9593 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[105] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop43 = {
   0x949F /* first character */
  ,0x949F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[104] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop42 = {
   0x9488 /* first character */
  ,0x9488 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[103] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop41 = {
   0x9418 /* first character */
  ,0x9418 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[102] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop40 = {
   0x91DD /* first character */
  ,0x91DD /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[101] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop39 = {
   0x9072 /* first character */
  ,0x9072 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[100] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop38 = {
   0x904B /* first character */
  ,0x904B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 99] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop37 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 98] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop36 = {
   0x9006 /* first character */
  ,0x9006 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 97] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop35 = {
   0x8FDF /* first character */
  ,0x8FDF /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 96] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop34 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 95] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop33 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 94] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop32 = {
   0x8F49 /* first character */
  ,0x8F49 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 93] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop31 = {
   0x88DC /* first character */
  ,0x88DC /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 92] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop30 = {
   0x8865 /* first character */
  ,0x8865 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 91] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop29 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 90] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop28 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 89] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop27 = {
   0x7DE8 /* first character */
  ,0x7DE8 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 88] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop26 = {
   0x7C73 /* first character */
  ,0x7C73 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 87] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop25 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 86] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop24 = {
   0x76EE /* first character */
  ,0x76EE /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 85] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop23 = {
   0x725B /* first character */
  ,0x725B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 84] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop22 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 83] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop21 = {
   0x6A19 /* first character */
  ,0x6A19 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 82] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop20 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 81] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop19 = {
   0x6642 /* first character */
  ,0x6642 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop18 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop17 = {
   0x65B9 /* first character */
  ,0x65B9 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop16 = {
   0x626D /* first character */
  ,0x626D /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop15 = {
   0x5EF6 /* first character */
  ,0x5EF6 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop14 = {
   0x5C3A /* first character */
  ,0x5C3A /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop13 = {
   0x5708 /* first character */
  ,0x5708 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop12 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop11 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop10 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop9 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop8 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop7 = {
   0x511F /* first character */
  ,0x511F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop6 = {
   0x507F /* first character */
  ,0x507F /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop5 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop4 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 40] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop2 = {
   0x002D /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_JS_2_Step2_1_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

