/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Net_AP_Info_Microsoft JhengHei_22B.c          *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_Net_AP_Info_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0021[ 13] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0022[  4] = { /* code 0022, QUOTATION MARK */
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0023[ 22] = { /* code 0023, NUMBER SIGN */
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X_______,
  XXXXXXXX,XXX_____,
  ___X___X,X_______,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  __X___X_,________,
  _X____X_,________,
  _X___X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ___X____,
  __XXXX__,
  _XXXXXX_,
  XX_X__X_,
  XX_X____,
  XX_X____,
  XXXX____,
  _XXX____,
  __XXXX__,
  ___XXXX_,
  ___X__XX,
  X__X__XX,
  XXXXXXXX,
  _XXXXX__,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0025[ 26] = { /* code 0025, PERCENT SIGN */
  __XXXX__,__XX____,
  _XXXXXX_,_XX_____,
  XX___XX_,_XX_____,
  XX___XX_,XX______,
  XX___XXX,X_______,
  XXXXXX_X,X_______,
  _XXXX_XX,_XXXX___,
  _____XX_,XXXXXX__,
  _____XX_,XX__XX__,
  ____XX__,XX__XX__,
  ___XX___,XX__XX__,
  ___XX___,XXXXXX__,
  __XX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0026[ 26] = { /* code 0026, AMPERSAND */
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX___X,X_______,
  __XX___X,X__XX___,
  __XX__XX,X__XX___,
  ___XXXXX,___XX___,
  __XXXXXX,___XX___,
  _XXX__XX,X_XX____,
  XX______,XXXX____,
  XX______,_XX_____,
  XXX____X,XXX_____,
  _XXXXXXX,X_XXXX__,
  __XXXXXX,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0027[  4] = { /* code 0027, APOSTROPHE */
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXX_____,
  _XX_____,
  _XX_____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  __XX____,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002A[  7] = { /* code 002A, ASTERISK */
  ________,
  ___X____,
  X__X__XX,
  XXXXXXXX,
  ___XX___,
  __XX_X__,
  _X____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002B[ 20] = { /* code 002B, PLUS SIGN */
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002C[  4] = { /* code 002C, COMMA */
  XX______,
  XX______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002F[ 15] = { /* code 002F, SOLIDUS */
  ______XX,
  ______XX,
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0030[ 13] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0031[ 13] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XXXXX___,
  X__XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0032[ 13] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _XXXXXX_,
  _X____XX,
  ______XX,
  ______XX,
  ______X_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0033[ 13] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XXXXXXX_,
  X____XX_,
  _____XX_,
  ____XXX_,
  _XXXX___,
  _XXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0034[ 26] = { /* code 0034, DIGIT FOUR */
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___X__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _X____XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0035[ 13] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0036[ 13] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  __XXXXX_,
  _XXX____,
  _XX_____,
  XX______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0037[ 26] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0038[ 13] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _XXXXXXX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXX___,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0039[ 13] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XXXXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003A[  9] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003B[ 11] = { /* code 003B, SEMICOLON */
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _X______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003C[  9] = { /* code 003C, LESS-THAN SIGN */
  _______X,
  _____XXX,
  ___XXX__,
  _XXX____,
  XX______,
  _XXX____,
  ___XXX__,
  _____XXX,
  _______X};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003D[ 12] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ________,________,
  ________,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003E[  9] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  XXX_____,
  __XXX___,
  ____XXX_,
  ______XX,
  ____XXX_,
  __XXX___,
  XXX_____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003F[ 13] = { /* code 003F, QUESTION MARK */
  _XXXX___,
  XXXXXXX_,
  X____XX_,
  _____XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  ________,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0040[ 28] = { /* code 0040, COMMERCIAL AT */
  _____XXX,XXX_____,
  ___XXX__,___XX___,
  __XX____,____XX__,
  _XX___XX,XX___X__,
  _XX__XX_,_X____X_,
  XX__XX__,_X____X_,
  XX__XX__,_X____X_,
  XX__XX__,_X____X_,
  XX__XX__,_X____X_,
  XX__XX__,XX___X__,
  _XX__XXX,_XXXX___,
  _XXX____,________,
  __XXX___,__X_____,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,________,
  _XXX____,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0045[ 13] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0046[ 13] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,__X_____,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX____XX,XXX_____,
  XX____XX,XXX_____,
  XX______,_XX_____,
  _XX_____,_XX_____,
  _XXX____,_XX_____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XXX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XXX__,________,
  XXXXX___,________,
  XX_XXX__,________,
  XX__XXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004C[ 13] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004D[ 26] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__X___,X__XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,_XX_____,
  XXXX____,_XX_____,
  XXXX____,_XX_____,
  XX_XX___,_XX_____,
  XX_XXX__,_XX_____,
  XX__XX__,_XX_____,
  XX___XX_,_XX_____,
  XX___XX_,_XX_____,
  XX____XX,_XX_____,
  XX_____X,XXX_____,
  XX_____X,XXX_____,
  XX______,XXX_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0050[ 13] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XXXXXXX_,
  XX___XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  XXXXXXX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,________,
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0053[ 13] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  _XX_____,
  _XXXXX__,
  ___XXXX_,
  _____XXX,
  ______XX,
  X_____XX,
  XXXXXXX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ____XX_X,________,
  ____XXXX,________,
  ____XXXX,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0057[ 39] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  __X___XX,__XX___X,________,
  __XX__XX,__XX__XX,________,
  __XX__XX,__XX__XX,________,
  ___X__X_,___X__X_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0058[ 26] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,_XX_____,
  _XX_____,XX______,
  __X____X,X_______,
  __XX__XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  _____X__,________,
  ____XXX_,________,
  ___XX_XX,________,
  __XX___X,X_______,
  __XX____,X_______,
  _XX_____,XX______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX____,XX______,
  __XX___X,X_______,
  ___XX__X,X_______,
  ___XXXXX,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005A[ 26] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005B[ 17] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005C[ 15] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XXX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005D[ 17] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ____X___,________,
  ___XXX__,________,
  ___X_X__,________,
  __XX_XX_,________,
  __X___X_,________,
  _XX___XX,________,
  _X_____X,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0060[  3] = { /* code 0060, GRAVE ACCENT */
  XX______,
  _XX_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXX_,
  _XXXXXXX,
  _X____XX,
  ______XX,
  _XXXXXXX,
  XXX___XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0062[ 28] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0067[ 26] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _X____XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0068[ 28] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006A[ 17] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006B[ 28] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX_XX___,________,
  XX___XX_,________,
  XX____XX,________,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX__XXX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0071[ 26] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XXXXXX__,
  XX___X__,
  XXXX____,
  _XXXX___,
  ____XX__,
  X___XX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____XX,____XX__,
  XX____XX,____XX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__X__,X__XX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,_XXX____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0078[ 18] = { /* code 0078, LATIN SMALL LETTER X */
  XX_____X,X_______,
  _XX___XX,________,
  __X__XX_,________,
  ___XXX__,________,
  ____X___,________,
  ___XXX__,________,
  __XX__X_,________,
  _XX___XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0079[ 26] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___X_X__,________,
  ___XXX__,________,
  ____XX__,________,
  ___XX___,________,
  __XXX___,________,
  XXXX____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007C[ 18] = { /* code 007C, VERTICAL LINE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007E[  6] = { /* code 007E, TILDE */
  _XXX____,X_______,
  X__XXX__,X_______,
  X____XXX,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_CharInfo[94] = {
   {   2,  13,   2,   4,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   4,   2,   4,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0022 } /* code 0022, QUOTATION MARK */
  ,{  11,  11,   0,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0023 } /* code 0023, NUMBER SIGN */
  ,{   8,  16,   1,   3,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0024 } /* code 0024, DOLLAR SIGN */
  ,{  14,  13,   1,   4,  15, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0025 } /* code 0025, PERCENT SIGN */
  ,{  14,  13,   1,   4,  15, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0026 } /* code 0026, AMPERSAND */
  ,{   1,   4,   2,   4,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0027 } /* code 0027, APOSTROPHE */
  ,{   5,  16,   1,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  16,   0,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   7,   0,   4,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002A } /* code 002A, ASTERISK */
  ,{   9,  10,   2,   7,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002B } /* code 002B, PLUS SIGN */
  ,{   2,   4,   0,  15,   4, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002C } /* code 002C, COMMA */
  ,{   5,   2,   1,  11,   7, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  15,   4, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002E } /* code 002E, FULL STOP */
  ,{   8,  15,   0,   4,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_002F } /* code 002F, SOLIDUS */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  13,   2,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  13,   0,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   9,   1,   8,   4, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003A } /* code 003A, COLON */
  ,{   3,  11,   0,   8,   4, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003B } /* code 003B, SEMICOLON */
  ,{   8,   9,   2,   7,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003C } /* code 003C, LESS-THAN SIGN */
  ,{   9,   6,   2,   9,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003D } /* code 003D, EQUALS SIGN */
  ,{   8,   9,   3,   7,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   7,  13,   1,   4,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_003F } /* code 003F, QUESTION MARK */
  ,{  15,  14,   1,   4,  18, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0040 } /* code 0040, COMMERCIAL AT */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  13,   1,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  13,   1,   4,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  13,   2,   4,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  13,   1,   4,   7, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  13,   2,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  13,   2,   4,  17, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  13,   2,   4,  14, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  12,  13,   1,   4,  14, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  13,   2,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  12,  16,   1,   4,  14, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  13,   1,   4,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  13,   0,   4,  18, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,  17,   2,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   7,  15,   0,   4,   7, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   4,  17,   0,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   9,   8,   2,   4,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   8,   1,   0,  19,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   3,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0060 } /* code 0060, GRAVE ACCENT */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   9,   1,   8,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  14,   0,   3,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  17,  -2,   4,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  14,   1,   3,  10, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  14,   1,   3,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,   9,   1,   8,  16, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   9,   1,   8,   7, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  12,   0,   5,   7, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  11, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,   9,   0,   8,  14, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  13,   0,   8,   9, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   0,   8,   8, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   4,  16,   1,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   2,  18,   2,   3,   5, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007C } /* code 007C, VERTICAL LINE */
  ,{   4,  16,   1,   4,   6, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   9,   3,   2,  10,  13, acGUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_007E } /* code 007E, TILDE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_Prop1 = {
   0x0021 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Net_AP_Info_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

