/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_Tool_Mode_Microsoft JhengHei_26B.c            *
* Font:        微軟正黑體                                            *
* Height:      26                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  26                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260105-全部頁面字庫分門別類ab8f-檔案和註解整理乾淨的\01-20250105-字庫檔案\最後\Font_Pg_Tool_Mode_Microsoft JhengHei_26B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_0020[  1] = { /* code 0020, SPACE */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_5B9A[ 57] = { /* code 5B9A */
  ________,XX______,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XX______,
  _XX_____,________,XX______,
  _XX_____,________,XX______,
  ___XXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,________,
  ________,_XX_____,________,
  ____XX__,_XX_____,________,
  ____XX__,_XX_____,________,
  ____XX__,_XXXXXXX,X_______,
  ___XXX__,_XXXXXXX,X_______,
  ___XXX__,_XX_____,________,
  ___XXXX_,_XX_____,________,
  __XX_XXX,_XX_____,________,
  _XXX__XX,XXX_____,________,
  _XX____X,XXXXXXXX,XXX_____,
  _X______,_XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_7F6E[ 54] = { /* code 7F6E */
  _XXXXXXX,XXXXXXXX,XX______,
  _XX___XX,___XX___,XX______,
  _XX___XX,___XX___,XX______,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,XX______,________,
  ________,XX______,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  ___XX___,_______X,________,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_8A2D[ 54] = { /* code 8A2D */
  ___XX___,__XXXXXX,________,
  ___XX___,__XXXXXX,________,
  XXXXXXXX,__XX___X,________,
  XXXXXXXX,__XX___X,________,
  ________,__XX___X,________,
  _XXXXXX_,_XX____X,XXX_____,
  _XXXXXX_,XXX____X,XXX_____,
  ________,_X______,________,
  _XXXXXX_,________,________,
  _XXXXXX_,XXXXXXXX,XX______,
  ________,XXXXXXXX,XX______,
  _XXXXXX_,__XX___X,X_______,
  _XXXXXX_,__XX__XX,X_______,
  _XX__XX_,___XXXXX,________,
  _XX__XX_,____XXX_,________,
  _XXXXXX_,__XXXXXX,________,
  _XXXXXX_,XXXX__XX,XXX_____,
  _XX__XX_,XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_8BBE[ 57] = { /* code 8BBE */
  __X_____,________,________,
  __XX____,XXXXXXXX,________,
  __XXX___,XXXXXXXX,________,
  ___XX___,XX____XX,________,
  ____X___,XX____XX,________,
  ________,X_____XX,________,
  XXXX___X,X_____XX,XXX_____,
  XXXX__XX,______XX,XXX_____,
  __XX____,________,________,
  __XX__XX,XXXXXXXX,X_______,
  __XX__XX,XXXXXXXX,X_______,
  __XX____,XX_____X,X_______,
  __XX____,XX____XX,________,
  __XX____,_XX__XX_,________,
  __XX_X__,__XXXX__,________,
  __XXXXX_,__XXXX__,________,
  __XXXX__,XXXXXXXX,X_______,
  ___X_XXX,XX____XX,XXX_____,
  ______XX,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_91CD[ 57] = { /* code 91CD */
  ________,_____XXX,X_______,
  __XXXXXX,XXXXX___,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  __XXXXXX,XXXXXXXX,X_______,
  __XX____,_XX____X,X_______,
  __XX____,_XX____X,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  __XX____,_XX____X,X_______,
  __XX____,_XX____X,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_9810[ 54] = { /* code 9810 */
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _____XX_,_____XX_,________,
  __X__XX_,____XX__,________,
  __XXXX__,_XXXXXXX,XX______,
  ___XX___,_XXXXXXX,XX______,
  ___XXX__,_XX_____,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,_XX_____,XX______,
  ___XX_XX,_XX_____,XX______,
  ___XX_XX,_XXXXXXX,XX______,
  ___XX__X,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XXXXXXX,XX______,
  ___XX___,_XXXXXXX,XX______,
  ___XX___,___XX_XX,________,
  _XXXX___,_XXX___X,XX______,
  _XXXX___,XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_9884[ 57] = { /* code 9884 */
  _XXXXXXX,_XXXXXXX,XXX_____,
  _XXXXXXX,_XXXXXXX,XXX_____,
  ______XX,_____XX_,________,
  __XX_XX_,_____XX_,________,
  __XXXXX_,__XXXXXX,XX______,
  ___XXX__,__XXXXXX,XX______,
  ____XXX_,__X_____,XX______,
  XXXXXXXX,X_X__XX_,XX______,
  XXXXXXXX,X_X__XX_,XX______,
  ____XX_X,X_X__XX_,XX______,
  ____XX_X,X_X__XX_,XX______,
  ____XX_X,X_X__XX_,XX______,
  ____XX_X,__X__X__,XX______,
  ____XX__,__X_XX__,XX______,
  ____XX__,____XX_X,________,
  ____XX__,___XX_XX,X_______,
  ____XX__,__XX____,XX______,
  __XXXX__,_XX_____,_XX_____,
  __XXX___,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[8] = {
   {   1,   1,   0,  21,   5, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_0020 } /* code 0020, SPACE */
  ,{  19,  19,   1,   3,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_5B9A } /* code 5B9A */
  ,{  19,  18,   1,   4,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_7F6E } /* code 7F6E */
  ,{  19,  18,   1,   4,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_8A2D } /* code 8A2D */
  ,{  19,  19,   1,   3,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_8BBE } /* code 8BBE */
  ,{  19,  19,   1,   3,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_91CD } /* code 91CD */
  ,{  19,  18,   1,   4,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_9810 } /* code 9810 */
  ,{  19,  19,   1,   4,  21, acGUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_9884 } /* code 9884 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop8 = {
   0x9884 /* first character */
  ,0x9884 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop7 = {
   0x9810 /* first character */
  ,0x9810 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop6 = {
   0x91CD /* first character */
  ,0x91CD /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop5 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop4 = {
   0x8A2D /* first character */
  ,0x8A2D /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop3 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop2 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,26 /* height of font  */
  ,26 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_Tool_Mode_MicrosoftJhengHei_26B_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

