/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_JS_0_Job_Microsoft JhengHei_22B.c             *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_JS_0_Job_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4EFB[ 30] = { /* code 4EFB */
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __X_____,_X______,
  _XX_____,_X______,
  _XX_____,_X______,
  XXX_____,_X______,
  XXX_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X_XXXX,XXXXXXX_,
  __X_XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4F5C[ 30] = { /* code 4F5C */
  ___XX__X,X_______,
  ___X___X,________,
  __XX___X,XXXXXXX_,
  __XX__XX,XXXXXXX_,
  _XX___X_,XX______,
  _XX__XX_,XX______,
  XXX_XX__,XXXXXXX_,
  __X__X__,XXXXXXX_,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,XXXXXXX_,
  __X_____,XXXXXXX_,
  __X_____,XX______,
  __X_____,XX______,
  __X_____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4FE1[ 34] = { /* code 4FE1 */
  ___XX___,XX______,
  ___X____,_X______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  _XXX____,________,
  _XXX_XXX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  XXXX____,________,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX____,________,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX_XX_,____XX__,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX_XX_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_505C[ 30] = { /* code 505C */
  __XX____,XX______,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  _XX__XXX,XXXXXX__,
  _XX__XX_,____XX__,
  XXX__XXX,XXXXXX__,
  XXX_____,________,
  __X_XXXX,XXXXXXX_,
  __X_XX__,_____XX_,
  __X___XX,XXXXX___,
  __X_____,_XX_____,
  __X_____,_XX_____,
  __X_____,_XX_____,
  __X____X,XX______,
  __X____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5173[ 30] = { /* code 5173 */
  ____XX__,XXX_____,
  ____XX__,XXX_____,
  ___XX___,__XX____,
  __XX____,___XX___,
  __X_XXXX,XXXXX___,
  _XX_XXXX,XXXXXX__,
  _X_____X,______X_,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,XX______,
  _____XX_,_XX_____,
  ___XXX__,___XX___,
  XXXXX___,____XX__,
  XXX_____,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5177[ 30] = { /* code 5177 */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____X___,__XX____,
  _XXXX___,___XXX__,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_52A1[ 30] = { /* code 52A1 */
  _____X__,________,
  ____XXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  _XXXX___,__XXX___,
  XX__XXX_,XXX_____,
  ______XX,XX______,
  XXXXXXX_,XXXXXXX_,
  XXX___XX,___XXXX_,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ______X_,____XX__,
  _____XX_,____XX__,
  ___XXX__,____X___,
  XXXXX___,_XXXX___,
  _XX_____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ________,___XX___,
  ________,___X____,
  _______X,XXXX____,
  _______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_540D[ 30] = { /* code 540D */
  ______XX,________,
  _____XXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  ___XXX__,___XX___,
  __XXXXX_,__XX____,
  _X____XX,_X______,
  _______X,X_______,
  ____XXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _X__X___,____XX__,
  ____X___,____XX__,
  ____X___,____XX__,
  ____XXXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  ____X___,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_591A[ 30] = { /* code 591A */
  ______XX,________,
  _____XXX,XXXXX___,
  ___XXXXX,XXXXX___,
  __XXXX__,__XX____,
  _XX__XX_,_XX_____,
  ______XX,XX______,
  ____XXXX,_XX_____,
  XXXXXX__,XXXXXXX_,
  _XX____X,XXXXXXX_,
  _____XXX,_____X__,
  ___XXXXX,___XX___,
  __XX____,XXXX____,
  ______XX,XXX_____,
  _XXXXXXX,X_______,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5B8C[ 34] = { /* code 5B8C */
  ______XX,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__,
  _X_XXXXX,XXXX_X__,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _____X__,XX______,
  ____XX__,XX___XX_,
  ____XX__,XX___XX_,
  __XXX___,XXXXXXX_,
  XXXX____,_XXXXX__,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5DE5[ 28] = { /* code 5DE5 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5E8F[ 32] = { /* code 5E8F */
  _______X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,________,
  _XX_XXXX,XXXXXX__,
  _XX_XXXX,XXXXXX__,
  _XX_____,__XXX___,
  _XX___XX,XXX_____,
  _XX____X,XX______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,XX__XX__,
  _XX_____,XX__X___,
  XX____XX,XX______,
  _X____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5F00[ 30] = { /* code 5F00 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ___XX___,__X_____,
  ___XX___,__X_____,
  ___X____,__X_____,
  __XX____,__X_____,
  _XX_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_6210[ 32] = { /* code 6210 */
  ________,_X_XX___,
  ________,_X___X__,
  ________,_X______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __X_____,_X______,
  __XXXXX_,_X___X__,
  __XXXXX_,_XX_XX__,
  _XX___X_,_XX_X___,
  _XX___X_,_XXXX___,
  _XX___X_,__XX____,
  _XX___X_,__X_____,
  _X_XXXX_,_XXX__X_,
  _X__XX__,XX_X_XX_,
  XX_____X,X__XXXX_,
  ______X_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_62E9[ 30] = { /* code 62E9 */
  __XX__XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  XXXXX__X,___XX___,
  XXXXX__X,X_XX____,
  __XX____,XXX_____,
  __XX___X,X_XXX___,
  __XXXXX_,_XX__XX_,
  _XXXX_XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  XXXX____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX____,_XX_____,
  _XXX____,_XX_____,
  _XX_____,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_64C7[ 30] = { /* code 64C7 */
  __X__XXX,XXXXXXX_,
  __X__X__,X_XX_XX_,
  XXXX_XXX,XXXXXXX_,
  XXXX____,_X______,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  __XX_XXX,XXXXXXX_,
  _XXX___X,___XX___,
  XXXX___X,X__XX___,
  X_X__XXX,XXXXXX__,
  __X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,_X______,
  XXX_____,_X______,
  _XX_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_66F4[ 30] = { /* code 66F4 */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __X____X,____XX__,
  __XXXXXX,XXXXXX__,
  __X____X,____XX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  ___X__XX,________,
  ___XXXX_,________,
  ____XXXX,XX______,
  XXXXXXXX,XXXXXXX_,
  XXX_____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_6B62[ 30] = { /* code 6B62 */
  _______X,X_______,
  _______X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,XXXXXX__,
  __XX___X,XXXXXX__,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_786E[ 30] = { /* code 786E */
  ________,_X______,
  XXXXXX__,XX______,
  XXXXXX_X,XXXXXX__,
  __XX__XX,XXXXXX__,
  __X___XX,XXXXXXX_,
  _XX____X,XXXXXXX_,
  _XXXXX_X,__XX_XX_,
  _XXXXX_X,XXXXXXX_,
  XXX_XX_X,XXXXXXX_,
  _XX_XX_X,__XX_XX_,
  _XX_XX_X,XXXXXXX_,
  _XX_XX_X,_____XX_,
  _XXXXX_X,_____XX_,
  _XXXXXXX,___XXXX_,
  _XX____X,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_78BA[ 32] = { /* code 78BA */
  ________,__X_____,
  XXXXXX__,_XX_____,
  XXXXXXXX,XXXXXXX_,
  __X___XX,XXXXXXX_,
  __X___XX,XX___XX_,
  _XX_____,X_XX____,
  _XXXX_XX,XXXXXXX_,
  XXXXX_XX,X__X____,
  XXX_X__X,XXXXXX__,
  _XX_X__X,X__X____,
  _XX_X__X,X__X____,
  _XX_X__X,XXXXXX__,
  _XX_X__X,X__X____,
  _XXXX__X,X__X____,
  _XXXX__X,XXXXXXX_,
  _XX_X__X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_79F0[ 30] = { /* code 79F0 */
  XXXXXX__,XX______,
  _XXX____,X_______,
  ___X____,XXXXXXX_,
  ___X___X,XXXXXXX_,
  XXXXXX_X,__X__X__,
  XXXXXXXX,__X__X__,
  __XXX___,__X_XX__,
  __XXXX_X,X_X_X___,
  __XX_X_X,X_X_X___,
  _X_X___X,__X_XX__,
  _X_X__XX,__X__X__,
  X__X__X_,__X__XX_,
  ___X__X_,__X__XX_,
  ___X____,XXX___X_,
  ___X____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_7A31[ 30] = { /* code 7A31 */
  ___XX___,____XX__,
  XXXXX_XX,XXXX____,
  _XXX__XX,_XX__XX_,
  __XX___X,_XX_XX__,
  XXXXX___,_XX_____,
  XXXXX_XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  __XXX_X_,_XX_XX__,
  _XXXX_XX,XXXXXX__,
  _XXXXXX_,_XX_XX__,
  XXXX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX__X_,____XX__,
  __XX__X_,___XXX__,
  __XX__X_,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_7DE8[ 32] = { /* code 7DE8 */
  ___X____,____XXX_,
  __XX__XX,XXXX____,
  __X_XXXX,________,
  _XX_X_XX,XXXXXX__,
  _X__X_XX,_____X__,
  XXXXX_XX,_____X__,
  XXXX__XX,XXXXXX__,
  __XX__XX,________,
  __X_X_XX,XXXXXXX_,
  _X_XXXXX,X_X_XXX_,
  XXX__XXX,X_X_XXX_,
  ______XX,XXXXXXX_,
  _XXXX_X_,X_X_XXX_,
  _X_X_XX_,X_X_XXX_,
  XX_X_XX_,X_X_XXX_,
  X_______,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_865F[ 30] = { /* code 865F */
  _XXXXX__,_XX_____,
  _XXXXX__,_XXXXX__,
  _X__XX__,_XX_____,
  _XXXXX_X,XXXXXXX_,
  _XXXXX_X,__X__XX_,
  _______X,_XXXX___,
  XXXXXX_X,__X_____,
  _XX____X,__XXXXX_,
  _XXXX__X,________,
  _XXXX__X,_X_XX___,
  ____X_XX,_X_XX___,
  ____X_XX,_X_XX_X_,
  ____X_XX,_X_XX_X_,
  _XXXX_X_,XX_XXXX_,
  __XX_XXX,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_8A8D[ 30] = { /* code 8A8D */
  __X___XX,XXXXXX__,
  __XX____,__X__X__,
  XXXXX___,_XX__X__,
  _______X,XXX__X__,
  _XXXX___,XX___X__,
  _______X,X____X__,
  _XXXXXXX,___XXX__,
  ________,_X______,
  ________,_XX_____,
  _XXXX___,__XX____,
  _X__X___,________,
  _X__X_XX,XX___X__,
  _X__X_X_,XX___XX_,
  _XXXXXX_,XX_XXXX_,
  _X__X___,XXXX__X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_8BA4[ 32] = { /* code 8BA4 */
  _X______,_X______,
  _XX_____,_X______,
  __XX____,_X______,
  ___X____,_X______,
  ________,_XX_____,
  XXXX____,_XX_____,
  XXXX____,_XX_____,
  __XX____,XXX_____,
  __XX____,XXX_____,
  __XX____,X_XX____,
  __XX___X,X_XX____,
  __XXX__X,X__XX___,
  __XXXXXX,___XX___,
  __XX__X_,____XX__,
  __X__XX_,_____XX_,
  _____X__,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_9009[ 30] = { /* code 9009 */
  _X____XX,_XX_____,
  _XXX__XX,_XX_____,
  ___X__XX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  XXXX_XX_,_XX_____,
  __XX_XXX,XXXXXXX_,
  __X__XXX,XXXXXXX_,
  _XX_____,X__X____,
  XXXX___X,X__X____,
  XXXX___X,X__X__X_,
  ___X___X,___X_XX_,
  __XX__XX,___XXXX_,
  __XXXX__,___XXX__,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_9078[ 30] = { /* code 9078 */
  _X___XXX,X_XXXX__,
  _XX__X__,X_X__X__,
  __X__XXX,X_XXXX__,
  XXXX_X__,__X_____,
  XXXX_X_X,X_XXXXX_,
  __XXXXX_,________,
  _XX____X,___X____,
  _X___XXX,XXXXXX__,
  XXXX___X,___X____,
  XXXXXXXX,XXXXXXX_,
  __XX___X,___X____,
  __X___XX,____XX__,
  _XXXXXX_,_____X__,
  XX_XXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_958B[ 30] = { /* code 958B */
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X_______,____XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___XX__,X___XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___X___,X___XX__,
  X__XX___,X___XX__,
  X__XX___,X_XXXX__,
  X__X____,X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_95DC[ 30] = { /* code 95DC */
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X__XX___,X___X___,
  X__X_X_X,_XX_X___,
  X_XXX__X,X___X___,
  X_XXXX_X,XXX_X___,
  X_______,___XX___,
  X_X__X_X,__X_X___,
  X_XXXX_X,XXX_X___,
  X___XX_X,____X___,
  X__XX__X,__XXX___,
  X_XX___X,__XXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[32] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4EFB } /* code 4EFB */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4F5C } /* code 4F5C */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_4FE1 } /* code 4FE1 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_505C } /* code 505C */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5173 } /* code 5173 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5177 } /* code 5177 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_52A1 } /* code 52A1 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_53F7 } /* code 53F7 */
  ,{  14,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_540D } /* code 540D */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_591A } /* code 591A */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5B8C } /* code 5B8C */
  ,{  15,  14,   1,   4,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5DE5 } /* code 5DE5 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5E8F } /* code 5E8F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_5F00 } /* code 5F00 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_6210 } /* code 6210 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_62E9 } /* code 62E9 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_64C7 } /* code 64C7 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_66F4 } /* code 66F4 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_6B62 } /* code 6B62 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_786E } /* code 786E */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_78BA } /* code 78BA */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_79F0 } /* code 79F0 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_7A31 } /* code 7A31 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_7DE8 } /* code 7DE8 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_865F } /* code 865F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_8A8D } /* code 8A8D */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_8BA4 } /* code 8BA4 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_9009 } /* code 9009 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_9078 } /* code 9078 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_958B } /* code 958B */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_95DC } /* code 95DC */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop32 = {
   0x95DC /* first character */
  ,0x95DC /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 31] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop31 = {
   0x958B /* first character */
  ,0x958B /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop30 = {
   0x9078 /* first character */
  ,0x9078 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop29 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop28 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop27 = {
   0x8A8D /* first character */
  ,0x8A8D /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop26 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop25 = {
   0x7DE8 /* first character */
  ,0x7DE8 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop24 = {
   0x7A31 /* first character */
  ,0x7A31 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop23 = {
   0x79F0 /* first character */
  ,0x79F0 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop22 = {
   0x78BA /* first character */
  ,0x78BA /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop21 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop20 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop19 = {
   0x66F4 /* first character */
  ,0x66F4 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop18 = {
   0x64C7 /* first character */
  ,0x64C7 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop17 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop16 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop15 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop14 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop13 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop12 = {
   0x5B8C /* first character */
  ,0x5B8C /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop11 = {
   0x591A /* first character */
  ,0x591A /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop10 = {
   0x540D /* first character */
  ,0x540D /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop9 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop8 = {
   0x52A1 /* first character */
  ,0x52A1 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop7 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop6 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop5 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop4 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop3 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop2 = {
   0x4EFB /* first character */
  ,0x4EFB /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_JS_0_Job_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

