/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_Pg_JS_1_JobSEQ_Microsoft JhengHei_22B.c          *
* Font:        微軟正黑體                                            *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\busundau\Documents\project\01-MTCS\MTCS-20260102--三頁個別字型弄好\20250707-字庫檔案\最後\Font_Pg_JS_1_JobSEQ_Microsoft JhengHei_22B.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0030[ 13] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0031[ 13] = { /* code 0031, DIGIT ONE */
  __XXX___,
  XXXXX___,
  X__XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0032[ 13] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _XXXXXX_,
  _X____XX,
  ______XX,
  ______XX,
  ______X_,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0033[ 13] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XXXXXXX_,
  X____XX_,
  _____XX_,
  ____XXX_,
  _XXXX___,
  _XXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0034[ 26] = { /* code 0034, DIGIT FOUR */
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ___XX_XX,________,
  ___X__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  _X____XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0035[ 13] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXXXXX__,
  ____XXX_,
  _____XX_,
  _____XX_,
  X___XXX_,
  XXXXXX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0036[ 13] = { /* code 0036, DIGIT SIX */
  ___XXXX_,
  __XXXXX_,
  _XXX____,
  _XX_____,
  XX______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  _XX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0037[ 26] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0038[ 13] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _XXXXXXX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXX___,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0039[ 13] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XXXXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  _____XX_,
  _X___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0041[ 26] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XX_,________,
  XXXXXX__,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXX____,X_______,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XXX_____,________,
  _XXX____,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0045[ 13] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0046[ 13] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,__X_____,
  _XX_____,________,
  XX______,________,
  XX______,________,
  XX____XX,XXX_____,
  XX____XX,XXX_____,
  XX______,_XX_____,
  _XX_____,_XX_____,
  _XXX____,_XX_____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX_____X,X_______,
  XX____XX,________,
  XX___XXX,________,
  XX___XX_,________,
  XX__XX__,________,
  XX_XXX__,________,
  XXXXX___,________,
  XX_XXX__,________,
  XX__XXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004C[ 13] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004D[ 26] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_____,__XXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX__X___,X__XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX___X_X,___XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___,
  XX____X_,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,_XX_____,
  XXXX____,_XX_____,
  XXXX____,_XX_____,
  XX_XX___,_XX_____,
  XX_XXX__,_XX_____,
  XX__XX__,_XX_____,
  XX___XX_,_XX_____,
  XX___XX_,_XX_____,
  XX____XX,_XX_____,
  XX_____X,XXX_____,
  XX_____X,XXX_____,
  XX______,XXX_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XX_____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0050[ 13] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XXXXXXX_,
  XX___XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  XXXXXXX_,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0051[ 32] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXX____,XXX_____,
  _XX_____,_XXX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,________,
  XXXXXXX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX____XX,________,
  XX____XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0053[ 13] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  _XX_____,
  _XXXXX__,
  ___XXXX_,
  _____XXX,
  ______XX,
  X_____XX,
  XXXXXXX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XXX____X,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0056[ 26] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX______,__XX____,
  XX______,__XX____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ____XX_X,________,
  ____XXXX,________,
  ____XXXX,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0057[ 39] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  _XX____X,XXX____X,X_______,
  __X___XX,__XX___X,________,
  __XX__XX,__XX__XX,________,
  __XX__XX,__XX__XX,________,
  ___X__X_,___X__X_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0058[ 26] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX______,_XX_____,
  _XX_____,XX______,
  __X____X,X_______,
  __XX__XX,X_______,
  ___XX_XX,________,
  ____XXX_,________,
  _____X__,________,
  ____XXX_,________,
  ___XX_XX,________,
  __XX___X,X_______,
  __XX____,X_______,
  _XX_____,XX______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX______,_XX_____,
  _XX_____,XX______,
  _XXX____,XX______,
  __XX___X,X_______,
  ___XX__X,X_______,
  ___XXXXX,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_005A[ 26] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXX_,
  _XXXXXXX,
  _X____XX,
  ______XX,
  _XXXXXXX,
  XXX___XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0062[ 28] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  XXX___X_,
  XX______,
  XX______,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XXX___X_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0067[ 26] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXX_X,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _X____XX,X_______,
  _XXXXXXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0068[ 28] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0069[ 13] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006A[ 17] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006B[ 28] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  XX___XX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXX____,________,
  XX_XX___,________,
  XX___XX_,________,
  XX____XX,________,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXX_,XXXXXX__,
  XXX__XXX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006E[ 18] = { /* code 006E, LATIN SMALL LETTER N */
  XX__XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006F[ 18] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0070[ 26] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XX_XXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0071[ 26] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  XXXXXX__,
  XX___X__,
  XXXX____,
  _XXXX___,
  ____XX__,
  X___XX__,
  XXXXXX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0076[ 18] = { /* code 0076, LATIN SMALL LETTER V */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XX____XX,____XX__,
  XX____XX,____XX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__X__,X__XX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,_XXX____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0078[ 18] = { /* code 0078, LATIN SMALL LETTER X */
  XX_____X,X_______,
  _XX___XX,________,
  __X__XX_,________,
  ___XXX__,________,
  ____X___,________,
  ___XXX__,________,
  __XX__X_,________,
  _XX___XX,________,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0079[ 26] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___X_X__,________,
  ___XXX__,________,
  ____XX__,________,
  ___XX___,________,
  __XXX___,________,
  XXXX____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_4FE1[ 34] = { /* code 4FE1 */
  ___XX___,XX______,
  ___X____,_X______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  _XXX____,________,
  _XXX_XXX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  XXXX____,________,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX____,________,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX_XX_,____XX__,
  __XX_XXX,XXXXXX__,
  __XX_XXX,XXXXXX__,
  __XX_XX_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_505C[ 30] = { /* code 505C */
  __XX____,XX______,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  _XX__XXX,XXXXXX__,
  _XX__XX_,____XX__,
  XXX__XXX,XXXXXX__,
  XXX_____,________,
  __X_XXXX,XXXXXXX_,
  __X_XX__,_____XX_,
  __X___XX,XXXXX___,
  __X_____,_XX_____,
  __X_____,_XX_____,
  __X_____,_XX_____,
  __X____X,XX______,
  __X____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5173[ 30] = { /* code 5173 */
  ____XX__,XXX_____,
  ____XX__,XXX_____,
  ___XX___,__XX____,
  __XX____,___XX___,
  __X_XXXX,XXXXX___,
  _XX_XXXX,XXXXXX__,
  _X_____X,______X_,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ______XX,XX______,
  _____XX_,_XX_____,
  ___XXX__,___XX___,
  XXXXX___,____XX__,
  XXX_____,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5177[ 30] = { /* code 5177 */
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____X___,__XX____,
  _XXXX___,___XXX__,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ________,___XX___,
  ________,___X____,
  _______X,XXXX____,
  _______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_540D[ 30] = { /* code 540D */
  ______XX,________,
  _____XXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  ___XXX__,___XX___,
  __XXXXX_,__XX____,
  _X____XX,_X______,
  _______X,X_______,
  ____XXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _X__X___,____XX__,
  ____X___,____XX__,
  ____X___,____XX__,
  ____XXXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  ____X___,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5426[ 30] = { /* code 5426 */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _______X,X_______,
  _____XXX,________,
  ___XXX_X,XXX_____,
  _XXXX__X,__XXXX__,
  _X_____X,_____X__,
  _______X,________,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5B8C[ 34] = { /* code 5B8C */
  ______XX,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__,
  _X_XXXXX,XXXX_X__,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  _____X__,XX______,
  ____XX__,XX___XX_,
  ____XX__,XX___XX_,
  __XXX___,XXXXXXX_,
  XXXX____,_XXXXX__,
  _X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5DE5[ 28] = { /* code 5DE5 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5E8F[ 32] = { /* code 5E8F */
  _______X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,________,
  _XX_XXXX,XXXXXX__,
  _XX_XXXX,XXXXXX__,
  _XX_____,__XXX___,
  _XX___XX,XXX_____,
  _XX____X,XX______,
  _XXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXX_,
  _XX_____,XX__XX__,
  _XX_____,XX__X___,
  XX____XX,XX______,
  _X____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5F00[ 30] = { /* code 5F00 */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ___XX___,__X_____,
  ___XX___,__X_____,
  ___X____,__X_____,
  __XX____,__X_____,
  _XX_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6210[ 32] = { /* code 6210 */
  ________,_X_XX___,
  ________,_X___X__,
  ________,_X______,
  __XXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXX_,
  __X_____,_X______,
  __XXXXX_,_X___X__,
  __XXXXX_,_XX_XX__,
  _XX___X_,_XX_X___,
  _XX___X_,_XXXX___,
  _XX___X_,__XX____,
  _XX___X_,__X_____,
  _X_XXXX_,_XXX__X_,
  _X__XX__,XX_X_XX_,
  XX_____X,X__XXXX_,
  ______X_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_62E7[ 30] = { /* code 62E7 */
  __XX____,_XX_____,
  __XX____,_XX_____,
  __XX__XX,XXXXXXX_,
  XXXXX_XX,XXXXXXX_,
  XXXXX_X_,_____XX_,
  __XX____,________,
  __XXX_XX,XXXXXXX_,
  __XXX_XX,XXXXXXX_,
  XXXX____,__X_____,
  XXXX____,__X_____,
  __XX____,__X_____,
  __XX____,__X_____,
  __XX____,__X_____,
  XXXX___X,XXX_____,
  _XX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_62E9[ 30] = { /* code 62E9 */
  __XX__XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  XXXXX__X,___XX___,
  XXXXX__X,X_XX____,
  __XX____,XXX_____,
  __XX___X,X_XXX___,
  __XXXXX_,_XX__XX_,
  _XXXX_XX,XXXXXX__,
  XXXX__XX,XXXXXX__,
  XXXX____,_XX_____,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX____,_XX_____,
  _XXX____,_XX_____,
  _XX_____,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_64C7[ 30] = { /* code 64C7 */
  __X__XXX,XXXXXXX_,
  __X__X__,X_XX_XX_,
  XXXX_XXX,XXXXXXX_,
  XXXX____,_X______,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  __XX_XXX,XXXXXXX_,
  _XXX___X,___XX___,
  XXXX___X,X__XX___,
  X_X__XXX,XXXXXX__,
  __X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,_X______,
  XXX_____,_X______,
  _XX_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6570[ 28] = { /* code 6570 */
  _X__X_XX,__X_____,
  __X_XXX_,__X_____,
  XXXXXXXX,_XXXXXX_,
  XXXXXXXX,_XXXXXX_,
  __X_X_X_,_X__XX__,
  _X__XXXX,XX__XX__,
  X___X___,X___XX__,
  ___X__X_,_X__X___,
  XXXXXXXX,_XXXX___,
  __X__XX_,__XX____,
  _XXX_X__,__XX____,
  ___XXX__,_XXXX___,
  __XX__X_,XX__XX__,
  XX_____X,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6578[ 32] = { /* code 6578 */
  ____X___,___X____,
  _XXXXXXX,__XX____,
  _X__X__X,__XX____,
  XXXXXXXX,X_XXXXX_,
  _X__X__X,__XXXXX_,
  _XXXXXXX,_XX__X__,
  ____X___,_XX_XX__,
  _XXXXXXX,_X__XX__,
  _X__X__X,__X_XX__,
  _XXXXXXX,__X_XX__,
  ___XX_XX,__XXX___,
  XXXXXXXX,X__XX___,
  __XX_XX_,___XX___,
  __XXXX__,__XXX___,
  __XXXXX_,_XX__X__,
  XXX____X,_X____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6587[ 32] = { /* code 6587 */
  _____XX_,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ____X___,__XX____,
  ___XX___,__XX____,
  ____XX__,_XX_____,
  ____XX__,_XX_____,
  _____XX_,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,XXX_____,
  __XXXX__,_XXXX___,
  XXXXX___,___XXXX_,
  _X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6B62[ 30] = { /* code 6B62 */
  _______X,X_______,
  _______X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,XXXXXX__,
  __XX___X,XXXXXX__,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_79F0[ 30] = { /* code 79F0 */
  XXXXXX__,XX______,
  _XXX____,X_______,
  ___X____,XXXXXXX_,
  ___X___X,XXXXXXX_,
  XXXXXX_X,__X__X__,
  XXXXXXXX,__X__X__,
  __XXX___,__X_XX__,
  __XXXX_X,X_X_X___,
  __XX_X_X,X_X_X___,
  _X_X___X,__X_XX__,
  _X_X__XX,__X__X__,
  X__X__X_,__X__XX_,
  ___X__X_,__X__XX_,
  ___X____,XXX___X_,
  ___X____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_7A31[ 30] = { /* code 7A31 */
  ___XX___,____XX__,
  XXXXX_XX,XXXX____,
  _XXX__XX,_XX__XX_,
  __XX___X,_XX_XX__,
  XXXXX___,_XX_____,
  XXXXX_XX,XXXXXX__,
  __XX__XX,XXXXXX__,
  __XXX_X_,_XX_XX__,
  _XXXX_XX,XXXXXX__,
  _XXXXXX_,_XX_XX__,
  XXXX_XXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  __XX__X_,____XX__,
  __XX__X_,___XXX__,
  __XX__X_,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_7D27[ 32] = { /* code 7D27 */
  ____X_XX,XXXXXX__,
  _X__X__X,X___XX__,
  _X__X___,XXXXX___,
  _X__X___,XXXX____,
  _X__X_XX,X__XX___,
  ______XX,_____XX_,
  _____XX_,__X_____,
  __XXXX__,_XX_____,
  ___XXXXX,X__X____,
  ____XXX_,___XX___,
  _XXXXXXX,XXXXXX__,
  _______X,_____X__,
  ____X__X,__XX____,
  __XX___X,____XX__,
  XX___XXX,_____XX_,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_865F[ 30] = { /* code 865F */
  _XXXXX__,_XX_____,
  _XXXXX__,_XXXXX__,
  _X__XX__,_XX_____,
  _XXXXX_X,XXXXXXX_,
  _XXXXX_X,__X__XX_,
  _______X,_XXXX___,
  XXXXXX_X,__X_____,
  _XX____X,__XXXXX_,
  _XXXX__X,________,
  _XXXX__X,_X_XX___,
  ____X_XX,_X_XX___,
  ____X_XX,_X_XX_X_,
  ____X_XX,_X_XX_X_,
  _XXXX_X_,XX_XXXX_,
  __XX_XXX,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9009[ 30] = { /* code 9009 */
  _X____XX,_XX_____,
  _XXX__XX,_XX_____,
  ___X__XX,XXXXXX__,
  XXXX_XXX,XXXXXX__,
  XXXX_XX_,_XX_____,
  __XX_XXX,XXXXXXX_,
  __X__XXX,XXXXXXX_,
  _XX_____,X__X____,
  XXXX___X,X__X____,
  XXXX___X,X__X__X_,
  ___X___X,___X_XX_,
  __XX__XX,___XXXX_,
  __XXXX__,___XXX__,
  _XXXXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9078[ 30] = { /* code 9078 */
  _X___XXX,X_XXXX__,
  _XX__X__,X_X__X__,
  __X__XXX,X_XXXX__,
  XXXX_X__,__X_____,
  XXXX_X_X,X_XXXXX_,
  __XXXXX_,________,
  _XX____X,___X____,
  _X___XXX,XXXXXX__,
  XXXX___X,___X____,
  XXXXXXXX,XXXXXXX_,
  __XX___X,___X____,
  __X___XX,____XX__,
  _XXXXXX_,_____X__,
  XX_XXXXX,XXXXXXX_,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_958B[ 30] = { /* code 958B */
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X___XX_X,X___XX__,
  XXXXXX_X,XXXXXX__,
  X_______,____XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___XX__,X___XX__,
  X_XXXXXX,XXX_XX__,
  X_XXXXXX,XXX_XX__,
  X___X___,X___XX__,
  X__XX___,X___XX__,
  X__XX___,X_XXXX__,
  X__X____,X_XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_95DC[ 30] = { /* code 95DC */
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X____X_X,X___X___,
  XXXXXX_X,XXXXX___,
  X__XX___,X___X___,
  X__X_X_X,_XX_X___,
  X_XXX__X,X___X___,
  X_XXXX_X,XXX_X___,
  X_______,___XX___,
  X_X__X_X,__X_X___,
  X_XXXX_X,XXX_X___,
  X___XX_X,____X___,
  X__XX__X,__XXX___,
  X_XX___X,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9846[ 30] = { /* code 9846 */
  _XXXXXX_,XXXXXXX_,
  _X_XX_X_,XXXXXXX_,
  _XXXXXX_,___X____,
  _X_XX_X_,XXXXXX__,
  _X_XX_X_,XXXXXX__,
  _XXXXXX_,XX___X__,
  ___XX___,XXXXXX__,
  ___XX___,XX___X__,
  XXXXXXXX,XXXXXX__,
  ___XX___,XX___X__,
  __XXXX__,XXXXXX__,
  _XXXX_X_,XXXXXX__,
  _X_XX_XX,_XX_X___,
  X__XX___,XX___X__,
  ___XX__X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9897[ 30] = { /* code 9897 */
  _XXXXXX_,XXXXXXX_,
  _XXXXXX_,XXXXXXX_,
  _X_XX_X_,__XX____,
  _XXXXXX_,XXXXXXX_,
  _X_XX_X_,XXXXXXX_,
  _XXXXXX_,XX_X_XX_,
  ___XX___,XX_X_XX_,
  ___XX___,XX_X_XX_,
  XXXXXXXX,XX_X_XX_,
  XXXXXXXX,XX_X_XX_,
  ___XXXX_,XXXX_XX_,
  __XXX_X_,XXX__XX_,
  _XXXX_XX,_XX_X___,
  XX_XX__X,XX___XX_,
  ___XX__X,X_____X_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[92] = {
   {   1,   1,   0,  17,   4, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0020 } /* code 0020, SPACE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  13,   2,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0039 } /* code 0039, DIGIT NINE */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  13,   1,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  13,   1,   4,  13, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  13,   2,   4,  13, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  13,   2,   4,   5, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,  13,   1,   4,   7, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  13,   2,   4,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  13,   2,   4,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  13,   2,   4,  14, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  12,  13,   1,   4,  14, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  12,  16,   1,   4,  14, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  13,   2,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  13,   1,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  13,   0,   4,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  10,  13,   1,   4,  13, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  13,   0,   4,  12, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  13,   0,   4,  18, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  13,   0,   4,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   9,   1,   8,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,   9,   1,   8,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  14,   0,   3,   6, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  14,   1,   3,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  13,   1,   4,   5, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  17,  -2,   4,   5, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  14,   1,   3,  10, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  14,   1,   3,   5, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,   9,   1,   8,  16, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  13,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   9,   1,   8,   7, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   9,   1,   8,   8, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  12,   0,   5,   7, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   9,   1,   8,  11, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,   9,   0,   8,  14, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,   9,   0,   8,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  13,   0,   8,   9, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,   9,   0,   8,   8, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_4FE1 } /* code 4FE1 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_505C } /* code 505C */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5173 } /* code 5173 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5177 } /* code 5177 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_53F7 } /* code 53F7 */
  ,{  14,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_540D } /* code 540D */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5426 } /* code 5426 */
  ,{  15,  17,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5B8C } /* code 5B8C */
  ,{  15,  14,   1,   4,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5DE5 } /* code 5DE5 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5E8F } /* code 5E8F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_5F00 } /* code 5F00 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6210 } /* code 6210 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_62E7 } /* code 62E7 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_62E9 } /* code 62E9 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_64C7 } /* code 64C7 */
  ,{  15,  14,   1,   4,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6570 } /* code 6570 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6578 } /* code 6578 */
  ,{  15,  16,   1,   2,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6587 } /* code 6587 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_6B62 } /* code 6B62 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_79F0 } /* code 79F0 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_7A31 } /* code 7A31 */
  ,{  15,  16,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_7D27 } /* code 7D27 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_865F } /* code 865F */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9009 } /* code 9009 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9078 } /* code 9078 */
  ,{  14,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_958B } /* code 958B */
  ,{  13,  15,   2,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_95DC } /* code 95DC */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9846 } /* code 9846 */
  ,{  15,  15,   1,   3,  17, acGUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_9897 } /* code 9897 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop33 = {
   0x9897 /* first character */
  ,0x9897 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 91] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop32 = {
   0x9846 /* first character */
  ,0x9846 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 90] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop31 = {
   0x95DC /* first character */
  ,0x95DC /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 89] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop30 = {
   0x958B /* first character */
  ,0x958B /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 88] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop29 = {
   0x9078 /* first character */
  ,0x9078 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 87] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop28 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 86] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop27 = {
   0x865F /* first character */
  ,0x865F /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 85] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop26 = {
   0x7D27 /* first character */
  ,0x7D27 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 84] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop25 = {
   0x7A31 /* first character */
  ,0x7A31 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 83] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop24 = {
   0x79F0 /* first character */
  ,0x79F0 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 82] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop23 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 81] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop22 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 80] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop21 = {
   0x6578 /* first character */
  ,0x6578 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 79] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop20 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 78] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop19 = {
   0x64C7 /* first character */
  ,0x64C7 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 77] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop18 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 76] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop17 = {
   0x62E7 /* first character */
  ,0x62E7 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 75] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop16 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 74] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop15 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 73] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop14 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 72] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop13 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 71] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop12 = {
   0x5B8C /* first character */
  ,0x5B8C /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 70] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop11 = {
   0x5426 /* first character */
  ,0x5426 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 69] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop10 = {
   0x540D /* first character */
  ,0x540D /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 68] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop9 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 67] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop8 = {
   0x5177 /* first character */
  ,0x5177 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 66] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop7 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 65] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop6 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 64] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop5 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 63] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop4 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_Pg_JS_1_JobSEQ_MicrosoftJhengHei_22B_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

